In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("production_logs.csv")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167946 entries, 0 to 167945
Data columns (total 27 columns):
 #   Column                     Non-Null Count   Dtype  
---  ------                     --------------   -----  
 0   PRODUCTIONDATE_DAY_LOC     167946 non-null  object 
 1   SHIFT_NAME                 167946 non-null  object 
 2   LINE_NAME                  167946 non-null  object 
 3   CO_TYPE                    145176 non-null  object 
 4   CREW_ID                    167787 non-null  object 
 5   AE_MODEL_CATEGORY          148392 non-null  object 
 6   SIZE_TYPE                  104949 non-null  object 
 7   SHIFT_NAME.1               167946 non-null  object 
 8   UTIL_REASON_DESCRIPTION    148392 non-null  object 
 9   DOWNTIME                   167946 non-null  int64  
 10  EFFECTIVE_RUNTIME          104949 non-null  float64
 11  GOOD_PRODUCTION_QTY        167946 non-null  int64  
 12  LUNCH_AND_BREAK            167946 non-null  int64  
 13  MEETING_AND_TRAINING       16

In [ ]:
df['PRODUCTIONDATE_DAY_LOC'] = pd.to_datetime(df['PRODUCTIONDATE_DAY_LOC'], dayfirst=True)
df.info()

/tmp/ipython-input-1561415343.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['PRODUCTIONDATE_DAY_LOC'] = pd.to_datetime(df['PRODUCTIONDATE_DAY_LOC'], dayfirst=True)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167946 entries, 0 to 167945
Data columns (total 27 columns):
 #   Column                     Non-Null Count   Dtype         
---  ------                     --------------   -----         
 0   PRODUCTIONDATE_DAY_LOC     167946 non-null  datetime64[ns]
 1   SHIFT_NAME                 167946 non-null  object        
 2   LINE_NAME                  167946 non-null  object        
 3   CO_TYPE                    145176 non-null  object        
 4   CREW_ID                    167787 non-null  object        
 5   AE_MODEL_CATEGORY          148392 non-null  object        
 6   SIZE_TYPE                  104949 non-null  object        
 7   SHIFT_NAME.1               167946 non-null  object        
 8   UTIL_REASON_DESCRIPTION    148392 non-null  object        
 9   DOWNTIME                   167946 non-null  int64         
 10  EFFECTIVE_RUNTIME          104949 non-null  float64       
 11  GOOD_PRODUCTION_QTY        167946 non-null  int64   

In [ ]:
df = df.sort_values(by=['PRODUCTIONDATE_DAY_LOC', 'SHIFT_NAME', 'LINE_NAME'], ascending=[True, True, True]).reset_index(drop=True)

In [ ]:
df_unplanned = df[df["AE_MODEL_CATEGORY"] == "Unplanned"] # thông tin về hoạt động không được lên lịch
df_plant_decision = df[df["AE_MODEL_CATEGORY"] == "Plant Decision"]
df_business_external = df[df["AE_MODEL_CATEGORY"] == "Business External"]

In [ ]:
df_unplanned

PRODUCTIONDATE_DAY_LOC   SHIFT_NAME LINE_NAME            CO_TYPE  \
160                2025-01-02  Afternoon-2  MAFT2201    Material_Handle   
161                2025-01-02  Afternoon-2  MAFT2201    Material_Handle   
163                2025-01-02  Afternoon-2  MAFT2201    Material_Handle   
164                2025-01-02  Afternoon-2  MAFT2201    Material_Handle   
167                2025-01-02  Afternoon-2  MAFT2201    Material_Handle   
...                       ...          ...       ...                ...   
167920             2025-06-30      Night-3  MKZA1501  Material_Filament   
167928             2025-06-30      Night-3  MKZA1502    Material_Handle   
167929             2025-06-30      Night-3  MKZA1502    Material_Handle   
167932             2025-06-30      Night-3  MKZA1502    Material_Handle   
167935             2025-06-30      Night-3  MKZA1502    Material_Handle   

       CREW_ID AE_MODEL_CATEGORY       SIZE_TYPE SHIFT_NAME.1  \
160          A         Unplanned       Renew 360  Afternoon-2   
161          A         Unplanned       Renew 360  Afternoon-2   
163          A         Unplanned       Renew 360  Afternoon-2   
164          A         Unplanned       Renew 360  Afternoon-2   
167          A         Unplanned       Renew 360  Afternoon-2   
...        ...               ...             ...          ...   
167920       C         Unplanned  Super Soft Pro      Night-3   
167928       C         Unplanned  Super Soft Pro      Night-3   
167929       C         Unplanned  Super Soft Pro      Night-3   
167932       C         Unplanned  Super Soft Pro      Night-3   
167935       C         Unplanned  Super Soft Pro      Night-3   

                                  UTIL_REASON_DESCRIPTION  DOWNTIME  ...  \
160         12-Filling tool - 1201-Mechanical adjustment.        17  ...   
161                  07-FLS - 0701-Mechanical adjustment.        12  ...   
163     09-In-feed conveyor - 0901-Mechanical adjustment.        13  ...   
164            06-Fiber box - 0601-Mechanical adjustment.        10  ...   
167               14-Fusing - 1401-Mechanical adjustment.        18  ...   
...                                                   ...       ...  ...   
167920  11-Auto handle feederT2-1102-Stuck handle on c...        10  ...   
167928  11-Auto handle feederT1-1102-Stuck handle on c...         9  ...   
167929  13-Filling toolT1-1306-Replace/adjust mechanic...        40  ...   
167932  06-Fiber boxT2-0602-Replace/adjust mechanical ...        10  ...   
167935                   13-Filling toolT2-1303-Clean jaw        10  ...   

        PRODUCTION_AVAILABLE_TIME  REJECT_PRODUCTION_QTY  RUN_TIME  \
160                            17                      0         0   
161                            12                      0         0   
163                            13                      0         0   
164                            10                      0         0   
167                            18                      0         0   
...                           ...                    ...       ...   
167920                         10                      0         0   
167928                          9                      0         0   
167929                         40                      0         0   
167932                         10                      0         0   
167935                         10                      0         0   

        CHANGEOVER_DURATION  CLEANING_AND_SANITIZATION  \
160                       0                          0   
161                       0                          0   
163                       0                          0   
164                       0                          0   
167                       0                          0   
...                     ...                        ...   
167920                    0                          0   
167928                    0                          0   
167929                    0                      

In [ ]:
df_unplanned.describe()

PRODUCTIONDATE_DAY_LOC      DOWNTIME  EFFECTIVE_RUNTIME  \
count                          56836  56836.000000            56836.0   
mean   2025-03-31 23:24:54.573861376     22.376803                0.0   
min              2025-01-02 00:00:00      1.000000                0.0   
25%              2025-02-20 00:00:00     10.000000                0.0   
50%              2025-04-01 00:00:00     15.000000                0.0   
75%              2025-05-14 00:00:00     23.000000                0.0   
max              2025-06-30 00:00:00    480.000000                0.0   
std                              NaN     28.657690                0.0   

       GOOD_PRODUCTION_QTY  LUNCH_AND_BREAK  MEETING_AND_TRAINING  NO_DEMAND  \
count              56836.0          56836.0               56836.0    56836.0   
mean                   0.0              0.0                   0.0        0.0   
min                    0.0              0.0                   0.0        0.0   
25%                    0.0              0.0                   0.0        0.0   
50%                    0.0              0.0                   0.0        0.0   
75%                    0.0              0.0                   0.0        0.0   
max                    0.0              0.0                   0.0        0.0   
std                    0.0              0.0                   0.0        0.0   

       PLANT_AVAILABLE_TIME  PLANT_EXPERIMENTATION  PRODUCTION_AVAILABLE_TIME  \
count          56836.000000                56836.0               56836.000000   
mean              22.376803                    0.0                  22.376803   
min                1.000000                    0.0                   1.000000   
25%               10.000000                    0.0                  10.000000   
50%               15.000000                    0.0                  15.000000   
75%               23.000000                    0.0                  23.000000   
max              480.000000                    0.0                 480.000000   
std               28.657690                    0.0                  28.657690   

       REJECT_PRODUCTION_QTY  RUN_TIME  CHANGEOVER_DURATION  \
count                56836.0   56836.0              56836.0   
mean                     0.0       0.0                  0.0   
min                      0.0       0.0                  0.0   
25%                      0.0       0.0                  0.0   
50%                      0.0       0.0                  0.0   
75%                      0.0       0.0                  0.0   
max                      0.0       0.0                  0.0   
std                      0.0       0.0                  0.0   

       CLEANING_AND_SANITIZATION  BUSINESS_EXTERNAL_TIME  PLANNED_MAINTENANCE  \
count                    56836.0                 56836.0              56836.0   
mean                         0.0                     0.0                  0.0   
min                          0.0                     0.0                  0.0   
25%                          0.0                     0.0                  0.0   
50%                          0.0                     0.0                  0.0   
75%                          0.0                     0.0                  0.0   
max                          0.0                     0.0                  0.0   
std                          0.0                     0.0                  0.0   

         TOTAL_TIME  WAITING_TIME  PRODUCTION_ORDER_RATE  
count  56836.000000       56836.0           56836.000000  
mean      22.376803           0.0              65.216067  
min        1.000000           0.0              20.000000  
25%       10.000000           0.0              60.000000  
50%       15.000000           0.0              67.000000  
75%       23.000000           0.0              78.950000  
max      480.000000           0.0             172.000000  
std       28.657690           0.0              20.086924

GOOD_PRODUCTION_QTY = REJECT_PRODUCTION_QTY	-> Không có sản phẩm đầu ra

Ta thấy các giá trị thống kê của DOWNTIME = PLANT_AVAILABLE_TIME và RUNTIME = 0 (Máy không thực hiện sản xuất sản phẩm và không được vận hành)

In [ ]:
df_unplanned['DOWNTIME'].equals(df_unplanned['PLANT_AVAILABLE_TIME'])

True

In [ ]:
df_unplanned['PRODUCTION_AVAILABLE_TIME'].equals(df_unplanned['PLANT_AVAILABLE_TIME'])

True

In [ ]:
df_unplanned["PRODUCTIONDATE_DAY_LOC"].value_counts()

PRODUCTIONDATE_DAY_LOC
2025-03-24    482
2025-02-20    476
2025-02-17    473
2025-05-14    473
2025-04-09    470
             ... 
2025-02-03    179
2025-02-09    121
2025-04-06    114
2025-01-19     66
2025-03-16     56
Name: count, Length: 153, dtype: int64

In [ ]:
df_unplanned["LINE_NAME"].unique()

array(['MAFT2201', 'MAFT2202', 'MAFT2203', 'MHPT2301', 'MHPT2302',
       'MHPT2303', 'MHPT2304', 'MHPT2305', 'MHPT2306', 'MHPT2307',
       'MKBC0101', 'MKBC0102', 'MKBC0201', 'MKBC0202', 'MKBC0301',
       'MKBC0302', 'MKBC0402', 'MKBC0501', 'MKBC0502', 'MKBC0601',
       'MKBC0602', 'MKBC0701', 'MKBC0902', 'MKBC1001', 'MKBC1101',
       'MKBC1102', 'MKBC1201', 'MKBC1202', 'MKBC1301', 'MKFX2101',
       'MKTU2001', 'MKTU2002', 'MKTU2003', 'MKTU2004', 'MKTU2005',
       'MKTU2006', 'MKZA1401', 'MKZA1801', 'MKZA1802', 'MKBC0401',
       'MKBC0901', 'MKBC1002', 'MKZA1501', 'MKZA1601', 'MKBC0702',
       'MKFX2102', 'MKZA1701', 'MKZA1702', 'MKZA1502', 'MKZA1602',
       'MKZA1402', 'MAFT2205', 'MAFT2204'], dtype=object)

In [ ]:
df_unplanned["SIZE_TYPE"].value_counts()

SIZE_TYPE
Total Defense Shield            9975
Classic Clean 100               7545
Deep Action White               4925
Total Action Model S            3836
EcoFresh Plus                   3622
Pro-Clean 5000                  3166
Super Soft Tech                 2862
Renew 360                       2757
PureMint Fresh                  1814
GreenClean Pro                  1729
Pro-Shield Complete             1520
Junior Sparkle (Ages 2+)        1435
ActiveClean Guard               1284
Super Soft Pro                  1134
Total Action Green              1023
Kids FunBrush (Tandy)            982
ActiveClean Model X              945
Defense Action Pro               936
Zenith Active                    919
Precision Grip 2.0               855
Classic White 110                775
Advanced Hydro-Clean             546
Oral Care 360                    504
Ocean Explorer (Ages 6+)         500
Zenith GreenClean                328
GreenClean Classic               249
Safari Explorer (Ages 6+)        223
EcoFresh Green                   202
Junior Guard Taper (Ages 5+)      87
EcoSoft Classic                   87
Zenith Classic Clean              52
GreenClean Ultra                  19
Name: count, dtype: int64

In [ ]:
df_unplanned["UTIL_REASON_DESCRIPTION"].unique()

array(['12-Filling tool - 1201-Mechanical adjustment.',
       '07-FLS - 0701-Mechanical adjustment.',
       '09-In-feed conveyor - 0901-Mechanical adjustment.',
       '06-Fiber box - 0601-Mechanical adjustment.',
       '14-Fusing - 1401-Mechanical adjustment.',
       '03-Change material - 0301-Change material',
       '11-Segment - 1101-Mechanical adjustment.',
       '02-Quality - 0202-Rework',
       '18-Autofeeder - 1802-Stuck handle on chain',
       '10-Robot - 1002-Adjust mechanical of robot',
       '12-Filling tool - 1201-Cleaning Jaw',
       '06-Fiber box - 0602-Adjust sparepart',
       '18-Autofeeder - 1801-Double hadle on chain',
       '18-Autofeeder - 1806-Replace Robots mechanical',
       '27-Autosorter - 2701-Handle on chain stuck',
       '17-End Feeder - 1702-Jammed handle on chain',
       '11-Auto handle feederT2-1101-Double hadle on chain',
       '11-Auto handle feederT3-1101-Double hadle on chain',
       '11-Auto handle feederT1-1101-Double hadle on chain

In [ ]:
df_unplanned["UTIL_REASON_DESCRIPTION"].value_counts()

UTIL_REASON_DESCRIPTION
17-End Feeder - 1702-Jammed handle on chain                             4093
02-Quality - 0202-Rework                                                3258
03-Change material - 0301-Change material                               3227
13-FM chain - 1306-Handle stuck on FM                                   3119
17-End Feeder - 1701-Double handle on chain                             2306
                                                                        ... 
14-Robot infeed - 1403-Wrong gripper                                       1
07-Anchor wire feedingT3-0701-Adjust/Replace mechanical parts of CAM       1
19-Vario Flow - 1901-Mechanical Vario Flow replacement                     1
10-In-feed Head Plate conveyor - 1003-Pneumatic cylinder adjustment        1
14-Fusing - 1406-Replace new electronic instruments                        1
Name: count, Length: 509, dtype: int64

In [ ]:
# 1. Đếm tần suất xuất hiện của từng mô tả
desc_count = df_unplanned['UTIL_REASON_DESCRIPTION'].value_counts().reset_index()
desc_count.columns = ['Description', 'Count']

# 2. Tính phần trăm và phần trăm tích lũy
desc_count['Percent'] = desc_count['Count'] / desc_count['Count'].sum()
desc_count['CumulativePercent'] = desc_count['Percent'].cumsum()

# 3. Lọc các Description nằm trong 80% đầu tiên
top_80 = desc_count[desc_count['CumulativePercent'] <= 0.8]

# Hiển thị kết quả
print(top_80)
print("\nTổng số dòng trong 80% đầu tiên:", top_80['Count'].sum())
print("Tổng số dòng toàn bộ:", desc_count['Count'].sum())
print("Tỷ lệ bao phủ:", round(top_80['Count'].sum() / desc_count['Count'].sum() * 100, 2), "%")

                                          Description  Count   Percent  \
0         17-End Feeder - 1702-Jammed handle on chain   4093  0.072014   
1                            02-Quality - 0202-Rework   3258  0.057323   
2           03-Change material - 0301-Change material   3227  0.056777   
3               13-FM chain - 1306-Handle stuck on FM   3119  0.054877   
4         17-End Feeder - 1701-Double handle on chain   2306  0.040573   
..                                                ...    ...       ...   
56  12-TurretT2-1205-Adjust  handle supply box pos...    174  0.003061   
57    14-Fusing - 1407-Coordination/program adjusment    168  0.002956   
58            16-Coordination - 1604-Adjust parameter    164  0.002885   
59  11-Auto handle feeder - 1103-Adjust robot posi...    156  0.002745   
60  11-Auto handle feederT1-1106-Replace/adjust me...    155  0.002727   

    CumulativePercent  
0            0.072014  
1            0.129337  
2            0.186114  
3            0.

Ta thấy top80 discription khá rời rạc, không tập trung vào một mô tả cụ thể nào => Tách cấu trúc description thành từng phần để dễ đánh giá

In [ ]:
# Tách thành các phần với cách làm linh hoạt
split_desc = df_unplanned['UTIL_REASON_DESCRIPTION'].str.split('-', n=3, expand=True)

# Tách phần ID
df_unplanned['ID'] = split_desc[0]

# Tách phần máy
df_unplanned['Machine_Name'] = split_desc[1]

# Tách mã lỗi
df_unplanned['Error_Code'] = split_desc[2]

# Tách mô tả lỗi chi tiết
df_unplanned['Error_Decrisption'] = split_desc[3]

/tmp/ipython-input-885556803.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unplanned['ID'] = split_desc[0]
/tmp/ipython-input-885556803.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unplanned['Machine_Name'] = split_desc[1]
/tmp/ipython-input-885556803.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/us

In [ ]:
df_unplanned[['ID', 'Machine_Name', 'Error_Code', 'Error_Decrisption']].head()

ID   Machine_Name      Error_Code             Error_Decrisption
160  12  Filling tool             1201        Mechanical adjustment.
161  07           FLS             0701        Mechanical adjustment.
163  09             In  feed conveyor    0901-Mechanical adjustment.
164  06     Fiber box             0601        Mechanical adjustment.
167  14        Fusing             1401        Mechanical adjustment.

In [ ]:
df_unplanned['ID'].value_counts()

ID
11    14564
17     8220
13     5220
03     3830
14     3822
06     3809
18     3391
02     3335
12     3138
16     2184
05     1404
10     1132
07      773
20      572
15      286
09      178
04      169
25      143
27      121
26       99
19       98
29       84
23       74
24       50
22       47
01       39
08       29
21       21
28        4
Name: count, dtype: int64

# ID

## ID = 11

In [ ]:
df_unplanned_11 = df_unplanned[df_unplanned['ID'] == '11']
df_unplanned_11

PRODUCTIONDATE_DAY_LOC   SHIFT_NAME LINE_NAME            CO_TYPE  \
170                2025-01-02  Afternoon-2  MAFT2202  Material_Filament   
252                2025-01-02  Afternoon-2  MKBC0102  Material_Filament   
253                2025-01-02  Afternoon-2  MKBC0102  Material_Filament   
256                2025-01-02  Afternoon-2  MKBC0102  Material_Filament   
270                2025-01-02  Afternoon-2  MKBC0202  Material_Filament   
...                       ...          ...       ...                ...   
167908             2025-06-30      Night-3  MKZA1401  Material_Filament   
167909             2025-06-30      Night-3  MKZA1401  Material_Filament   
167918             2025-06-30      Night-3  MKZA1501  Material_Filament   
167920             2025-06-30      Night-3  MKZA1501  Material_Filament   
167928             2025-06-30      Night-3  MKZA1502    Material_Handle   

       CREW_ID AE_MODEL_CATEGORY            SIZE_TYPE SHIFT_NAME.1  \
170          A         Unplanned            Renew 360  Afternoon-2   
252          A         Unplanned  Pro-Shield Complete  Afternoon-2   
253          A         Unplanned  Pro-Shield Complete  Afternoon-2   
256          A         Unplanned  Pro-Shield Complete  Afternoon-2   
270          A         Unplanned       Pro-Clean 5000  Afternoon-2   
...        ...               ...                  ...          ...   
167908       C         Unplanned    ActiveClean Guard      Night-3   
167909       C         Unplanned    ActiveClean Guard      Night-3   
167918       C         Unplanned       Super Soft Pro      Night-3   
167920       C         Unplanned       Super Soft Pro      Night-3   
167928       C         Unplanned       Super Soft Pro      Night-3   

                                  UTIL_REASON_DESCRIPTION  DOWNTIME  ...  \
170              11-Segment - 1101-Mechanical adjustment.         8  ...   
252     11-Auto handle feederT2-1101-Double hadle on c...        40  ...   
253     11-Auto handle feederT3-1101-Double hadle on c...        40  ...   
256     11-Auto handle feederT1-1101-Double hadle on c...        43  ...   
270     11-Auto handle feederT3-1103-Adjust robot posi...        10  ...   
...                                                   ...       ...  ...   
167908  11-Auto handle feederT3-1101-Double hadle on c...         9  ...   
167909  11-Auto handle feederT2-1102-Stuck handle on c...        10  ...   
167918  11-Auto handle feederT3-1102-Stuck handle on c...         6  ...   
167920  11-Auto handle feederT2-1102-Stuck handle on c...        10  ...   
167928  11-Auto handle feederT1-1102-Stuck handle on c...         9  ...   

        CLEANING_AND_SANITIZATION  BUSINESS_EXTERNAL_TIME  \
170                             0                       0   
252                             0                       0   
253                             0                       0   
256                             0                       0   
270                             0                       0   
...                           ...                     ...   
167908                          0                       0   
167909                          0                       0   
167918                          0                       0   
167920                          0                       0   
167928                          0                       0   

        PLANNED_MAINTENANCE  TOTAL_TIME  WAITING_TIME  PRODUCTION_ORDER_RATE  \
170                       0           8             0                  24.00   
252                       0          40             0                  81.40   
253                       0          40             0                  81.40   
256                       0          43             0                  81.40   
270                       0          10             0                  81.40   
...                     ...         ...           ...                    ...   
167908                    0           9             0      

In [ ]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency

# --- 1. Tạo cột đánh dấu lỗi ID=11 ---
df['IS_ERROR_11'] = 0
df.loc[df.index.isin(df_unplanned_11.index), 'IS_ERROR_11'] = 1

# --- 2. Hàm tính Cramér’s V để đo mức độ ảnh hưởng (0 → 1) ---
def cramers_v(confusion_matrix):
    chi2 = chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum().sum()
    r, k = confusion_matrix.shape
    return np.sqrt(chi2 / (n * (min(r - 1, k - 1))))

# --- 3. Hàm kiểm định Chi-square + Cramér’s V ---
def chi_square_test(df, column):
    # Chuẩn hóa: loại NaN & chuyển về category
    data = df[[column, 'IS_ERROR_11']].dropna()
    data[column] = data[column].astype('category')

    # Tạo bảng chéo
    contingency_table = pd.crosstab(data[column], data['IS_ERROR_11'])

    # Nếu bảng quá nhỏ hoặc chỉ có 1 chiều thì bỏ qua
    if contingency_table.shape[0] < 2 or contingency_table.shape[1] < 2:
        print(f"\n Không đủ dữ liệu để kiểm định với {column}")
        return

    # Chi-square
    chi2, p, dof, expected = chi2_contingency(contingency_table)

    # Cramér’s V
    V = cramers_v(contingency_table)

    print(f"\n Yếu tố: {column}")
    print(f"  Chi-square = {chi2:.3f}")
    print(f"  p-value    = {p:.5f}")
    print(f"  Cramér's V = {V:.4f}")

    if p < 0.05:
        print("    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 11")
    else:
        print("    Kết luận: Không ảnh hưởng đáng kể")

# --- 4. Chạy kiểm định cho các yếu tố ---
for col in ['LINE_NAME', 'SIZE_TYPE', 'CREW_ID']:
    chi_square_test(df, col)



 Yếu tố: LINE_NAME
  Chi-square = 8318.410
  p-value    = 0.00000
  Cramér's V = 0.2226
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 11

 Yếu tố: SIZE_TYPE
  Chi-square = 3384.010
  p-value    = 0.00000
  Cramér's V = 0.1796
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 11

 Yếu tố: CREW_ID
  Chi-square = 164.914
  p-value    = 0.00000
  Cramér's V = 0.0314
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 11


Cả LINE_NAME, SIZE_TYPE, và CREW_ID đều có ảnh hưởng đáng kể tới lỗi ID = 11 (p-value = 0.00000).

Tuy nhiên, mức độ ảnh hưởng khác nhau rõ rệt dựa trên Cramér’s V:

- LINE_NAME là yếu tố ảnh hưởng mạnh nhất (V = 0.2226) → Đây là yếu tố chính cần tập trung.

- SIZE_TYPE có ảnh hưởng nhưng yếu hơn (V = 0.1796).

- CREW_ID ảnh hưởng rất nhỏ, gần như không đáng kể (V = 0.0314)

In [ ]:
df_unplanned_11["LINE_NAME"].value_counts()

LINE_NAME
MKBC0901    1033
MKBC0102     933
MKBC0902     735
MKBC0502     688
MKBC0302     610
MKBC0202     607
MKBC1002     585
MKBC0601     517
MKBC0101     499
MKBC1301     431
MKBC0301     417
MKBC0602     412
MKBC0702     397
MKBC1202     395
MKBC1102     387
MKZA1402     369
MKTU2003     366
MKTU2004     358
MKBC1101     350
MKTU2001     343
MKBC1001     342
MKTU2005     331
MKTU2002     312
MKBC0701     267
MKZA1401     261
MKTU2006     254
MKZA1501     241
MKZA1802     240
MKZA1502     227
MKBC0501     220
MKBC1201     215
MKZA1702     190
MKBC0201     190
MKZA1801     182
MKZA1701     141
MKBC0402     105
MKBC0401      86
MKZA1601      81
MKZA1602      72
MAFT2203      23
MHPT2307      22
MHPT2303      20
MHPT2306      18
MAFT2204      17
MHPT2305      13
MAFT2205      12
MHPT2301      12
MHPT2302      11
MHPT2304       9
MAFT2202       8
MKFX2101       6
MAFT2201       3
MKFX2102       1
Name: count, dtype: int64

## ID = 17

In [ ]:
df_unplanned_17 = df_unplanned[df_unplanned['ID'] == '17']
df_unplanned_17

PRODUCTIONDATE_DAY_LOC   SHIFT_NAME LINE_NAME            CO_TYPE  \
250                2025-01-02  Afternoon-2  MKBC0101    Material_Handle   
260                2025-01-02  Afternoon-2  MKBC0201    Material_Handle   
277                2025-01-02  Afternoon-2  MKBC0202  Material_Filament   
289                2025-01-02  Afternoon-2  MKBC0301  Material_Filament   
338                2025-01-02  Afternoon-2  MKBC0502    Material_Handle   
...                       ...          ...       ...                ...   
167617             2025-06-30        Day-1  MKZA1702    Material_Handle   
167723             2025-06-30      Night-3  MKBC0301  Material_Filament   
167731             2025-06-30      Night-3  MKBC0302    Material_Handle   
167826             2025-06-30      Night-3  MKBC1101  Material_Filament   
167836             2025-06-30      Night-3  MKBC1102    Material_Handle   

       CREW_ID AE_MODEL_CATEGORY              SIZE_TYPE SHIFT_NAME.1  \
250          A         Unplanned  Kids FunBrush (Tandy)  Afternoon-2   
260          A         Unplanned          EcoFresh Plus  Afternoon-2   
277          A         Unplanned         Pro-Clean 5000  Afternoon-2   
289          A         Unplanned   Total Defense Shield  Afternoon-2   
338          A         Unplanned        Super Soft Tech  Afternoon-2   
...        ...               ...                    ...          ...   
167617       A         Unplanned      Deep Action White        Day-1   
167723       C         Unplanned      Classic Clean 100      Night-3   
167731       C         Unplanned          EcoFresh Plus      Night-3   
167826       C         Unplanned      Classic Clean 100      Night-3   
167836       C         Unplanned          EcoFresh Plus      Night-3   

                            UTIL_REASON_DESCRIPTION  DOWNTIME  ...  \
250     17-End Feeder - 1702-Jammed handle on chain        12  ...   
260     17-End Feeder - 1702-Jammed handle on chain        15  ...   
277     17-End Feeder - 1702-Jammed handle on chain        20  ...   
289     17-End Feeder - 1702-Jammed handle on chain        20  ...   
338     17-End Feeder - 1702-Jammed handle on chain        17  ...   
...                                             ...       ...  ...   
167617    17-End Feeder - 1703-Wrong position robot        23  ...   
167723  17-End Feeder - 1702-Jammed handle on chain        10  ...   
167731  17-End Feeder - 1701-Double handle on chain        17  ...   
167826  17-End Feeder - 1702-Jammed handle on chain        17  ...   
167836  17-End Feeder - 1702-Jammed handle on chain        15  ...   

        CLEANING_AND_SANITIZATION  BUSINESS_EXTERNAL_TIME  \
250                             0                       0   
260                             0                       0   
277                             0                       0   
289                             0                       0   
338                             0                       0   
...                           ...                     ...   
167617                          0                       0   
167723                          0                       0   
167731                          0                       0   
167826                          0                       0   
167836                          0                       0   

        PLANNED_MAINTENANCE  TOTAL_TIME  WAITING_TIME  PRODUCTION_ORDER_RATE  \
250                       0          12             0                  86.00   
260                       0          15             0                  85.70   
277                       0          20             0                  81.40   
289                       0          20             0                  78.90   
338                       0          17             0                  78.95   
...                     ...         ...           ...                    ...   
167617                    0          23             0                  51.00   
167723                    0

In [ ]:
df['IS_ERROR_17'] = 0
df.loc[df.index.isin(df_unplanned_17.index), 'IS_ERROR_17'] = 1

def chi_square_test_17(df, column):
    data = df[[column, 'IS_ERROR_17']].dropna()
    data[column] = data[column].astype('category')
    contingency_table = pd.crosstab(data[column], data['IS_ERROR_17'])
    if contingency_table.shape[0] < 2 or contingency_table.shape[1] < 2:
        print(f"\nKhông đủ dữ liệu để kiểm định với {column}")
        return
    chi2, p, dof, expected = chi2_contingency(contingency_table)
    V = cramers_v(contingency_table)
    print(f"\nYếu tố: {column}")
    print(f"  Chi-square = {chi2:.3f}")
    print(f"  p-value    = {p:.5f}")
    print(f"  Cramér's V = {V:.4f}")
    if p < 0.05:
        print("    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 17")
    else:
        print("    Kết luận: Không ảnh hưởng đáng kể")

for col in ['LINE_NAME', 'SIZE_TYPE', 'CREW_ID']:
    chi_square_test_17(df, col)



Yếu tố: LINE_NAME
  Chi-square = 8253.263
  p-value    = 0.00000
  Cramér's V = 0.2217
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 17

Yếu tố: SIZE_TYPE
  Chi-square = 6518.332
  p-value    = 0.00000
  Cramér's V = 0.2492
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 17

Yếu tố: CREW_ID
  Chi-square = 161.773
  p-value    = 0.00000
  Cramér's V = 0.0311
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 17


Cả LINE_NAME, SIZE_TYPE và CREW_ID đều có ảnh hưởng đáng kể tới lỗi ID = 17 (p-value = 0.00000).

Tuy nhiên, mức độ ảnh hưởng khác nhau rõ rệt dựa trên Cramér’s V:

- SIZE_TYPE là yếu tố ảnh hưởng mạnh nhất (V = 0.2492) → Đây là yếu tố chính cần tập trung.

- LINE_NAME có ảnh hưởng đáng kể nhưng yếu hơn (V = 0.2217).

- CREW_ID ảnh hưởng rất nhỏ, gần như không đáng kể (V = 0.0311).

In [ ]:
df_unplanned_17["SIZE_TYPE"].value_counts()

SIZE_TYPE
Pro-Clean 5000               1271
EcoFresh Plus                1197
Classic Clean 100            1184
Total Defense Shield         1057
Junior Sparkle (Ages 2+)      427
Precision Grip 2.0            374
Super Soft Tech               352
Deep Action White             329
Kids FunBrush (Tandy)         296
Pro-Shield Complete           296
ActiveClean Model X           232
Zenith Active                 211
ActiveClean Guard             209
Classic White 110             201
Super Soft Pro                190
Ocean Explorer (Ages 6+)      169
Defense Action Pro            121
Safari Explorer (Ages 6+)      76
Total Action Model S           16
Zenith Classic Clean            6
Advanced Hydro-Clean            2
PureMint Fresh                  2
Renew 360                       1
Oral Care 360                   1
Name: count, dtype: int64

## ID = 13

In [ ]:
df_unplanned_13 = df_unplanned[df_unplanned['ID'] == '13']
df_unplanned_13

PRODUCTIONDATE_DAY_LOC   SHIFT_NAME LINE_NAME            CO_TYPE  \
265                2025-01-02  Afternoon-2  MKBC0201    Material_Handle   
269                2025-01-02  Afternoon-2  MKBC0201    Material_Handle   
287                2025-01-02  Afternoon-2  MKBC0301  Material_Filament   
290                2025-01-02  Afternoon-2  MKBC0302    Material_Handle   
337                2025-01-02  Afternoon-2  MKBC0502    Material_Handle   
...                       ...          ...       ...                ...   
167760             2025-06-30      Night-3  MKBC0502    Material_Handle   
167794             2025-06-30      Night-3  MKBC0901  Material_Filament   
167814             2025-06-30      Night-3  MKBC1002  Material_Filament   
167929             2025-06-30      Night-3  MKZA1502    Material_Handle   
167935             2025-06-30      Night-3  MKZA1502    Material_Handle   

       CREW_ID AE_MODEL_CATEGORY             SIZE_TYPE SHIFT_NAME.1  \
265          A         Unplanned         EcoFresh Plus  Afternoon-2   
269          A         Unplanned         EcoFresh Plus  Afternoon-2   
287          A         Unplanned  Total Defense Shield  Afternoon-2   
290          A         Unplanned         EcoFresh Plus  Afternoon-2   
337          A         Unplanned       Super Soft Tech  Afternoon-2   
...        ...               ...                   ...          ...   
167760       C         Unplanned  Total Action Model S      Night-3   
167794       C         Unplanned     Classic Clean 100      Night-3   
167814       C         Unplanned     Classic Clean 100      Night-3   
167929       C         Unplanned        Super Soft Pro      Night-3   
167935       C         Unplanned        Super Soft Pro      Night-3   

                                  UTIL_REASON_DESCRIPTION  DOWNTIME  ...  \
265                 13-FM chain - 1306-Handle stuck on FM        25  ...   
269     13-FM chain - 1302-Replace details of clamping...        20  ...   
287                 13-FM chain - 1306-Handle stuck on FM        13  ...   
290                 13-FM chain - 1306-Handle stuck on FM        15  ...   
337                 13-FM chain - 1306-Handle stuck on FM        50  ...   
...                                                   ...       ...  ...   
167760              13-FM chain - 1306-Handle stuck on FM         4  ...   
167794  13-Filling toolT3-1307-Replace/adjust mechanic...         8  ...   
167814  13-Filling toolT1-1307-Replace/adjust mechanic...         6  ...   
167929  13-Filling toolT1-1306-Replace/adjust mechanic...        40  ...   
167935                   13-Filling toolT2-1303-Clean jaw        10  ...   

        CLEANING_AND_SANITIZATION  BUSINESS_EXTERNAL_TIME  \
265                             0                       0   
269                             0                       0   
287                             0                       0   
290                             0                       0   
337                             0                       0   
...                           ...                     ...   
167760                          0                       0   
167794                          0                       0   
167814                          0                       0   
167929                          0                       0   
167935                          0                       0   

        PLANNED_MAINTENANCE  TOTAL_TIME  WAITING_TIME  PRODUCTION_ORDER_RATE  \
265                       0          25             0                  85.70   
269                       0          20             0                  85.70   
287                       0          13             0                  78.90   
290                       0          15             0                  86.00   
337                       0          50             0                  78.95   
...                     ...         ...           ...                    ...   
167760                    0           4        

In [ ]:
df['IS_ERROR_13'] = 0
df.loc[df.index.isin(df_unplanned_13.index), 'IS_ERROR_13'] = 1

def chi_square_test_13(df, column):
    data = df[[column, 'IS_ERROR_13']].dropna()
    data[column] = data[column].astype('category')
    contingency_table = pd.crosstab(data[column], data['IS_ERROR_13'])
    if contingency_table.shape[0] < 2 or contingency_table.shape[1] < 2:
        print(f"\nKhông đủ dữ liệu để kiểm định với {column}")
        return
    chi2, p, dof, expected = chi2_contingency(contingency_table)
    V = cramers_v(contingency_table)
    print(f"\nYếu tố: {column}")
    print(f"  Chi-square = {chi2:.3f}")
    print(f"  p-value    = {p:.5f}")
    print(f"  Cramér's V = {V:.4f}")
    if p < 0.05:
        print("    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 13")
    else:
        print("    Kết luận: Không ảnh hưởng đáng kể")

for col in ['LINE_NAME', 'SIZE_TYPE', 'CREW_ID']:
    chi_square_test_13(df, col)



Yếu tố: LINE_NAME
  Chi-square = 3731.471
  p-value    = 0.00000
  Cramér's V = 0.1491
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 13

Yếu tố: SIZE_TYPE
  Chi-square = 1470.422
  p-value    = 0.00000
  Cramér's V = 0.1184
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 13

Yếu tố: CREW_ID
  Chi-square = 170.363
  p-value    = 0.00000
  Cramér's V = 0.0319
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 13


Cả LINE_NAME, SIZE_TYPE và CREW_ID đều có ảnh hưởng đáng kể tới lỗi ID = 13 (p-value = 0.00000).

Tuy nhiên, mức độ ảnh hưởng khác nhau rõ rệt dựa trên Cramér’s V:

- LINE_NAME là yếu tố ảnh hưởng mạnh nhất (V = 0.1491) → Đây là yếu tố chính cần tập trung.

- SIZE_TYPE có ảnh hưởng vừa phải (V = 0.1184).

- CREW_ID ảnh hưởng rất nhỏ, gần như không đáng kể (V = 0.0319).

In [ ]:
df_unplanned_13["LINE_NAME"].value_counts()

LINE_NAME
MKBC0902    478
MKBC0901    361
MKBC0201    300
MKBC0202    277
MKBC1202    225
MKBC0102    223
MKZA1501    217
MKBC0502    210
MKZA1401    195
MKBC0501    193
MKBC0101    180
MKBC0302    168
MKBC1002    166
MKBC0602    165
MKBC0601    164
MKBC1201    151
MKZA1502    143
MKBC1102    114
MKBC1101    100
MKBC0702     94
MKBC1001     94
MKBC0301     94
MKBC0402     93
MKBC0401     81
MKBC0701     58
MKTU2005     57
MKZA1402     55
MKZA1601     55
MKZA1802     55
MKZA1602     51
MKBC1301     45
MKZA1701     40
MKZA1702     37
MKTU2002     34
MKZA1801     33
MKTU2004     28
MKTU2001     27
MHPT2307     21
MKFX2101     18
MHPT2303     18
MKTU2006     16
MHPT2301     15
MHPT2302     14
MKFX2102     14
MHPT2304     13
MKTU2003     13
MHPT2305      9
MHPT2306      5
MAFT2201      2
MAFT2202      1
Name: count, dtype: int64

## ID = 03

In [ ]:
df_unplanned_03 = df_unplanned[df_unplanned['ID'] == '03']
df_unplanned_03

PRODUCTIONDATE_DAY_LOC   SHIFT_NAME LINE_NAME            CO_TYPE  \
168                2025-01-02  Afternoon-2  MAFT2201    Material_Handle   
191                2025-01-02  Afternoon-2  MHPT2301    Material_Handle   
198                2025-01-02  Afternoon-2  MHPT2302    Material_Handle   
210                2025-01-02  Afternoon-2  MHPT2303    Material_Handle   
218                2025-01-02  Afternoon-2  MHPT2304  Material_Filament   
...                       ...          ...       ...                ...   
167669             2025-06-30      Night-3  MHPT2304  Material_Filament   
167688             2025-06-30      Night-3  MHPT2306  Material_Filament   
167691             2025-06-30      Night-3  MHPT2307                NaN   
167867             2025-06-30      Night-3  MKTU2002    Material_Handle   
167889             2025-06-30      Night-3  MKTU2004    Material_Handle   

       CREW_ID AE_MODEL_CATEGORY             SIZE_TYPE SHIFT_NAME.1  \
168          A         Unplanned             Renew 360  Afternoon-2   
191          A         Unplanned     Deep Action White  Afternoon-2   
198          A         Unplanned     Deep Action White  Afternoon-2   
210          A         Unplanned  Total Action Model S  Afternoon-2   
218          A         Unplanned  Total Defense Shield  Afternoon-2   
...        ...               ...                   ...          ...   
167669       C         Unplanned  Total Defense Shield      Night-3   
167688       C         Unplanned  Total Defense Shield      Night-3   
167691       C         Unplanned  Total Defense Shield      Night-3   
167867       C         Unplanned        PureMint Fresh      Night-3   
167889       C         Unplanned    Total Action Green      Night-3   

                             UTIL_REASON_DESCRIPTION  DOWNTIME  ...  \
168        03-Change material - 0301-Change material         9  ...   
191        03-Change material - 0301-Change material        14  ...   
198        03-Change material - 0301-Change material        14  ...   
210        03-Change material - 0301-Change material        10  ...   
218        03-Change material - 0301-Change material         7  ...   
...                                              ...       ...  ...   
167669     03-Change material - 0301-Change material         5  ...   
167688     03-Change material - 0301-Change material        10  ...   
167691     03-Change material - 0301-Change material        10  ...   
167867  03-Material changing - 0301-Replace material         5  ...   
167889  03-Material changing - 0301-Replace material         5  ...   

        CLEANING_AND_SANITIZATION  BUSINESS_EXTERNAL_TIME  \
168                             0                       0   
191                             0                       0   
198                             0                       0   
210                             0                       0   
218                             0                       0   
...                           ...                     ...   
167669                          0                       0   
167688                          0                       0   
167691                          0                       0   
167867                          0                       0   
167889                          0                       0   

        PLANNED_MAINTENANCE  TOTAL_TIME  WAITING_TIME  PRODUCTION_ORDER_RATE  \
168                       0           9             0                  24.00   
191                       0          14             0                  48.00   
198                       0          14             0                  48.00   
210                       0          10             0                  66.70   
218                       0           7             0                  63.16   
...                     ...         ...           ...                    ...   
167669                    0           5             0                  63.16   
167688                    0

In [ ]:
df['IS_ERROR_3'] = 0
df.loc[df.index.isin(df_unplanned_03.index), 'IS_ERROR_3'] = 1

def chi_square_test_3(df, column):
    data = df[[column, 'IS_ERROR_3']].dropna()
    data[column] = data[column].astype('category')
    contingency_table = pd.crosstab(data[column], data['IS_ERROR_3'])
    if contingency_table.shape[0] < 2 or contingency_table.shape[1] < 2:
        print(f"\nKhông đủ dữ liệu để kiểm định với {column}")
        return
    chi2, p, dof, expected = chi2_contingency(contingency_table)
    V = cramers_v(contingency_table)
    print(f"\nYếu tố: {column}")
    print(f"  Chi-square = {chi2:.3f}")
    print(f"  p-value    = {p:.5f}")
    print(f"  Cramér's V = {V:.4f}")
    if p < 0.05:
        print("    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 03")
    else:
        print("    Kết luận: Không ảnh hưởng đáng kể")

for col in ['LINE_NAME', 'SIZE_TYPE', 'CREW_ID']:
    chi_square_test_3(df, col)



Yếu tố: LINE_NAME
  Chi-square = 13713.306
  p-value    = 0.00000
  Cramér's V = 0.2858
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 03

Yếu tố: SIZE_TYPE
  Chi-square = 4457.859
  p-value    = 0.00000
  Cramér's V = 0.2061
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 03

Yếu tố: CREW_ID
  Chi-square = 45.910
  p-value    = 0.00000
  Cramér's V = 0.0165
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 03


Cả LINE_NAME, SIZE_TYPE, và CREW_ID đều có ảnh hưởng đáng kể tới lỗi ID = 03 (p-value = 0.00000).

Tuy nhiên, mức độ ảnh hưởng khác nhau rõ rệt dựa trên Cramér’s V:

- LINE_NAME là yếu tố ảnh hưởng mạnh nhất (V = 0.2858) → Đây là yếu tố chính cần tập trung.

- SIZE_TYPE có ảnh hưởng nhưng yếu hơn (V = 0.2061).

- CREW_ID ảnh hưởng rất nhỏ, gần như không đáng kể (V = 0.0165)

In [ ]:
df_unplanned_03["LINE_NAME"].value_counts()

LINE_NAME
MHPT2303    471
MHPT2302    440
MHPT2301    431
MHPT2304    426
MHPT2307    419
MHPT2305    406
MHPT2306    401
MAFT2201    106
MAFT2204     87
MAFT2205     77
MKTU2002     75
MAFT2203     73
MKZA1501     63
MKZA1502     62
MAFT2202     59
MKTU2001     45
MKFX2102     29
MKFX2101     28
MKTU2006     23
MKTU2004     22
MKTU2003     16
MKZA1702      9
MKZA1602      9
MKZA1701      9
MKTU2005      9
MKZA1601      6
MKBC1301      4
MKZA1401      4
MKBC0902      3
MKBC0302      3
MKBC0201      2
MKBC1002      2
MKBC0901      2
MKBC1001      2
MKBC0301      1
MKBC0101      1
MKBC0202      1
MKBC0701      1
MKBC0702      1
MKZA1801      1
MKBC1202      1
Name: count, dtype: int64

## ID = 14

In [ ]:
df_unplanned_14 = df_unplanned[df_unplanned['ID'] == '14']
df_unplanned_14

PRODUCTIONDATE_DAY_LOC   SHIFT_NAME LINE_NAME            CO_TYPE  \
167                2025-01-02  Afternoon-2  MAFT2201    Material_Handle   
177                2025-01-02  Afternoon-2  MAFT2202  Material_Filament   
184                2025-01-02  Afternoon-2  MAFT2203    Material_Handle   
263                2025-01-02  Afternoon-2  MKBC0201    Material_Handle   
286                2025-01-02  Afternoon-2  MKBC0301  Material_Filament   
...                       ...          ...       ...                ...   
167816             2025-06-30      Night-3  MKBC1002  Material_Filament   
167856             2025-06-30      Night-3  MKTU2001    Material_Handle   
167866             2025-06-30      Night-3  MKTU2002    Material_Handle   
167885             2025-06-30      Night-3  MKTU2004    Material_Handle   
167898             2025-06-30      Night-3  MKTU2006    Material_Handle   

       CREW_ID AE_MODEL_CATEGORY             SIZE_TYPE SHIFT_NAME.1  \
167          A         Unplanned             Renew 360  Afternoon-2   
177          A         Unplanned             Renew 360  Afternoon-2   
184          A         Unplanned             Renew 360  Afternoon-2   
263          A         Unplanned         EcoFresh Plus  Afternoon-2   
286          A         Unplanned  Total Defense Shield  Afternoon-2   
...        ...               ...                   ...          ...   
167816       C         Unplanned     Classic Clean 100      Night-3   
167856       C         Unplanned        PureMint Fresh      Night-3   
167866       C         Unplanned        PureMint Fresh      Night-3   
167885       C         Unplanned    Total Action Green      Night-3   
167898       C         Unplanned      GreenClean Ultra      Night-3   

                                  UTIL_REASON_DESCRIPTION  DOWNTIME  ...  \
167               14-Fusing - 1401-Mechanical adjustment.        18  ...   
177               14-Fusing - 1401-Mechanical adjustment.        27  ...   
184               14-Fusing - 1401-Mechanical adjustment.        15  ...   
263           14-Robot infeed - 1402-Adjust robot postion        15  ...   
286     14-Fiber picker  T1-1401-Adjust gap of fiber p...        30  ...   
...                                                   ...       ...  ...   
167816  14-Fiber picker  T2-1401-Adjust gap of fiber p...        15  ...   
167856  14-Fiber picker   - 1401-Adjust gap of fiber p...        28  ...   
167866  14-Fiber picker   - 1401-Adjust gap of fiber p...        10  ...   
167885  14-Fiber picker   - 1401-Adjust gap of fiber p...        14  ...   
167898  14-Fiber picker   - 1401-Adjust gap of fiber p...        15  ...   

        CLEANING_AND_SANITIZATION  BUSINESS_EXTERNAL_TIME  \
167                             0                       0   
177                             0                       0   
184                             0                       0   
263                             0                       0   
286                             0                       0   
...                           ...                     ...   
167816                          0                       0   
167856                          0                       0   
167866                          0                       0   
167885                          0                       0   
167898                          0                       0   

        PLANNED_MAINTENANCE  TOTAL_TIME  WAITING_TIME  PRODUCTION_ORDER_RATE  \
167                       0          18             0                  24.00   
177                       0          27             0                  24.00   
184                       0          15             0                  24.00   
263                       0          15             0                  85.70   
286                       0          30             0                  78.90   
...                     ...         ...           ...                    ...   
167816                    0          15        

In [ ]:
df['IS_ERROR_14'] = 0
df.loc[df.index.isin(df_unplanned_14.index), 'IS_ERROR_14'] = 1

def chi_square_test_14(df, column):
    data = df[[column, 'IS_ERROR_14']].dropna()
    data[column] = data[column].astype('category')
    contingency_table = pd.crosstab(data[column], data['IS_ERROR_14'])
    if contingency_table.shape[0] < 2 or contingency_table.shape[1] < 2:
        print(f"\nKhông đủ dữ liệu để kiểm định với {column}")
        return
    chi2, p, dof, expected = chi2_contingency(contingency_table)
    V = cramers_v(contingency_table)
    print(f"\nYếu tố: {column}")
    print(f"  Chi-square = {chi2:.3f}")
    print(f"  p-value    = {p:.5f}")
    print(f"  Cramér's V = {V:.4f}")
    if p < 0.05:
        print("    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 14")
    else:
        print("    Kết luận: Không ảnh hưởng đáng kể")

for col in ['LINE_NAME', 'SIZE_TYPE', 'CREW_ID']:
    chi_square_test_14(df, col)



Yếu tố: LINE_NAME
  Chi-square = 2692.121
  p-value    = 0.00000
  Cramér's V = 0.1266
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 14

Yếu tố: SIZE_TYPE
  Chi-square = 2660.773
  p-value    = 0.00000
  Cramér's V = 0.1592
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 14

Yếu tố: CREW_ID
  Chi-square = 4.952
  p-value    = 0.08407
  Cramér's V = 0.0054
    Kết luận: Không ảnh hưởng đáng kể


Dựa trên kiểm định Chi-square kết hợp với hệ số Cramér’s V:

- SIZE_TYPE là yếu tố ảnh hưởng mạnh nhất đến lỗi ID = 14.

- LINE_NAME cũng có ảnh hưởng, nhưng yếu hơn SIZE_TYPE.

- CREW_ID không phải là yếu tố gây lỗi đáng kể (p-value > 0.05, mức ảnh hưởng gần như bằng 0).

In [ ]:
df_unplanned_14["SIZE_TYPE"].value_counts()

SIZE_TYPE
Renew 360                       675
Classic Clean 100               538
Total Defense Shield            375
GreenClean Pro                  253
EcoFresh Plus                   225
PureMint Fresh                  198
Deep Action White               187
Total Action Green              155
Super Soft Tech                 126
Total Action Model S            124
Pro-Clean 5000                  118
Oral Care 360                   105
Advanced Hydro-Clean             89
Defense Action Pro               82
Junior Sparkle (Ages 2+)         82
Zenith Active                    67
Classic White 110                60
Zenith GreenClean                58
Kids FunBrush (Tandy)            56
Pro-Shield Complete              48
Super Soft Pro                   41
EcoFresh Green                   32
Ocean Explorer (Ages 6+)         30
ActiveClean Guard                21
Junior Guard Taper (Ages 5+)     16
Precision Grip 2.0               15
EcoSoft Classic                  15
GreenClean Classic               12
Safari Explorer (Ages 6+)         7
Zenith Classic Clean              6
ActiveClean Model X               5
GreenClean Ultra                  1
Name: count, dtype: int64

## ID = 06

In [ ]:
df_unplanned_06 = df_unplanned[df_unplanned['ID'] == '06']
df_unplanned_06

PRODUCTIONDATE_DAY_LOC   SHIFT_NAME LINE_NAME            CO_TYPE  \
164                2025-01-02  Afternoon-2  MAFT2201    Material_Handle   
171                2025-01-02  Afternoon-2  MAFT2202  Material_Filament   
179                2025-01-02  Afternoon-2  MAFT2203    Material_Handle   
214                2025-01-02  Afternoon-2  MHPT2304  Material_Filament   
219                2025-01-02  Afternoon-2  MHPT2305  Material_Filament   
...                       ...          ...       ...                ...   
167761             2025-06-30      Night-3  MKBC0502    Material_Handle   
167821             2025-06-30      Night-3  MKBC1101  Material_Filament   
167849             2025-06-30      Night-3  MKFX2102  Material_Filament   
167865             2025-06-30      Night-3  MKTU2002    Material_Handle   
167932             2025-06-30      Night-3  MKZA1502    Material_Handle   

       CREW_ID AE_MODEL_CATEGORY             SIZE_TYPE SHIFT_NAME.1  \
164          A         Unplanned             Renew 360  Afternoon-2   
171          A         Unplanned             Renew 360  Afternoon-2   
179          A         Unplanned             Renew 360  Afternoon-2   
214          A         Unplanned  Total Defense Shield  Afternoon-2   
219          A         Unplanned     Classic Clean 100  Afternoon-2   
...        ...               ...                   ...          ...   
167761       C         Unplanned  Total Action Model S      Night-3   
167821       C         Unplanned     Classic Clean 100      Night-3   
167849       C         Unplanned     Classic Clean 100      Night-3   
167865       C         Unplanned        PureMint Fresh      Night-3   
167932       C         Unplanned        Super Soft Pro      Night-3   

                                  UTIL_REASON_DESCRIPTION  DOWNTIME  ...  \
164            06-Fiber box - 0601-Mechanical adjustment.        10  ...   
171            06-Fiber box - 0601-Mechanical adjustment.        12  ...   
179            06-Fiber box - 0601-Mechanical adjustment.        13  ...   
214                  06-Fiber box - 0602-Adjust sparepart        16  ...   
219                  06-Fiber box - 0602-Adjust sparepart        30  ...   
...                                                   ...       ...  ...   
167761  06-Fiber boxT1-0602-Replace/adjust mechanical ...        10  ...   
167821  06-Fiber boxT1-0602-Replace/adjust mechanical ...        10  ...   
167849               06-Fiber box - 0601-Sparepart broken        45  ...   
167865  06-Fiber box - 0602-Replace/adjust mechanical ...        15  ...   
167932  06-Fiber boxT2-0602-Replace/adjust mechanical ...        10  ...   

        CLEANING_AND_SANITIZATION  BUSINESS_EXTERNAL_TIME  \
164                             0                       0   
171                             0                       0   
179                             0                       0   
214                             0                       0   
219                             0                       0   
...                           ...                     ...   
167761                          0                       0   
167821                          0                       0   
167849                          0                       0   
167865                          0                       0   
167932                          0                       0   

        PLANNED_MAINTENANCE  TOTAL_TIME  WAITING_TIME  PRODUCTION_ORDER_RATE  \
164                       0          10             0                  24.00   
171                       0          12             0                  24.00   
179                       0          13             0                  24.00   
214                       0          16             0                  63.16   
219                       0          30             0                  63.20   
...                     ...         ...           ...                    ...   
167761                    0          10        

In [ ]:
df['IS_ERROR_06'] = 0
df.loc[df.index.isin(df_unplanned_06.index), 'IS_ERROR_06'] = 1

def chi_square_test_06(df, column):
    data = df[[column, 'IS_ERROR_06']].dropna()
    data[column] = data[column].astype('category')
    contingency_table = pd.crosstab(data[column], data['IS_ERROR_06'])
    if contingency_table.shape[0] < 2 or contingency_table.shape[1] < 2:
        print(f"\nKhông đủ dữ liệu để kiểm định với {column}")
        return
    chi2, p, dof, expected = chi2_contingency(contingency_table)
    V = cramers_v(contingency_table)
    print(f"\nYếu tố: {column}")
    print(f"  Chi-square = {chi2:.3f}")
    print(f"  p-value    = {p:.5f}")
    print(f"  Cramér's V = {V:.4f}")
    if p < 0.05:
        print("    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 06")
    else:
        print("    Kết luận: Không ảnh hưởng đáng kể")

for col in ['LINE_NAME', 'SIZE_TYPE', 'CREW_ID']:
    chi_square_test_06(df, col)



Yếu tố: LINE_NAME
  Chi-square = 4768.883
  p-value    = 0.00000
  Cramér's V = 0.1685
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 06

Yếu tố: SIZE_TYPE
  Chi-square = 1880.896
  p-value    = 0.00000
  Cramér's V = 0.1339
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 06

Yếu tố: CREW_ID
  Chi-square = 17.133
  p-value    = 0.00019
  Cramér's V = 0.0101
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 06


Cả LINE_NAME, SIZE_TYPE, và CREW_ID đều có ảnh hưởng đáng kể tới lỗi ID = 06

Tuy nhiên, mức độ ảnh hưởng khác nhau rõ rệt dựa trên Cramér’s V:

- LINE_NAME là yếu tố ảnh hưởng mạnh nhất (V = 0.1685) → Đây là yếu tố chính cần tập trung.

- SIZE_TYPE có ảnh hưởng nhưng yếu hơn (V = 0.1339).

- CREW_ID ảnh hưởng rất nhỏ, gần như không đáng kể (V = 0.0101)

In [ ]:
df_unplanned_06["LINE_NAME"].value_counts()

LINE_NAME
MHPT2304    331
MHPT2307    297
MHPT2305    293
MHPT2301    282
MHPT2302    213
MHPT2306    209
MHPT2303    191
MKTU2001    160
MKTU2004    150
MKTU2005    119
MKBC1301    117
MKFX2101     98
MKTU2002     97
MKBC1002     90
MKFX2102     81
MKZA1502     72
MKTU2006     71
MKBC0502     70
MKBC0902     69
MKBC0501     68
MKBC1001     68
MKBC1101     64
MKZA1501     59
MKTU2003     51
MKBC0901     50
MKZA1401     46
MKBC1102     31
MAFT2202     30
MAFT2203     29
MKBC0702     28
MKBC0202     27
MAFT2201     26
MKBC1201     25
MKBC0701     25
MKBC0201     23
MAFT2205     22
MKBC1202     22
MAFT2204     18
MKBC0601     17
MKBC0602     14
MKBC0402      9
MKBC0102      7
MKZA1802      5
MKBC0302      4
MKBC0101      4
MKBC0401      4
MKZA1702      4
MKZA1601      4
MKBC0301      4
MKZA1801      3
MKZA1701      3
MKZA1602      3
MKZA1402      2
Name: count, dtype: int64

## ID = 18

In [ ]:
df_unplanned_18 = df_unplanned[df_unplanned['ID'] == '18']
df_unplanned_18

PRODUCTIONDATE_DAY_LOC   SHIFT_NAME LINE_NAME            CO_TYPE  \
192                2025-01-02  Afternoon-2  MHPT2301    Material_Handle   
208                2025-01-02  Afternoon-2  MHPT2303    Material_Handle   
213                2025-01-02  Afternoon-2  MHPT2304  Material_Filament   
224                2025-01-02  Afternoon-2  MHPT2305  Material_Filament   
226                2025-01-02  Afternoon-2  MHPT2306  Material_Filament   
...                       ...          ...       ...                ...   
167653             2025-06-30      Night-3  MHPT2302    Material_Handle   
167655             2025-06-30      Night-3  MHPT2303    Material_Handle   
167668             2025-06-30      Night-3  MHPT2304  Material_Filament   
167697             2025-06-30      Night-3  MHPT2307                NaN   
167850             2025-06-30      Night-3  MKFX2102  Material_Filament   

       CREW_ID AE_MODEL_CATEGORY             SIZE_TYPE SHIFT_NAME.1  \
192          A         Unplanned     Deep Action White  Afternoon-2   
208          A         Unplanned  Total Action Model S  Afternoon-2   
213          A         Unplanned  Total Defense Shield  Afternoon-2   
224          A         Unplanned     Classic Clean 100  Afternoon-2   
226          A         Unplanned  Total Defense Shield  Afternoon-2   
...        ...               ...                   ...          ...   
167653       C         Unplanned     Deep Action White      Night-3   
167655       C         Unplanned  Total Action Model S      Night-3   
167668       C         Unplanned  Total Defense Shield      Night-3   
167697       C         Unplanned  Total Defense Shield      Night-3   
167850       C         Unplanned     Classic Clean 100      Night-3   

                           UTIL_REASON_DESCRIPTION  DOWNTIME  ...  \
192     18-Autofeeder - 1802-Stuck handle on chain        10  ...   
208     18-Autofeeder - 1802-Stuck handle on chain        17  ...   
213     18-Autofeeder - 1802-Stuck handle on chain        30  ...   
224     18-Autofeeder - 1801-Double hadle on chain        24  ...   
226     18-Autofeeder - 1802-Stuck handle on chain         3  ...   
...                                            ...       ...  ...   
167653  18-Autofeeder - 1802-Stuck handle on chain        14  ...   
167655  18-Autofeeder - 1802-Stuck handle on chain        10  ...   
167668  18-Autofeeder - 1802-Stuck handle on chain         5  ...   
167697  18-Autofeeder - 1802-Stuck handle on chain         8  ...   
167850  18-Autofeeder - 1802-Stuck handle on chain        10  ...   

        CLEANING_AND_SANITIZATION  BUSINESS_EXTERNAL_TIME  \
192                             0                       0   
208                             0                       0   
213                             0                       0   
224                             0                       0   
226                             0                       0   
...                           ...                     ...   
167653                          0                       0   
167655                          0                       0   
167668                          0                       0   
167697                          0                       0   
167850                          0                       0   

        PLANNED_MAINTENANCE  TOTAL_TIME  WAITING_TIME  PRODUCTION_ORDER_RATE  \
192                       0          10             0                  48.00   
208                       0          17             0                  66.70   
213                       0          30             0                  63.16   
224                       0          24             0                  63.20   
226                       0           3             0                  63.16   
...                     ...         ...           ...                    ...   
167653                    0          14             0                  48.00   
167655                    0          10            

In [ ]:
df['IS_ERROR_18'] = 0
df.loc[df.index.isin(df_unplanned_18.index), 'IS_ERROR_18'] = 1

def chi_square_test_18(df, column):
    data = df[[column, 'IS_ERROR_18']].dropna()
    data[column] = data[column].astype('category')
    contingency_table = pd.crosstab(data[column], data['IS_ERROR_18'])
    if contingency_table.shape[0] < 2 or contingency_table.shape[1] < 2:
        print(f"\nKhông đủ dữ liệu để kiểm định với {column}")
        return
    chi2, p, dof, expected = chi2_contingency(contingency_table)
    V = cramers_v(contingency_table)
    print(f"\nYếu tố: {column}")
    print(f"  Chi-square = {chi2:.3f}")
    print(f"  p-value    = {p:.5f}")
    print(f"  Cramér's V = {V:.4f}")
    if p < 0.05:
        print("    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 18")
    else:
        print("    Kết luận: Không ảnh hưởng đáng kể")

for col in ['LINE_NAME', 'SIZE_TYPE', 'CREW_ID']:
    chi_square_test_18(df, col)



Yếu tố: LINE_NAME
  Chi-square = 12703.771
  p-value    = 0.00000
  Cramér's V = 0.2750
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 18

Yếu tố: SIZE_TYPE
  Chi-square = 3616.569
  p-value    = 0.00000
  Cramér's V = 0.1856
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 18

Yếu tố: CREW_ID
  Chi-square = 19.177
  p-value    = 0.00007
  Cramér's V = 0.0107
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 18


Cả LINE_NAME, SIZE_TYPE, và CREW_ID đều có ảnh hưởng đáng kể tới lỗi ID = 18

Tuy nhiên, mức độ ảnh hưởng khác nhau rõ rệt dựa trên Cramér’s V:

- LINE_NAME là yếu tố ảnh hưởng mạnh nhất (V = 0.2750) → Đây là yếu tố chính cần tập trung.

- SIZE_TYPE có ảnh hưởng nhưng yếu hơn (V = 0.1856).

- CREW_ID ảnh hưởng rất nhỏ, gần như không đáng kể (V = 0.0107)

In [ ]:
df_unplanned_18["LINE_NAME"].value_counts()

LINE_NAME
MHPT2307    478
MHPT2303    441
MHPT2305    433
MHPT2301    398
MHPT2302    339
MHPT2304    337
MHPT2306    238
MKFX2101    202
MKFX2102    113
MKBC0502     36
MKTU2003     32
MAFT2203     30
MKBC1301     28
MAFT2201     23
MKTU2005     21
MAFT2204     18
MKBC0901     16
MKTU2004     16
MAFT2205     14
MAFT2202     14
MKBC0501     13
MKZA1501     12
MKBC0101     11
MKBC0701     11
MKTU2001     10
MKBC0601      9
MKBC0702      9
MKZA1502      8
MKBC1101      8
MKTU2002      7
MKBC0902      6
MKBC0102      6
MKZA1401      6
MKBC0401      6
MKZA1601      5
MKBC1102      4
MKTU2006      4
MKBC1202      3
MKZA1602      3
MKBC0301      3
MKBC1201      3
MKBC0202      3
MKBC1002      2
MKBC0302      2
MKBC0402      2
MKBC0201      2
MKZA1701      1
MKZA1801      1
MKBC0602      1
MKZA1402      1
MKZA1702      1
MKBC1001      1
Name: count, dtype: int64

## ID = 02

In [ ]:
df_unplanned_02 = df_unplanned[df_unplanned['ID'] == '02']
df_unplanned_02

PRODUCTIONDATE_DAY_LOC   SHIFT_NAME LINE_NAME            CO_TYPE  \
186                2025-01-02  Afternoon-2  MAFT2203    Material_Handle   
281                2025-01-02  Afternoon-2  MKBC0301  Material_Filament   
433                2025-01-02  Afternoon-2  MKBC1301    Material_Handle   
456                2025-01-02  Afternoon-2  MKTU2002    Material_Handle   
486                2025-01-02  Afternoon-2  MKTU2006    Material_Handle   
...                       ...          ...       ...                ...   
167262             2025-06-30  Afternoon-2  MKTU2005    Bundle_Material   
167273             2025-06-30  Afternoon-2  MKTU2006    Material_Handle   
167554             2025-06-30        Day-1  MKTU2002    Material_Handle   
167593             2025-06-30        Day-1  MKZA1501  Material_Filament   
167610             2025-06-30        Day-1  MKZA1502    Material_Handle   

       CREW_ID AE_MODEL_CATEGORY             SIZE_TYPE SHIFT_NAME.1  \
186          A         Unplanned             Renew 360  Afternoon-2   
281          A         Unplanned  Total Defense Shield  Afternoon-2   
433          A         Unplanned  Advanced Hydro-Clean  Afternoon-2   
456          A         Unplanned        PureMint Fresh  Afternoon-2   
486          A         Unplanned    Total Action Green  Afternoon-2   
...        ...               ...                   ...          ...   
167262       B         Unplanned      GreenClean Ultra  Afternoon-2   
167273       B         Unplanned      GreenClean Ultra  Afternoon-2   
167554       A         Unplanned        PureMint Fresh        Day-1   
167593       A         Unplanned        Super Soft Pro        Day-1   
167610       A         Unplanned        Super Soft Pro        Day-1   

         UTIL_REASON_DESCRIPTION  DOWNTIME  ...  CLEANING_AND_SANITIZATION  \
186     02-Quality - 0202-Rework       105  ...                          0   
281     02-Quality - 0202-Rework        30  ...                          0   
433     02-Quality - 0202-Rework        28  ...                          0   
456     02-Quality - 0202-Rework        29  ...                          0   
486     02-Quality - 0202-Rework        17  ...                          0   
...                          ...       ...  ...                        ...   
167262  02-Quality - 0202-Rework        32  ...                          0   
167273  02-Quality - 0202-Rework        30  ...                          0   
167554  02-Quality - 0202-Rework        20  ...                          0   
167593  02-Quality - 0202-Rework        20  ...                          0   
167610  02-Quality - 0202-Rework        25  ...                          0   

        BUSINESS_EXTERNAL_TIME  PLANNED_MAINTENANCE  TOTAL_TIME  WAITING_TIME  \
186                          0                    0         105             0   
281                          0                    0          30             0   
433                          0                    0          28             0   
456                          0                    0          29             0   
486                          0                    0          17             0   
...                        ...                  ...         ...           ...   
167262                       0                    0          32             0   
167273                       0                    0          30             0   
167554                       0                    0          20             0   
167593                       0                    0          20             0   
167610                       0                    0          25             0   

        PRODUCTION_ORDER_RATE  ID  Machine_Name  Error_Code  Error_Decrisption  
186                     24.00  02      Quality         0202             Rework  
281                     78.90  02      Quality         0202             Rework  
433                     25.00  02      Quality         0202             Rework  
456                

In [ ]:
df['IS_ERROR_02'] = 0
df.loc[df.index.isin(df_unplanned_02.index), 'IS_ERROR_02'] = 1

def chi_square_test_02(df, column):
    data = df[[column, 'IS_ERROR_02']].dropna()
    data[column] = data[column].astype('category')
    contingency_table = pd.crosstab(data[column], data['IS_ERROR_02'])
    if contingency_table.shape[0] < 2 or contingency_table.shape[1] < 2:
        print(f"\nKhông đủ dữ liệu để kiểm định với {column}")
        return
    chi2, p, dof, expected = chi2_contingency(contingency_table)
    V = cramers_v(contingency_table)
    print(f"\nYếu tố: {column}")
    print(f"  Chi-square = {chi2:.3f}")
    print(f"  p-value    = {p:.5f}")
    print(f"  Cramér's V = {V:.4f}")
    if p < 0.05:
        print("    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 02")
    else:
        print("    Kết luận: Không ảnh hưởng đáng kể")

for col in ['LINE_NAME', 'SIZE_TYPE', 'CREW_ID']:
    chi_square_test_02(df, col)



Yếu tố: LINE_NAME
  Chi-square = 5158.153
  p-value    = 0.00000
  Cramér's V = 0.1753
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 02

Yếu tố: SIZE_TYPE
  Chi-square = 3253.506
  p-value    = 0.00000
  Cramér's V = 0.1761
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 02

Yếu tố: CREW_ID
  Chi-square = 42.601
  p-value    = 0.00000
  Cramér's V = 0.0159
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 02


Cả LINE_NAME, SIZE_TYPE, và CREW_ID đều có ảnh hưởng đáng kể tới lỗi ID = 02

Tuy nhiên, mức độ ảnh hưởng khác nhau rõ rệt dựa trên Cramér’s V:

- SIZE_TYPE là yếu tố ảnh hưởng mạnh nhất (V = 0.1761) → Đây là yếu tố chính cần tập trung.

- LINE_NAME có ảnh hưởng nhưng yếu hơn (V = 0.1753).

- CREW_ID ảnh hưởng rất nhỏ, gần như không đáng kể (V = 0.0159)

In [ ]:
df_unplanned_02["SIZE_TYPE"].value_counts()

SIZE_TYPE
Total Action Model S            416
Deep Action White               331
GreenClean Pro                  326
Super Soft Tech                 322
Classic Clean 100               209
ActiveClean Guard               195
Precision Grip 2.0              190
PureMint Fresh                  185
ActiveClean Model X             185
Pro-Clean 5000                  183
Renew 360                       141
Total Action Green              103
Super Soft Pro                   76
GreenClean Classic               72
EcoFresh Plus                    64
Junior Sparkle (Ages 2+)         47
Advanced Hydro-Clean             41
Zenith GreenClean                41
Total Defense Shield             41
Kids FunBrush (Tandy)            38
EcoFresh Green                   23
Pro-Shield Complete              19
Classic White 110                19
Junior Guard Taper (Ages 5+)     16
Zenith Active                    16
Ocean Explorer (Ages 6+)          9
Defense Action Pro                8
EcoSoft Classic                   7
Oral Care 360                     6
Safari Explorer (Ages 6+)         3
GreenClean Ultra                  2
Zenith Classic Clean              1
Name: count, dtype: int64

## ID = 12

In [ ]:
df_unplanned_12 = df_unplanned[df_unplanned['ID'] == '12']
df_unplanned_12

PRODUCTIONDATE_DAY_LOC   SHIFT_NAME LINE_NAME            CO_TYPE  \
160                2025-01-02  Afternoon-2  MAFT2201    Material_Handle   
174                2025-01-02  Afternoon-2  MAFT2202  Material_Filament   
183                2025-01-02  Afternoon-2  MAFT2203    Material_Handle   
195                2025-01-02  Afternoon-2  MHPT2301    Material_Handle   
201                2025-01-02  Afternoon-2  MHPT2302    Material_Handle   
...                       ...          ...       ...                ...   
167650             2025-06-30      Night-3  MHPT2302    Material_Handle   
167660             2025-06-30      Night-3  MHPT2303    Material_Handle   
167681             2025-06-30      Night-3  MHPT2305    Bundle_Material   
167780             2025-06-30      Night-3  MKBC0701    Material_Handle   
167872             2025-06-30      Night-3  MKTU2002    Material_Handle   

       CREW_ID AE_MODEL_CATEGORY                 SIZE_TYPE SHIFT_NAME.1  \
160          A         Unplanned                 Renew 360  Afternoon-2   
174          A         Unplanned                 Renew 360  Afternoon-2   
183          A         Unplanned                 Renew 360  Afternoon-2   
195          A         Unplanned         Deep Action White  Afternoon-2   
201          A         Unplanned         Deep Action White  Afternoon-2   
...        ...               ...                       ...          ...   
167650       C         Unplanned         Deep Action White      Night-3   
167660       C         Unplanned      Total Action Model S      Night-3   
167681       C         Unplanned      Total Defense Shield      Night-3   
167780       C         Unplanned  Junior Sparkle (Ages 2+)      Night-3   
167872       C         Unplanned            PureMint Fresh      Night-3   

                                  UTIL_REASON_DESCRIPTION  DOWNTIME  ...  \
160         12-Filling tool - 1201-Mechanical adjustment.        17  ...   
174         12-Filling tool - 1201-Mechanical adjustment.        53  ...   
183         12-Filling tool - 1201-Mechanical adjustment.        59  ...   
195                   12-Filling tool - 1201-Cleaning Jaw        15  ...   
201                   12-Filling tool - 1201-Cleaning Jaw        18  ...   
...                                                   ...       ...  ...   
167650           12-Filling tool - 1204-Replace sparepart        30  ...   
167660               12-Filling tool - 1203-Adjust cutter        40  ...   
167681                12-Filling tool - 1201-Cleaning Jaw         5  ...   
167780  12-Dust collector - 1201-Replace details of du...         5  ...   
167872    12-Turret - 1201-Replace/adjust parts of turret        20  ...   

        CLEANING_AND_SANITIZATION  BUSINESS_EXTERNAL_TIME  \
160                             0                       0   
174                             0                       0   
183                             0                       0   
195                             0                       0   
201                             0                       0   
...                           ...                     ...   
167650                          0                       0   
167660                          0                       0   
167681                          0                       0   
167780                          0                       0   
167872                          0                       0   

        PLANNED_MAINTENANCE  TOTAL_TIME  WAITING_TIME  PRODUCTION_ORDER_RATE  \
160                       0          17             0                  24.00   
174                       0          53             0                  24.00   
183                       0          59             0                  24.00   
195                       0          15             0                  48.00   
201                       0          18             0                  48.00   
...                     ...         ...           ...                    ...   

In [ ]:
df['IS_ERROR_12'] = 0
df.loc[df.index.isin(df_unplanned_12.index), 'IS_ERROR_12'] = 1

def chi_square_test_12(df, column):
    data = df[[column, 'IS_ERROR_12']].dropna()
    data[column] = data[column].astype('category')
    contingency_table = pd.crosstab(data[column], data['IS_ERROR_12'])
    if contingency_table.shape[0] < 2 or contingency_table.shape[1] < 2:
        print(f"\nKhông đủ dữ liệu để kiểm định với {column}")
        return
    chi2, p, dof, expected = chi2_contingency(contingency_table)
    V = cramers_v(contingency_table)
    print(f"\nYếu tố: {column}")
    print(f"  Chi-square = {chi2:.3f}")
    print(f"  p-value    = {p:.5f}")
    print(f"  Cramér's V = {V:.4f}")
    if p < 0.05:
        print("    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 12")
    else:
        print("    Kết luận: Không ảnh hưởng đáng kể")

for col in ['LINE_NAME', 'SIZE_TYPE', 'CREW_ID']:
    chi_square_test_12(df, col)



Yếu tố: LINE_NAME
  Chi-square = 4420.846
  p-value    = 0.00000
  Cramér's V = 0.1622
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 12

Yếu tố: SIZE_TYPE
  Chi-square = 3991.762
  p-value    = 0.00000
  Cramér's V = 0.1950
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 12

Yếu tố: CREW_ID
  Chi-square = 2.600
  p-value    = 0.27259
  Cramér's V = 0.0039
    Kết luận: Không ảnh hưởng đáng kể


LINE_NAME, SIZE_TYPE đều có ảnh hưởng tới lỗi ID = 12, tuy nhiên CREW_ID lại không có ảnh hưởng đáng kể đến lỗi ID này

Mức độ ảnh hưởng khác nhau rõ rệt dựa trên Cramér’s V:

- SIZE_TYPE là yếu tố ảnh hưởng mạnh nhất (V = 0.1950) → Đây là yếu tố chính cần tập trung.

- LINE_NAME có ảnh hưởng nhưng yếu hơn (V = 0.1622).

- CREW_ID không ảnh hưởng đánh kể (V = 0.0039)

In [ ]:
df_unplanned_12["SIZE_TYPE"].value_counts()

SIZE_TYPE
Renew 360                    723
Deep Action White            567
Total Defense Shield         399
Classic Clean 100            271
Super Soft Tech              220
Total Action Model S         170
Oral Care 360                117
Super Soft Pro               100
ActiveClean Guard             88
EcoFresh Plus                 86
PureMint Fresh                58
Pro-Clean 5000                53
GreenClean Pro                45
Precision Grip 2.0            33
Zenith Active                 30
Defense Action Pro            23
Junior Sparkle (Ages 2+)      21
Classic White 110             18
Total Action Green            17
Pro-Shield Complete           17
Kids FunBrush (Tandy)         16
ActiveClean Model X           15
Advanced Hydro-Clean          13
GreenClean Classic            10
Zenith GreenClean             10
Ocean Explorer (Ages 6+)       7
EcoFresh Green                 5
Zenith Classic Clean           3
EcoSoft Classic                2
Safari Explorer (Ages 6+)      1
Name: count, dtype: int64

## ID = 16

In [ ]:
df_unplanned_16 = df_unplanned[df_unplanned['ID'] == '16']
df_unplanned_16

PRODUCTIONDATE_DAY_LOC   SHIFT_NAME LINE_NAME            CO_TYPE  \
496                2025-01-02  Afternoon-2  MKZA1401    Bundle_Material   
516                2025-01-02  Afternoon-2  MKZA1802    Material_Handle   
699                2025-01-02        Day-1  MKBC0601  Material_Filament   
1186               2025-01-02      Night-3  MKZA1401  Material_Filament   
1201               2025-01-02      Night-3  MKZA1801    Material_Handle   
...                       ...          ...       ...                ...   
167599             2025-06-30        Day-1  MKZA1501  Material_Filament   
167604             2025-06-30        Day-1  MKZA1502    Material_Handle   
167612             2025-06-30        Day-1  MKZA1502    Material_Handle   
167613             2025-06-30        Day-1  MKZA1502    Material_Handle   
167916             2025-06-30      Night-3  MKZA1501  Material_Filament   

       CREW_ID AE_MODEL_CATEGORY             SIZE_TYPE SHIFT_NAME.1  \
496          A         Unplanned       Super Soft Tech  Afternoon-2   
516          A         Unplanned  Total Action Model S  Afternoon-2   
699          C         Unplanned  Total Defense Shield        Day-1   
1186         B         Unplanned     ActiveClean Guard      Night-3   
1201         B         Unplanned  Total Action Model S      Night-3   
...        ...               ...                   ...          ...   
167599       A         Unplanned        Super Soft Pro        Day-1   
167604       A         Unplanned        Super Soft Pro        Day-1   
167612       A         Unplanned        Super Soft Pro        Day-1   
167613       A         Unplanned        Super Soft Pro        Day-1   
167916       C         Unplanned        Super Soft Pro      Night-3   

                                  UTIL_REASON_DESCRIPTION  DOWNTIME  ...  \
496            16-Autosorter - 1601-Handle on chain stuck        15  ...   
516            16-Autosorter - 1601-Handle on chain stuck        15  ...   
699               16-CoordinationT3-1604-Adjust parameter        14  ...   
1186           16-Autosorter - 1601-Handle on chain stuck         4  ...   
1201         16-Autosorter - 1602-Handle sort robot stuck        30  ...   
...                                                   ...       ...  ...   
167599             16-Autosorter - 1605-handle sort stuck        12  ...   
167604  16-Autosorter - 1614-Conveyor position adjustment         7  ...   
167612       16-Autosorter - 1602-Handle sort robot stuck        10  ...   
167613         16-Autosorter - 1601-Handle on chain stuck         7  ...   
167916         16-Autosorter - 1601-Handle on chain stuck         5  ...   

        CLEANING_AND_SANITIZATION  BUSINESS_EXTERNAL_TIME  \
496                             0                       0   
516                             0                       0   
699                             0                       0   
1186                            0                       0   
1201                            0                       0   
...                           ...                     ...   
167599                          0                       0   
167604                          0                       0   
167612                          0                       0   
167613                          0                       0   
167916                          0                       0   

        PLANNED_MAINTENANCE  TOTAL_TIME  WAITING_TIME  PRODUCTION_ORDER_RATE  \
496                       0          15             0                  67.00   
516                       0          15             0                  67.00   
699                       0          14             0                  78.90   
1186                      0           4             0                  67.00   
1201                      0          30             0                  67.00   
...                     ...         ...           ...                    ...   
167599                    0          12        

In [ ]:
df['IS_ERROR_16'] = 0
df.loc[df.index.isin(df_unplanned_16.index), 'IS_ERROR_16'] = 1

def chi_square_test_16(df, column):
    data = df[[column, 'IS_ERROR_16']].dropna()
    data[column] = data[column].astype('category')
    contingency_table = pd.crosstab(data[column], data['IS_ERROR_16'])
    if contingency_table.shape[0] < 2 or contingency_table.shape[1] < 2:
        print(f"\nKhông đủ dữ liệu để kiểm định với {column}")
        return
    chi2, p, dof, expected = chi2_contingency(contingency_table)
    V = cramers_v(contingency_table)
    print(f"\nYếu tố: {column}")
    print(f"  Chi-square = {chi2:.3f}")
    print(f"  p-value    = {p:.5f}")
    print(f"  Cramér's V = {V:.4f}")
    if p < 0.05:
        print("    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 16")
    else:
        print("    Kết luận: Không ảnh hưởng đáng kể")

for col in ['LINE_NAME', 'SIZE_TYPE', 'CREW_ID']:
    chi_square_test_16(df, col)



Yếu tố: LINE_NAME
  Chi-square = 3816.851
  p-value    = 0.00000
  Cramér's V = 0.1508
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 16

Yếu tố: SIZE_TYPE
  Chi-square = 2278.603
  p-value    = 0.00000
  Cramér's V = 0.1473
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 16

Yếu tố: CREW_ID
  Chi-square = 58.350
  p-value    = 0.00000
  Cramér's V = 0.0186
    Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 16


Cả LINE_NAME, SIZE_TYPE, và CREW_ID đều có ảnh hưởng đáng kể tới lỗi ID = 16

Tuy nhiên, mức độ ảnh hưởng khác nhau rõ rệt dựa trên Cramér’s V:

- LINE_NAME là yếu tố ảnh hưởng mạnh nhất (V = 0.1508) → Đây là yếu tố chính cần tập trung.

- SIZE_TYPE có ảnh hưởng nhưng yếu hơn (V = 0.1473).

- CREW_ID ảnh hưởng rất nhỏ, gần như không đáng kể (V = 0.0186)

In [ ]:
df_unplanned_16["LINE_NAME"].value_counts()

LINE_NAME
MKZA1501    294
MKZA1502    244
MKZA1802    136
MKBC0501    113
MKZA1801    111
MKZA1602     95
MKBC1102     95
MKBC0502     87
MKBC1101     86
MKZA1402     63
MKZA1401     63
MKBC1002     50
MKZA1701     47
MKBC0901     45
MKZA1601     43
MKZA1702     41
MKBC0302     40
MKTU2004     38
MKBC0301     37
MKTU2001     37
MKBC0202     33
MKTU2005     30
MKBC0402     29
MKBC0601     27
MKTU2002     26
MKTU2006     25
MKBC0102     23
MKBC0902     23
MKTU2003     21
MKBC1301     18
MKBC0602     15
MKBC0401     15
MAFT2204     14
MKBC1001     14
MKBC0201     13
MAFT2205     13
MKBC0101     11
MKBC1202     10
MAFT2202     10
MAFT2203      9
MAFT2201      9
MKBC1201      7
MHPT2304      5
MKBC0702      5
MHPT2302      5
MKFX2101      2
MHPT2303      2
MKBC0701      1
MHPT2307      1
MHPT2301      1
MHPT2305      1
MHPT2306      1
Name: count, dtype: int64

# LINE_NAME

In [ ]:
df_unplanned["PRODUCTS_LOST"] = df_unplanned["DOWNTIME"] * df_unplanned["PRODUCTION_ORDER_RATE"]

/tmp/ipython-input-3723533551.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unplanned["PRODUCTS_LOST"] = df_unplanned["DOWNTIME"] * df_unplanned["PRODUCTION_ORDER_RATE"]


In [ ]:
df_unplanned

PRODUCTIONDATE_DAY_LOC   SHIFT_NAME LINE_NAME            CO_TYPE  \
160                2025-01-02  Afternoon-2  MAFT2201    Material_Handle   
161                2025-01-02  Afternoon-2  MAFT2201    Material_Handle   
163                2025-01-02  Afternoon-2  MAFT2201    Material_Handle   
164                2025-01-02  Afternoon-2  MAFT2201    Material_Handle   
167                2025-01-02  Afternoon-2  MAFT2201    Material_Handle   
...                       ...          ...       ...                ...   
167920             2025-06-30      Night-3  MKZA1501  Material_Filament   
167928             2025-06-30      Night-3  MKZA1502    Material_Handle   
167929             2025-06-30      Night-3  MKZA1502    Material_Handle   
167932             2025-06-30      Night-3  MKZA1502    Material_Handle   
167935             2025-06-30      Night-3  MKZA1502    Material_Handle   

       CREW_ID AE_MODEL_CATEGORY       SIZE_TYPE SHIFT_NAME.1  \
160          A         Unplanned       Renew 360  Afternoon-2   
161          A         Unplanned       Renew 360  Afternoon-2   
163          A         Unplanned       Renew 360  Afternoon-2   
164          A         Unplanned       Renew 360  Afternoon-2   
167          A         Unplanned       Renew 360  Afternoon-2   
...        ...               ...             ...          ...   
167920       C         Unplanned  Super Soft Pro      Night-3   
167928       C         Unplanned  Super Soft Pro      Night-3   
167929       C         Unplanned  Super Soft Pro      Night-3   
167932       C         Unplanned  Super Soft Pro      Night-3   
167935       C         Unplanned  Super Soft Pro      Night-3   

                                  UTIL_REASON_DESCRIPTION  DOWNTIME  ...  \
160         12-Filling tool - 1201-Mechanical adjustment.        17  ...   
161                  07-FLS - 0701-Mechanical adjustment.        12  ...   
163     09-In-feed conveyor - 0901-Mechanical adjustment.        13  ...   
164            06-Fiber box - 0601-Mechanical adjustment.        10  ...   
167               14-Fusing - 1401-Mechanical adjustment.        18  ...   
...                                                   ...       ...  ...   
167920  11-Auto handle feederT2-1102-Stuck handle on c...        10  ...   
167928  11-Auto handle feederT1-1102-Stuck handle on c...         9  ...   
167929  13-Filling toolT1-1306-Replace/adjust mechanic...        40  ...   
167932  06-Fiber boxT2-0602-Replace/adjust mechanical ...        10  ...   
167935                   13-Filling toolT2-1303-Clean jaw        10  ...   

        BUSINESS_EXTERNAL_TIME  PLANNED_MAINTENANCE  TOTAL_TIME  WAITING_TIME  \
160                          0                    0          17             0   
161                          0                    0          12             0   
163                          0                    0          13             0   
164                          0                    0          10             0   
167                          0                    0          18             0   
...                        ...                  ...         ...           ...   
167920                       0                    0          10             0   
167928                       0                    0           9             0   
167929                       0                    0          40             0   
167932                       0                    0          10             0   
167935                       0                    0          10             0   

        PRODUCTION_ORDER_RATE  ID          Machine_Name      Error_Code  \
160                     24.00  12         Filling tool             1201   
161                     24.00  07                  FLS             0701   
163                     24.00  09                    In  feed conveyor    
164                     24.00  06            Fiber box             0601   
167                     24.00  14               Fusing          

In [ ]:
df_unplanned.groupby("LINE_NAME")["PRODUCTS_LOST"].sum().sort_values(ascending=False)

LINE_NAME
MKZA1501    3271850.35
MKBC0202    3257872.20
MKZA1502    3239302.29
MKZA1601    3000394.00
MKBC0102    2931051.20
MKZA1402    2826978.00
MKBC0501    2811243.60
MKBC0901    2635041.05
MKZA1802    2608980.00
MKZA1801    2422988.00
MKZA1401    2392379.00
MKBC0502    2295896.85
MKBC0201    2231456.60
MKBC1202    2210729.30
MKBC0101    2184744.00
MKBC1102    2089628.00
MKBC0902    1928320.80
MHPT2307    1872251.88
MKBC0601    1789688.70
MHPT2303    1738602.20
MKBC1002    1734213.60
MKBC1201    1614812.99
MKBC1101    1598198.40
MKBC0302    1525226.20
MKZA1602    1455540.00
MHPT2305    1372677.64
MKZA1701    1345351.00
MKBC0602    1331753.10
MKBC0301    1253042.30
MHPT2304    1252399.64
MKBC0702    1226914.15
MKFX2101    1125429.60
MHPT2301    1122624.00
MKZA1702    1073550.00
MKBC1301    1032753.76
MHPT2306    1004686.12
MKBC0701     965264.00
MHPT2302     827184.00
MKBC0401     693294.58
MKTU2005     679837.01
MKTU2004     676530.84
MKFX2102     662207.70
MAFT2203     617400.00
MKBC1001     598020.00
MKBC0402     565184.39
MKTU2003     539283.68
MAFT2202     507192.00
MAFT2204     466128.00
MKTU2001     463645.00
MAFT2201     434112.00
MKTU2002     390492.48
MKTU2006     314013.14
MAFT2205     287232.00
Name: PRODUCTS_LOST, dtype: float64

## MKZA1501

In [ ]:
MKZA1501 = df_unplanned[df_unplanned['LINE_NAME'] == 'MKZA1501']

In [ ]:
MKZA1501["UTIL_REASON_DESCRIPTION"].value_counts()

UTIL_REASON_DESCRIPTION
02-Quality - 0202-Rework                                        195
16-Autosorter - 1601-Handle on chain stuck                      166
17-End Feeder - 1702-Jammed handle on chain                      81
13-Filling toolT1-1303-Clean jaw                                 63
16-Autosorter - 1602-Handle sort robot stuck                     59
                                                               ... 
13-Filling toolT1-1302-Clean filling tool box                     1
03-Material changingT1-0302-Unplanned driver tip replacement      1
03-Material changingT3-0302-Unplanned driver tip replacement      1
07-Code date/host stamp - 0702-Adjust code date/host stamp        1
13-Filling toolT3-1302-Clean filling tool box                     1
Name: count, Length: 148, dtype: int64

In [ ]:
df[df["LINE_NAME"] == "MKZA1501"]["AE_MODEL_CATEGORY"].value_counts()

AE_MODEL_CATEGORY
Unplanned            1642
Plant Decision       1141
Runtime               402
Business External     202
Name: count, dtype: int64

Tỷ lệ lỗi = 1642/(1642+402) = 0.80332681017

In [ ]:
MKZA1501["DOWNTIME"].sum()

np.int64(48497)

In [ ]:
(MKZA1501["DOWNTIME"]*MKZA1501["PRODUCTION_ORDER_RATE"]).sum()

np.float64(3271850.35)

## MKBC0202

In [ ]:
MKBC0202 = df_unplanned[df_unplanned['LINE_NAME'] == 'MKBC0202']

In [ ]:
MKBC0202["UTIL_REASON_DESCRIPTION"].value_counts()

UTIL_REASON_DESCRIPTION
17-End Feeder - 1702-Jammed handle on chain                                 357
13-FM chain - 1306-Handle stuck on FM                                       236
11-Auto handle feederT1-1102-Stuck handle on chain                          140
11-Auto handle feederT3-1102-Stuck handle on chain                          129
02-Quality - 0202-Rework                                                    118
                                                                           ... 
13-Filling toolT2-1307-Replace/adjust mechanical details of Filling tool      1
13-Filling toolT2-1302-Clean filling tool box                                 1
10-Trimming Unit - 1002-Replace details of Trimming unit                      1
17-Main shaftT2-1702-Replace main motor                                       1
15-Electrical cabinet/displayT2-1506-Another repairs in cabinet               1
Name: count, Length: 132, dtype: int64

In [ ]:
df[df["LINE_NAME"] == "MKBC0202"]["AE_MODEL_CATEGORY"].value_counts()

AE_MODEL_CATEGORY
Unplanned            1916
Plant Decision       1653
Runtime               411
Business External     140
Name: count, dtype: int64

Tỷ lệ lỗi = 1916/(1916+411) = 0.82337773957

In [ ]:
MKBC0202["DOWNTIME"].sum()

np.int64(40023)

In [ ]:
(MKBC0202["DOWNTIME"]*MKBC0202["PRODUCTION_ORDER_RATE"]).sum()

np.float64(3257872.2)

## MKZA1502


In [ ]:
MKZA1502 = df_unplanned[df_unplanned['LINE_NAME'] == 'MKZA1502']

In [ ]:
MKZA1502["UTIL_REASON_DESCRIPTION"].value_counts()

UTIL_REASON_DESCRIPTION
02-Quality - 0202-Rework                                                      196
16-Autosorter - 1601-Handle on chain stuck                                    128
17-End Feeder - 1702-Jammed handle on chain                                   102
03-Material changing - 0301-Replace material                                   58
13-Filling toolT1-1303-Clean jaw                                               54
                                                                             ... 
03-Material changingT3-0301-Replace material                                    1
11-Auto handle feederT3-1104-Lack of handle on chain                            1
11-Auto handle feederT3-1107-Replace/adjust MECH parts of Hopper-Separator      1
11-Auto handle feederT3-1113-Adjust parameter of auto handle feeder             1
07-Anchor wire feedingT2-0703-Cleaning/adjust anchor wire feeding               1
Name: count, Length: 133, dtype: int64

In [ ]:
df[df["LINE_NAME"] == "MKZA1502"]["AE_MODEL_CATEGORY"].value_counts()

AE_MODEL_CATEGORY
Unplanned            1520
Plant Decision        990
Runtime               330
Business External     248
Name: count, dtype: int64

Tỷ lệ lỗi = 1520/(1520+330) = 0.82162162162

In [ ]:
MKZA1502["DOWNTIME"].sum()

np.int64(47431)

In [ ]:
(MKZA1502["DOWNTIME"]*MKZA1502["PRODUCTION_ORDER_RATE"]).sum()

np.float64(3239302.29)

## MKZA1601

In [ ]:
MKZA1601 = df_unplanned[df_unplanned['LINE_NAME'] == 'MKZA1601']

In [ ]:
MKZA1601["UTIL_REASON_DESCRIPTION"].value_counts()

UTIL_REASON_DESCRIPTION
02-Quality - 0202-Rework                                    190
17-End Feeder - 1701-Double handle on chain                 139
17-End Feeder - 1702-Jammed handle on chain                 125
17-End Feeder - 1705-Mechanical Adjustment                   29
11-Auto handle feederT1-1101-Double hadle on chain           25
                                                           ... 
13-Filling toolT1-1301-Clean driver tip                       1
13-Filling toolT2-1301-Clean driver tip                       1
10-MechanicalT2-1004-Adjust conveyor                          1
18-Laser and vision system - 1801-Repair laser code date      1
16-CoordinationT2-1601-X/ Y motor is failed                   1
Name: count, Length: 93, dtype: int64

In [ ]:
df[df["LINE_NAME"] == "MKZA1601"]["AE_MODEL_CATEGORY"].value_counts()

AE_MODEL_CATEGORY
Unplanned            855
Plant Decision       669
Business External    318
Runtime              241
Name: count, dtype: int64

Tỷ lệ lỗi = 855/(855+241) = 0.78010948905

In [ ]:
MKZA1601["DOWNTIME"].sum()

np.int64(44610)

In [ ]:
(MKZA1601["DOWNTIME"]*MKZA1601["PRODUCTION_ORDER_RATE"]).sum()

np.float64(3000394.0)

## MKBC0102

In [ ]:
MKBC0102 = df_unplanned[df_unplanned['LINE_NAME'] == 'MKBC0102']

In [ ]:
MKBC0102["UTIL_REASON_DESCRIPTION"].value_counts()

UTIL_REASON_DESCRIPTION
11-Auto handle feederT1-1101-Double hadle on chain                      215
11-Auto handle feederT3-1101-Double hadle on chain                      207
11-Auto handle feederT2-1101-Double hadle on chain                      205
13-FM chain - 1306-Handle stuck on FM                                   193
17-End Feeder - 1712-Lack of handle on chain End Feeder                 121
                                                                       ... 
13-Filling toolT3-1303-Clean jaw                                          1
06-Fiber boxT1-0602-Replace/adjust mechanical parts of fiber beaters      1
10-MechanicalT3-1001-Jam conveyor                                         1
10-MechanicalT3-1003-Replace detials of conveyor                          1
12-TurretT1-1201-Replace/adjust parts of turret                           1
Name: count, Length: 103, dtype: int64

In [ ]:
df[df["LINE_NAME"] == "MKBC0102"]["AE_MODEL_CATEGORY"].value_counts()

AE_MODEL_CATEGORY
Unplanned            1784
Plant Decision       1479
Runtime               389
Business External     179
Name: count, dtype: int64

Tỷ lệ lỗi = 1784/(1784+389) = 0.82098481362

In [ ]:
MKBC0102["DOWNTIME"].sum()

np.int64(36008)

In [ ]:
(MKBC0102["DOWNTIME"]*MKBC0102["PRODUCTION_ORDER_RATE"]).sum()

np.float64(2931051.2)

#SIZE_TYPE

In [ ]:
df_unplanned.groupby("SIZE_TYPE")["PRODUCTS_LOST"].sum().sort_values(ascending=False)

SIZE_TYPE
Total Defense Shield            10855881.88
Classic Clean 100               10828558.40
Total Action Model S             7675192.60
Super Soft Tech                  5984921.90
EcoFresh Plus                    5790438.10
Pro-Clean 5000                   5675289.40
Deep Action White                5207058.00
Precision Grip 2.0               3000394.00
ActiveClean Guard                2884203.45
ActiveClean Model X              2826978.00
Pro-Shield Complete              2491654.00
Junior Sparkle (Ages 2+)         2276162.00
Renew 360                        2024832.00
GreenClean Pro                   2021811.45
Kids FunBrush (Tandy)            1634602.00
Super Soft Pro                   1370654.64
Zenith Active                    1349457.96
Classic White 110                1307136.30
PureMint Fresh                   1035150.00
Total Action Green                932925.00
Ocean Explorer (Ages 6+)          860000.00
Defense Action Pro                718140.00
Safari Explorer (Ages 6+)         358792.00
Advanced Hydro-Clean              348525.00
Oral Care 360                     287232.00
Zenith GreenClean                 219203.46
EcoFresh Green                    171796.20
GreenClean Classic                138540.00
Junior Guard Taper (Ages 5+)       80011.00
Zenith Classic Clean               70818.00
EcoSoft Classic                    60731.10
GreenClean Ultra                    8501.50
Name: PRODUCTS_LOST, dtype: float64

## Renew 360

In [ ]:
Renew_360 = df_unplanned[df_unplanned['SIZE_TYPE'] == 'Renew 360']

In [ ]:
Renew_360["UTIL_REASON_DESCRIPTION"].value_counts()

UTIL_REASON_DESCRIPTION
12-Filling tool - 1201-Mechanical adjustment.                          558
14-Fusing - 1401-Mechanical adjustment.                                499
03-Change material - 0301-Change material                              325
20-FM - 2001-Mechanical adjustment.                                    160
14-Fusing - 1407-Coordination/program adjusment                        152
                                                                      ... 
16-Robot infeed headplate - 1606-Replace new electronic instruments      1
15-Electrical cabinet/display - 1501-Display screen is broken            1
18-Robot outfeed headplate - 1803-Pneumatic cylinder adjustment          1
10-In-feed Head Plate conveyor - 1003-Pneumatic cylinder adjustment      1
14-Fusing - 1406-Replace new electronic instruments                      1
Name: count, Length: 65, dtype: int64

In [ ]:
df[df["SIZE_TYPE"] == "Renew 360"]["AE_MODEL_CATEGORY"].value_counts()

AE_MODEL_CATEGORY
Unplanned         2757
Runtime            827
Plant Decision     281
Name: count, dtype: int64

Tỷ lệ lỗi = 2757/(2757+827) = 0.76925223214

In [ ]:
Renew_360["DOWNTIME"].sum()

np.int64(83899)

In [ ]:
(Renew_360["DOWNTIME"]*Renew_360["PRODUCTION_ORDER_RATE"]).sum()

np.float64(2024832.0)

## Deep Action White

In [ ]:
Deep_Action_White = df_unplanned[df_unplanned['SIZE_TYPE'] == 'Deep Action White']

In [ ]:
Deep_Action_White["UTIL_REASON_DESCRIPTION"].value_counts()

UTIL_REASON_DESCRIPTION
03-Change material - 0301-Change material                           799
18-Autofeeder - 1802-Stuck handle on chain                          454
06-Fiber box - 0602-Adjust sparepart                                433
12-Filling tool - 1201-Cleaning Jaw                                 375
02-Quality - 0202-Rework                                            324
                                                                   ... 
07-Anchor wire feeding - 0702-Replace mechanical                      1
03-Material changingT1-0301-Replace material                          1
12-TurretT1-1207-Clean details of Turret                              1
06-Fiber boxT3-0601-Replace/adjust mechanical parts of fiber box      1
10-MechanicalT1-1004-Adjust conveyor                                  1
Name: count, Length: 225, dtype: int64

In [ ]:
df[df["SIZE_TYPE"] == "Deep Action White"]["AE_MODEL_CATEGORY"].value_counts()

AE_MODEL_CATEGORY
Unplanned         4925
Runtime           1694
Plant Decision     274
Name: count, dtype: int64

Tỷ lệ lỗi = 4925/(4925+1694) = 0.74407010122

In [ ]:
Deep_Action_White["DOWNTIME"].sum()

np.int64(102168)

In [ ]:
(Deep_Action_White["DOWNTIME"]*Deep_Action_White["PRODUCTION_ORDER_RATE"]).sum()

np.float64(5207058.0)

## Total Defense Shield

In [ ]:
Total_Defense_Shield = df_unplanned[df_unplanned['SIZE_TYPE'] == 'Total Defense Shield']

In [ ]:
Total_Defense_Shield["UTIL_REASON_DESCRIPTION"].value_counts()

UTIL_REASON_DESCRIPTION
03-Change material - 0301-Change material                              1401
18-Autofeeder - 1802-Stuck handle on chain                              870
06-Fiber box - 0602-Adjust sparepart                                    787
17-End Feeder - 1702-Jammed handle on chain                             699
13-FM chain - 1306-Handle stuck on FM                                   557
                                                                       ... 
10-MechanicalT1-1003-Replace detials of conveyor                          1
11-Auto handle feederT2-1113-Adjust parameter of auto handle feeder       1
06-Fiber boxT3-0603-Replace/adjust pneumatic parts of fiber box           1
10-Trimming Unit - 1003-Adjusting height of Trimming station              1
15-Electrical cabinet/display - 1504-CB overcurrent                       1
Name: count, Length: 260, dtype: int64

In [ ]:
df[df["SIZE_TYPE"] == "Total Defense Shield"]["AE_MODEL_CATEGORY"].value_counts()

AE_MODEL_CATEGORY
Unplanned         9975
Runtime           3267
Plant Decision     614
Name: count, dtype: int64

Tỷ lệ lỗi = 9975/(9975+3267) = 0.75328500226

In [ ]:
Total_Defense_Shield["DOWNTIME"].sum()

np.int64(153220)

In [ ]:
(Total_Defense_Shield["DOWNTIME"]*Total_Defense_Shield["PRODUCTION_ORDER_RATE"]).sum()

np.float64(10855881.88)

## Classic Clean 100

In [ ]:
Classic_Clean_100 = df_unplanned[df_unplanned['SIZE_TYPE'] == 'Classic Clean 100']

In [ ]:
Classic_Clean_100["UTIL_REASON_DESCRIPTION"].value_counts()

UTIL_REASON_DESCRIPTION
17-End Feeder - 1702-Jammed handle on chain                                      571
13-FM chain - 1306-Handle stuck on FM                                            481
17-End Feeder - 1701-Double handle on chain                                      427
11-Auto handle feederT2-1102-Stuck handle on chain                               334
11-Auto handle feederT1-1102-Stuck handle on chain                               329
                                                                                ... 
16-CoordinationT3-1603-Replace/adjust mechanical detail of coordination            1
07-Anchor wire feedingT2-0702-Replace/adjust mechanical parts of wire feeding      1
16-Autosorter - 1608-WIP conveyor wrong position                                   1
16-Autosorter - 1614-Conveyor position adjustment                                  1
19-Vario Flow - 1901-Mechanical Vario Flow replacement                             1
Name: count, Length: 274, dtype: int64

In [ ]:
df[df["SIZE_TYPE"] == "Classic Clean 100"]["AE_MODEL_CATEGORY"].value_counts()

AE_MODEL_CATEGORY
Unplanned         7545
Runtime           2940
Plant Decision     581
Name: count, dtype: int64

Tỷ lệ lỗi = 7545/(7545+2940) = 0.71959942775

In [ ]:
Classic_Clean_100["DOWNTIME"].sum()

np.int64(141657)

In [ ]:
(Classic_Clean_100["DOWNTIME"]*Classic_Clean_100["PRODUCTION_ORDER_RATE"]).sum()

np.float64(10828558.4)

## Total Action Model S

In [ ]:
Total_Action_Model_S = df_unplanned[df_unplanned['SIZE_TYPE'] == 'Total Action Model S']

In [ ]:
Total_Action_Model_S["UTIL_REASON_DESCRIPTION"].value_counts()

UTIL_REASON_DESCRIPTION
03-Change material - 0301-Change material                       429
02-Quality - 0202-Rework                                        416
18-Autofeeder - 1802-Stuck handle on chain                      344
05-Labor - 0509-Move to get WIP                                 279
06-Fiber box - 0602-Adjust sparepart                            175
                                                               ... 
13-FM chain - 1303-Sensor broken                                  1
03-Material changingT3-0302-Unplanned driver tip replacement      1
10-Trimming Unit - 1003-Adjusting height of Trimming station      1
16-Autosorter - 1603-Handle sort valve broken                     1
11-Turet - 1105-Adjust turet location                             1
Name: count, Length: 209, dtype: int64

In [ ]:
df[df["SIZE_TYPE"] == "Total Action Model S"]["AE_MODEL_CATEGORY"].value_counts()

AE_MODEL_CATEGORY
Unplanned         3836
Runtime           1312
Plant Decision     562
Name: count, dtype: int64

Tỷ lệ lỗi = 3836/(3836+1312) =0.74514374514

In [ ]:
Total_Action_Model_S["DOWNTIME"].sum()

np.int64(109548)

In [ ]:
(Total_Action_Model_S["DOWNTIME"]*Total_Action_Model_S["PRODUCTION_ORDER_RATE"]).sum()

np.float64(7675192.6)

## Super Soft Tech

In [ ]:
Super_Soft_Tech = df_unplanned[df_unplanned['SIZE_TYPE'] == 'Super Soft Tech']

In [ ]:
Super_Soft_Tech["UTIL_REASON_DESCRIPTION"].value_counts()

UTIL_REASON_DESCRIPTION
02-Quality - 0202-Rework                                                      316
16-Autosorter - 1601-Handle on chain stuck                                    196
11-Auto handle feederT1-1101-Double hadle on chain                            146
17-End Feeder - 1702-Jammed handle on chain                                   121
11-Auto handle feederT3-1101-Double hadle on chain                            113
                                                                             ... 
06-Fiber boxT2-0601-Replace/adjust mechanical parts of fiber box                1
09-Compressor airT1-0901-Replace details of valve/air pipe                      1
15-Electrical cabinet/displayT3-1506-Another repairs in cabinet                 1
07-Anchor wire feedingT2-0705-Break down of sensor empty/stuck anchor wire      1
11-Endrounding station - 1102-Replace details of Endrounding station            1
Name: count, Length: 178, dtype: int64

In [ ]:
df[df["SIZE_TYPE"] == "Super Soft Tech"]["AE_MODEL_CATEGORY"].value_counts()

AE_MODEL_CATEGORY
Unplanned         2862
Runtime            816
Plant Decision     346
Name: count, dtype: int64

Tỷ lệ lỗi = 2862/(2862+816) = 0.77814029363

In [ ]:
Super_Soft_Tech["DOWNTIME"].sum()

np.int64(86692)

In [ ]:
(Super_Soft_Tech["DOWNTIME"]*Super_Soft_Tech["PRODUCTION_ORDER_RATE"]).sum()

np.float64(5984921.9)

## EcoFresh Plus

In [ ]:
EcoFresh_Plus = df_unplanned[df_unplanned['SIZE_TYPE'] == 'EcoFresh Plus']

In [ ]:
EcoFresh_Plus["UTIL_REASON_DESCRIPTION"].value_counts()

UTIL_REASON_DESCRIPTION
17-End Feeder - 1702-Jammed handle on chain                                   696
13-FM chain - 1306-Handle stuck on FM                                         431
17-End Feeder - 1701-Double handle on chain                                   348
11-Auto handle feederT2-1102-Stuck handle on chain                            173
11-Auto handle feederT1-1102-Stuck handle on chain                            154
                                                                             ... 
05-LaborT3-0506-Training/ meeting out of plan                                   1
15-Electrical cabinet/displayT1-1506-Another repairs in cabinet                 1
16-CoordinationT3-1603-Replace/adjust mechanical detail of coordination         1
07-Anchor wire feedingT2-0705-Break down of sensor empty/stuck anchor wire      1
04-MaterialT3-0403-Waiting for receiving spare part                             1
Name: count, Length: 162, dtype: int64

In [ ]:
df[df["SIZE_TYPE"] == "EcoFresh Plus"]["AE_MODEL_CATEGORY"].value_counts()

AE_MODEL_CATEGORY
Unplanned         3622
Runtime           1250
Plant Decision    1014
Name: count, dtype: int64

Tỷ lệ lỗi = 3622/(3622+1250) = 0.7434318555

In [ ]:
EcoFresh_Plus["DOWNTIME"].sum()

np.int64(67407)

In [ ]:
(EcoFresh_Plus["DOWNTIME"]*EcoFresh_Plus["PRODUCTION_ORDER_RATE"]).sum()

np.float64(5790438.1)

# TỔNG THỂ

In [ ]:
# YẾU TỐ ẢNH HƯỞNG ĐẾN TẤT CẢ CÁC LỖI
df['IS_ERROR'] = 0
df.loc[df.index.isin(df_unplanned.index), 'IS_ERROR'] = 1

def chi_square_test(df, column):
    data = df[[column, 'IS_ERROR']].dropna()
    data[column] = data[column].astype('category')
    contingency_table = pd.crosstab(data[column], data['IS_ERROR'])
    if contingency_table.shape[0] < 2 or contingency_table.shape[1] < 2:
        print(f"\nKhông đủ dữ liệu để kiểm định với {column}")
        return
    chi2, p, dof, expected = chi2_contingency(contingency_table)
    V = cramers_v(contingency_table)
    print(f"\nYếu tố: {column}")
    print(f"  Chi-square = {chi2:.3f}")
    print(f"  p-value    = {p:.5f}")
    print(f"  Cramér's V = {V:.4f}")
    if p < 0.05:
        print("    Kết luận: Có ảnh hưởng đáng kể đến lỗi")
    else:
        print("    Kết luận: Không ảnh hưởng đáng kể")

for col in ['LINE_NAME', 'SIZE_TYPE', 'CREW_ID']:
    chi_square_test(df, col)



Yếu tố: LINE_NAME
  Chi-square = 4716.733
  p-value    = 0.00000
  Cramér's V = 0.1676
    Kết luận: Có ảnh hưởng đáng kể đến lỗi

Yếu tố: SIZE_TYPE
  Chi-square = 2328.051
  p-value    = 0.00000
  Cramér's V = 0.1489
    Kết luận: Có ảnh hưởng đáng kể đến lỗi

Yếu tố: CREW_ID
  Chi-square = 58.876
  p-value    = 0.00000
  Cramér's V = 0.0187
    Kết luận: Có ảnh hưởng đáng kể đến lỗi


Cả LINE_NAME, SIZE_TYPE, và CREW_ID đều có ảnh hưởng đáng kể tới lỗi (p-value = 0.00000).

Tuy nhiên, mức độ ảnh hưởng khác nhau rõ rệt dựa trên Cramér’s V:

- LINE_NAME là yếu tố ảnh hưởng mạnh nhất (V = 0.1676) → Đây là yếu tố chính cần tập trung.

- SIZE_TYPE có ảnh hưởng nhưng yếu hơn (V = 0.1489).

- CREW_ID ảnh hưởng rất nhỏ, gần như không đáng kể (V = 0.0187)

In [ ]:
# Tính tổng DOWNTIME theo ID
total_downtime_per_id = df_unplanned.groupby('ID')['DOWNTIME'].sum().reset_index()

# Sắp xếp giảm dần
total_downtime_per_id_sorted_desc = total_downtime_per_id.sort_values(by='DOWNTIME', ascending=False)

print(total_downtime_per_id_sorted_desc)


    ID  DOWNTIME
1   02    285060
10  11    203676
16  17    168519
12  13     95570
13  14     90991
5   06     71421
11  12     71145
17  18     57354
15  16     40917
4   05     33406
9   10     32049
2   03     31140
3   04     18090
14  15     16617
6   07     15178
19  20     14232
25  26      5199
8   09      3923
24  25      2967
18  19      2687
22  23      1840
23  24      1758
28  29      1701
26  27      1560
0   01      1492
21  22      1350
20  21      1039
7   08       587
27  28       340


In [ ]:
# TOTAL PRODUCTS LOST DUE TO DOWNTIME
(df_unplanned["DOWNTIME"]*df_unplanned["PRODUCTION_ORDER_RATE"]).sum()

np.float64(80495591.34)