In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("production_logs.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167946 entries, 0 to 167945
Data columns (total 27 columns):
 #   Column                     Non-Null Count   Dtype  
---  ------                     --------------   -----  
 0   PRODUCTIONDATE_DAY_LOC     167946 non-null  object 
 1   SHIFT_NAME                 167946 non-null  object 
 2   LINE_NAME                  167946 non-null  object 
 3   CO_TYPE                    145176 non-null  object 
 4   CREW_ID                    167787 non-null  object 
 5   AE_MODEL_CATEGORY          148392 non-null  object 
 6   SIZE_TYPE                  104949 non-null  object 
 7   SHIFT_NAME.1               167946 non-null  object 
 8   UTIL_REASON_DESCRIPTION    148392 non-null  object 
 9   DOWNTIME                   167946 non-null  int64  
 10  EFFECTIVE_RUNTIME          104949 non-null  float64
 11  GOOD_PRODUCTION_QTY        167946 non-null  int64  
 12  LUNCH_AND_BREAK            167946 non-null  int64  
 13  MEETING_AND_TRAINING       16

In [4]:
df['PRODUCTIONDATE_DAY_LOC'] = pd.to_datetime(df['PRODUCTIONDATE_DAY_LOC'], dayfirst=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167946 entries, 0 to 167945
Data columns (total 27 columns):
 #   Column                     Non-Null Count   Dtype         
---  ------                     --------------   -----         
 0   PRODUCTIONDATE_DAY_LOC     167946 non-null  datetime64[ns]
 1   SHIFT_NAME                 167946 non-null  object        
 2   LINE_NAME                  167946 non-null  object        
 3   CO_TYPE                    145176 non-null  object        
 4   CREW_ID                    167787 non-null  object        
 5   AE_MODEL_CATEGORY          148392 non-null  object        
 6   SIZE_TYPE                  104949 non-null  object        
 7   SHIFT_NAME.1               167946 non-null  object        
 8   UTIL_REASON_DESCRIPTION    148392 non-null  object        
 9   DOWNTIME                   167946 non-null  int64         
 10  EFFECTIVE_RUNTIME          104949 non-null  float64       
 11  GOOD_PRODUCTION_QTY        167946 non-null  int64   

/tmp/ipython-input-1561415343.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['PRODUCTIONDATE_DAY_LOC'] = pd.to_datetime(df['PRODUCTIONDATE_DAY_LOC'], dayfirst=True)


In [5]:
df = df.sort_values(by=['PRODUCTIONDATE_DAY_LOC', 'SHIFT_NAME', 'LINE_NAME'], ascending=[True, True, True]).reset_index(drop=True)

In [6]:
df

PRODUCTIONDATE_DAY_LOC   SHIFT_NAME LINE_NAME            CO_TYPE  \
0                  2025-01-01  Afternoon-2  MAFT2201    Material_Handle   
1                  2025-01-01  Afternoon-2  MAFT2202    Material_Handle   
2                  2025-01-01  Afternoon-2  MAFT2203    Material_Handle   
3                  2025-01-01  Afternoon-2  MAFT2204  Material_Filament   
4                  2025-01-01  Afternoon-2  MAFT2205    Material_Handle   
...                       ...          ...       ...                ...   
167941             2025-06-30      Night-3  MKZA1702    Material_Handle   
167942             2025-06-30      Night-3  MKZA1702    Material_Handle   
167943             2025-06-30      Night-3  MKZA1702    Material_Handle   
167944             2025-06-30      Night-3  MKZA1801    Material_Handle   
167945             2025-06-30      Night-3  MKZA1802    Material_Handle   

       CREW_ID  AE_MODEL_CATEGORY SIZE_TYPE SHIFT_NAME.1  \
0          NaN  Business External       NaN  Afternoon-2   
1          NaN  Business External       NaN  Afternoon-2   
2          NaN  Business External       NaN  Afternoon-2   
3          NaN  Business External       NaN  Afternoon-2   
4          NaN  Business External       NaN  Afternoon-2   
...        ...                ...       ...          ...   
167941       C     Plant Decision       NaN      Night-3   
167942       C     Plant Decision       NaN      Night-3   
167943       C     Plant Decision       NaN      Night-3   
167944       C  Business External       NaN      Night-3   
167945       C  Business External       NaN      Night-3   

        UTIL_REASON_DESCRIPTION  DOWNTIME  ...  PRODUCTION_AVAILABLE_TIME  \
0                       Holiday         0  ...                          0   
1                       Holiday         0  ...                          0   
2                       Holiday         0  ...                          0   
3                       Holiday         0  ...                          0   
4                       Holiday         0  ...                          0   
...                         ...       ...  ...                        ...   
167941              Lunch/Break         0  ...                          0   
167942  Cleaning and Sanitation         0  ...                          0   
167943      Planned Maintenance         0  ...                          0   
167944                No Demand         0  ...                          0   
167945                No Demand         0  ...                          0   

        REJECT_PRODUCTION_QTY  RUN_TIME  CHANGEOVER_DURATION  \
0                           0         0                    0   
1                           0         0                    0   
2                           0         0                    0   
3                           0         0                    0   
4                           0         0                    0   
...                       ...       ...                  ...   
167941                      0         0                    0   
167942                      0         0                    0   
167943                      0         0                    0   
167944                      0         0                    0   
167945                      0         0                    0   

        CLEANING_AND_SANITIZATION  BUSINESS_EXTERNAL_TIME  \
0                               0                     480   
1                               0                     480   
2                               0                     480   
3                               0                     480   
4                               0                     480   
...                           ...                     ...   
167941                          0                       0   
167942                         15                       0   
167943                          0                       0   
167944                          0                     480   
167945              

In [7]:
df

PRODUCTIONDATE_DAY_LOC   SHIFT_NAME LINE_NAME            CO_TYPE  \
0                  2025-01-01  Afternoon-2  MAFT2201    Material_Handle   
1                  2025-01-01  Afternoon-2  MAFT2202    Material_Handle   
2                  2025-01-01  Afternoon-2  MAFT2203    Material_Handle   
3                  2025-01-01  Afternoon-2  MAFT2204  Material_Filament   
4                  2025-01-01  Afternoon-2  MAFT2205    Material_Handle   
...                       ...          ...       ...                ...   
167941             2025-06-30      Night-3  MKZA1702    Material_Handle   
167942             2025-06-30      Night-3  MKZA1702    Material_Handle   
167943             2025-06-30      Night-3  MKZA1702    Material_Handle   
167944             2025-06-30      Night-3  MKZA1801    Material_Handle   
167945             2025-06-30      Night-3  MKZA1802    Material_Handle   

       CREW_ID  AE_MODEL_CATEGORY SIZE_TYPE SHIFT_NAME.1  \
0          NaN  Business External       NaN  Afternoon-2   
1          NaN  Business External       NaN  Afternoon-2   
2          NaN  Business External       NaN  Afternoon-2   
3          NaN  Business External       NaN  Afternoon-2   
4          NaN  Business External       NaN  Afternoon-2   
...        ...                ...       ...          ...   
167941       C     Plant Decision       NaN      Night-3   
167942       C     Plant Decision       NaN      Night-3   
167943       C     Plant Decision       NaN      Night-3   
167944       C  Business External       NaN      Night-3   
167945       C  Business External       NaN      Night-3   

        UTIL_REASON_DESCRIPTION  DOWNTIME  ...  PRODUCTION_AVAILABLE_TIME  \
0                       Holiday         0  ...                          0   
1                       Holiday         0  ...                          0   
2                       Holiday         0  ...                          0   
3                       Holiday         0  ...                          0   
4                       Holiday         0  ...                          0   
...                         ...       ...  ...                        ...   
167941              Lunch/Break         0  ...                          0   
167942  Cleaning and Sanitation         0  ...                          0   
167943      Planned Maintenance         0  ...                          0   
167944                No Demand         0  ...                          0   
167945                No Demand         0  ...                          0   

        REJECT_PRODUCTION_QTY  RUN_TIME  CHANGEOVER_DURATION  \
0                           0         0                    0   
1                           0         0                    0   
2                           0         0                    0   
3                           0         0                    0   
4                           0         0                    0   
...                       ...       ...                  ...   
167941                      0         0                    0   
167942                      0         0                    0   
167943                      0         0                    0   
167944                      0         0                    0   
167945                      0         0                    0   

        CLEANING_AND_SANITIZATION  BUSINESS_EXTERNAL_TIME  \
0                               0                     480   
1                               0                     480   
2                               0                     480   
3                               0                     480   
4                               0                     480   
...                           ...                     ...   
167941                          0                       0   
167942                         15                       0   
167943                          0                       0   
167944                          0                     480   
167945              

In [170]:
df_unplanned = df[df["AE_MODEL_CATEGORY"] == "Unplanned"] # thông tin về hoạt động không được lên lịch
df_plant_decision = df[df["AE_MODEL_CATEGORY"] == "Plant Decision"]
df_business_external = df[df["AE_MODEL_CATEGORY"] == "Business External"]

# DF_UNPLANNED

In [9]:
df_unplanned

PRODUCTIONDATE_DAY_LOC   SHIFT_NAME LINE_NAME            CO_TYPE  \
160                2025-01-02  Afternoon-2  MAFT2201    Material_Handle   
161                2025-01-02  Afternoon-2  MAFT2201    Material_Handle   
163                2025-01-02  Afternoon-2  MAFT2201    Material_Handle   
164                2025-01-02  Afternoon-2  MAFT2201    Material_Handle   
167                2025-01-02  Afternoon-2  MAFT2201    Material_Handle   
...                       ...          ...       ...                ...   
167920             2025-06-30      Night-3  MKZA1501  Material_Filament   
167928             2025-06-30      Night-3  MKZA1502    Material_Handle   
167929             2025-06-30      Night-3  MKZA1502    Material_Handle   
167932             2025-06-30      Night-3  MKZA1502    Material_Handle   
167935             2025-06-30      Night-3  MKZA1502    Material_Handle   

       CREW_ID AE_MODEL_CATEGORY       SIZE_TYPE SHIFT_NAME.1  \
160          A         Unplanned       Renew 360  Afternoon-2   
161          A         Unplanned       Renew 360  Afternoon-2   
163          A         Unplanned       Renew 360  Afternoon-2   
164          A         Unplanned       Renew 360  Afternoon-2   
167          A         Unplanned       Renew 360  Afternoon-2   
...        ...               ...             ...          ...   
167920       C         Unplanned  Super Soft Pro      Night-3   
167928       C         Unplanned  Super Soft Pro      Night-3   
167929       C         Unplanned  Super Soft Pro      Night-3   
167932       C         Unplanned  Super Soft Pro      Night-3   
167935       C         Unplanned  Super Soft Pro      Night-3   

                                  UTIL_REASON_DESCRIPTION  DOWNTIME  ...  \
160         12-Filling tool - 1201-Mechanical adjustment.        17  ...   
161                  07-FLS - 0701-Mechanical adjustment.        12  ...   
163     09-In-feed conveyor - 0901-Mechanical adjustment.        13  ...   
164            06-Fiber box - 0601-Mechanical adjustment.        10  ...   
167               14-Fusing - 1401-Mechanical adjustment.        18  ...   
...                                                   ...       ...  ...   
167920  11-Auto handle feederT2-1102-Stuck handle on c...        10  ...   
167928  11-Auto handle feederT1-1102-Stuck handle on c...         9  ...   
167929  13-Filling toolT1-1306-Replace/adjust mechanic...        40  ...   
167932  06-Fiber boxT2-0602-Replace/adjust mechanical ...        10  ...   
167935                   13-Filling toolT2-1303-Clean jaw        10  ...   

        PRODUCTION_AVAILABLE_TIME  REJECT_PRODUCTION_QTY  RUN_TIME  \
160                            17                      0         0   
161                            12                      0         0   
163                            13                      0         0   
164                            10                      0         0   
167                            18                      0         0   
...                           ...                    ...       ...   
167920                         10                      0         0   
167928                          9                      0         0   
167929                         40                      0         0   
167932                         10                      0         0   
167935                         10                      0         0   

        CHANGEOVER_DURATION  CLEANING_AND_SANITIZATION  \
160                       0                          0   
161                       0                          0   
163                       0                          0   
164                       0                          0   
167                       0                          0   
...                     ...                        ...   
167920                    0                          0   
167928                    0                          0   
167929                    0                      

In [10]:
df_unplanned["CO_TYPE"].unique()

array(['Material_Handle', 'Material_Filament', nan, 'Bundle_Material',
       'Tooling'], dtype=object)

In [11]:
df_unplanned["CO_TYPE"].value_counts()

CO_TYPE
Material_Handle      27422
Material_Filament    22422
Bundle_Material       3347
Tooling               1967
Name: count, dtype: int64

In [12]:
df_unplanned.isnull().sum()

PRODUCTIONDATE_DAY_LOC          0
SHIFT_NAME                      0
LINE_NAME                       0
CO_TYPE                      1678
CREW_ID                         0
AE_MODEL_CATEGORY               0
SIZE_TYPE                       0
SHIFT_NAME.1                    0
UTIL_REASON_DESCRIPTION         0
DOWNTIME                        0
EFFECTIVE_RUNTIME               0
GOOD_PRODUCTION_QTY             0
LUNCH_AND_BREAK                 0
MEETING_AND_TRAINING            0
NO_DEMAND                       0
PLANT_AVAILABLE_TIME            0
PLANT_EXPERIMENTATION           0
PRODUCTION_AVAILABLE_TIME       0
REJECT_PRODUCTION_QTY           0
RUN_TIME                        0
CHANGEOVER_DURATION             0
CLEANING_AND_SANITIZATION       0
BUSINESS_EXTERNAL_TIME          0
PLANNED_MAINTENANCE             0
TOTAL_TIME                      0
WAITING_TIME                    0
PRODUCTION_ORDER_RATE           0
dtype: int64

In [153]:
# Tạo dataframe mới với tổng thời gian DOWNTIME theo từng LINE_NAME
df_line_downtime = df_unplanned.groupby('LINE_NAME')['DOWNTIME'].sum().reset_index()
df_line_downtime.columns = ['LINE_NAME', 'TOTAL_DOWNTIME']
df_line_downtime = df_line_downtime.sort_values(by='TOTAL_DOWNTIME', ascending=False)
print(df_line_downtime)


   LINE_NAME  TOTAL_DOWNTIME
45  MKZA1501           48497
46  MKZA1502           47431
47  MKZA1601           44610
44  MKZA1402           41981
15  MKBC0202           40023
52  MKZA1802           37583
13  MKBC0102           36008
20  MKBC0501           35301
43  MKZA1401           34785
51  MKZA1801           34565
26  MKBC0901           33396
11  MHPT2307           29436
21  MKBC0502           29287
48  MKZA1602           28395
40  MKTU2004           27943
34  MKBC1301           27759
41  MKTU2005           27052
33  MKBC1202           26577
14  MKBC0201           26000
7   MHPT2303           25978
27  MKBC0902           25879
2   MAFT2203           25375
12  MKBC0101           25276
31  MKBC1102           24298
5   MHPT2301           23388
22  MKBC0601           22683
29  MKBC1002           22407
9   MHPT2305           21729
1   MAFT2202           21133
39  MKTU2003           21079
32  MKBC1201           20754
50  MKZA1702           20704
30  MKBC1101           20220
49  MKZA1701  

In [154]:
# Số lỗi của mỗi LINE_NAME
df_unplanned['LINE_NAME'].value_counts()

LINE_NAME
MKBC0901    2190
MKBC0202    1916
MKBC0902    1894
MKBC0102    1784
MHPT2307    1678
MKZA1501    1642
MHPT2303    1586
MKZA1502    1520
MHPT2301    1517
MKBC0502    1517
MHPT2305    1477
MKBC0501    1404
MHPT2304    1393
MKBC0101    1351
MKBC0201    1340
MHPT2302    1335
MKBC1102    1328
MKBC1002    1294
MKBC1202    1270
MKBC0302    1261
MKBC0601    1226
MHPT2306    1190
MKBC1101    1175
MKZA1401    1112
MKBC0301    1062
MKBC0602    1010
MKBC1301    1008
MKTU2004     949
MKZA1402     945
MKBC1201     906
MKTU2005     896
MKBC0702     888
MKZA1802     861
MKZA1601     855
MKTU2001     838
MKBC1001     794
MKTU2003     749
MKTU2002     740
MAFT2201     735
MKZA1801     732
MAFT2203     730
MKZA1602     725
MAFT2204     711
MKBC0701     674
MKZA1702     607
MKFX2101     605
MAFT2202     581
MKTU2006     549
MKZA1701     533
MAFT2205     504
MKBC0402     424
MKBC0401     422
MKFX2102     403
Name: count, dtype: int64

In [155]:
df_unplanned.describe()

PRODUCTIONDATE_DAY_LOC      DOWNTIME  EFFECTIVE_RUNTIME  \
count                          56836  56836.000000            56836.0   
mean   2025-03-31 23:24:54.573861376     22.376803                0.0   
min              2025-01-02 00:00:00      1.000000                0.0   
25%              2025-02-20 00:00:00     10.000000                0.0   
50%              2025-04-01 00:00:00     15.000000                0.0   
75%              2025-05-14 00:00:00     23.000000                0.0   
max              2025-06-30 00:00:00    480.000000                0.0   
std                              NaN     28.657690                0.0   

       GOOD_PRODUCTION_QTY  LUNCH_AND_BREAK  MEETING_AND_TRAINING  NO_DEMAND  \
count              56836.0          56836.0               56836.0    56836.0   
mean                   0.0              0.0                   0.0        0.0   
min                    0.0              0.0                   0.0        0.0   
25%                    0.0              0.0                   0.0        0.0   
50%                    0.0              0.0                   0.0        0.0   
75%                    0.0              0.0                   0.0        0.0   
max                    0.0              0.0                   0.0        0.0   
std                    0.0              0.0                   0.0        0.0   

       PLANT_AVAILABLE_TIME  PLANT_EXPERIMENTATION  PRODUCTION_AVAILABLE_TIME  \
count          56836.000000                56836.0               56836.000000   
mean              22.376803                    0.0                  22.376803   
min                1.000000                    0.0                   1.000000   
25%               10.000000                    0.0                  10.000000   
50%               15.000000                    0.0                  15.000000   
75%               23.000000                    0.0                  23.000000   
max              480.000000                    0.0                 480.000000   
std               28.657690                    0.0                  28.657690   

       REJECT_PRODUCTION_QTY  RUN_TIME  CHANGEOVER_DURATION  \
count                56836.0   56836.0              56836.0   
mean                     0.0       0.0                  0.0   
min                      0.0       0.0                  0.0   
25%                      0.0       0.0                  0.0   
50%                      0.0       0.0                  0.0   
75%                      0.0       0.0                  0.0   
max                      0.0       0.0                  0.0   
std                      0.0       0.0                  0.0   

       CLEANING_AND_SANITIZATION  BUSINESS_EXTERNAL_TIME  PLANNED_MAINTENANCE  \
count                    56836.0                 56836.0              56836.0   
mean                         0.0                     0.0                  0.0   
min                          0.0                     0.0                  0.0   
25%                          0.0                     0.0                  0.0   
50%                          0.0                     0.0                  0.0   
75%                          0.0                     0.0                  0.0   
max                          0.0                     0.0                  0.0   
std                          0.0                     0.0                  0.0   

         TOTAL_TIME  WAITING_TIME  PRODUCTION_ORDER_RATE  
count  56836.000000       56836.0           56836.000000  
mean      22.376803           0.0              65.216067  
min        1.000000           0.0              20.000000  
25%       10.000000           0.0              60.000000  
50%       15.000000           0.0              67.000000  
75%       23.000000           0.0              78.950000  
max      480.000000           0.0             172.000000  
std       28.657690           0.0              20.086924

GOOD_PRODUCTION_QTY = REJECT_PRODUCTION_QTY	-> Không có sản phẩm đầu ra

Ta thấy các giá trị thống kê của DOWNTIME = PLANT_AVAILABLE_TIME và RUNTIME = 0 (Máy không thực hiện sản xuất sản phẩm và không được vận hành)

In [156]:
df_unplanned['DOWNTIME'].equals(df_unplanned['PLANT_AVAILABLE_TIME'])

True

In [157]:
df_unplanned['PRODUCTION_AVAILABLE_TIME'].equals(df_unplanned['PLANT_AVAILABLE_TIME'])

True

In [158]:
df_unplanned["PRODUCTIONDATE_DAY_LOC"].value_counts()

PRODUCTIONDATE_DAY_LOC
2025-03-24    482
2025-02-20    476
2025-02-17    473
2025-05-14    473
2025-04-09    470
             ... 
2025-02-03    179
2025-02-09    121
2025-04-06    114
2025-01-19     66
2025-03-16     56
Name: count, Length: 153, dtype: int64

In [159]:
df_unplanned["LINE_NAME"].unique()

array(['MAFT2201', 'MAFT2202', 'MAFT2203', 'MHPT2301', 'MHPT2302',
       'MHPT2303', 'MHPT2304', 'MHPT2305', 'MHPT2306', 'MHPT2307',
       'MKBC0101', 'MKBC0102', 'MKBC0201', 'MKBC0202', 'MKBC0301',
       'MKBC0302', 'MKBC0402', 'MKBC0501', 'MKBC0502', 'MKBC0601',
       'MKBC0602', 'MKBC0701', 'MKBC0902', 'MKBC1001', 'MKBC1101',
       'MKBC1102', 'MKBC1201', 'MKBC1202', 'MKBC1301', 'MKFX2101',
       'MKTU2001', 'MKTU2002', 'MKTU2003', 'MKTU2004', 'MKTU2005',
       'MKTU2006', 'MKZA1401', 'MKZA1801', 'MKZA1802', 'MKBC0401',
       'MKBC0901', 'MKBC1002', 'MKZA1501', 'MKZA1601', 'MKBC0702',
       'MKFX2102', 'MKZA1701', 'MKZA1702', 'MKZA1502', 'MKZA1602',
       'MKZA1402', 'MAFT2205', 'MAFT2204'], dtype=object)

In [160]:
df_unplanned["SIZE_TYPE"].value_counts()

SIZE_TYPE
Total Defense Shield            9975
Classic Clean 100               7545
Deep Action White               4925
Total Action Model S            3836
EcoFresh Plus                   3622
Pro-Clean 5000                  3166
Super Soft Tech                 2862
Renew 360                       2757
PureMint Fresh                  1814
GreenClean Pro                  1729
Pro-Shield Complete             1520
Junior Sparkle (Ages 2+)        1435
ActiveClean Guard               1284
Super Soft Pro                  1134
Total Action Green              1023
Kids FunBrush (Tandy)            982
ActiveClean Model X              945
Defense Action Pro               936
Zenith Active                    919
Precision Grip 2.0               855
Classic White 110                775
Advanced Hydro-Clean             546
Oral Care 360                    504
Ocean Explorer (Ages 6+)         500
Zenith GreenClean                328
GreenClean Classic               249
Safari Explorer (Ages 6+)        223
EcoFresh Green                   202
Junior Guard Taper (Ages 5+)      87
EcoSoft Classic                   87
Zenith Classic Clean              52
GreenClean Ultra                  19
Name: count, dtype: int64

In [161]:
df_unplanned["UTIL_REASON_DESCRIPTION"].unique()

array(['12-Filling tool - 1201-Mechanical adjustment.',
       '07-FLS - 0701-Mechanical adjustment.',
       '09-In-feed conveyor - 0901-Mechanical adjustment.',
       '06-Fiber box - 0601-Mechanical adjustment.',
       '14-Fusing - 1401-Mechanical adjustment.',
       '03-Change material - 0301-Change material',
       '11-Segment - 1101-Mechanical adjustment.',
       '02-Quality - 0202-Rework',
       '18-Autofeeder - 1802-Stuck handle on chain',
       '10-Robot - 1002-Adjust mechanical of robot',
       '12-Filling tool - 1201-Cleaning Jaw',
       '06-Fiber box - 0602-Adjust sparepart',
       '18-Autofeeder - 1801-Double hadle on chain',
       '18-Autofeeder - 1806-Replace Robots mechanical',
       '27-Autosorter - 2701-Handle on chain stuck',
       '17-End Feeder - 1702-Jammed handle on chain',
       '11-Auto handle feederT2-1101-Double hadle on chain',
       '11-Auto handle feederT3-1101-Double hadle on chain',
       '11-Auto handle feederT1-1101-Double hadle on chain

In [162]:
df_unplanned["UTIL_REASON_DESCRIPTION"].value_counts()

UTIL_REASON_DESCRIPTION
17-End Feeder - 1702-Jammed handle on chain                             4093
02-Quality - 0202-Rework                                                3258
03-Change material - 0301-Change material                               3227
13-FM chain - 1306-Handle stuck on FM                                   3119
17-End Feeder - 1701-Double handle on chain                             2306
                                                                        ... 
14-Robot infeed - 1403-Wrong gripper                                       1
07-Anchor wire feedingT3-0701-Adjust/Replace mechanical parts of CAM       1
19-Vario Flow - 1901-Mechanical Vario Flow replacement                     1
10-In-feed Head Plate conveyor - 1003-Pneumatic cylinder adjustment        1
14-Fusing - 1406-Replace new electronic instruments                        1
Name: count, Length: 509, dtype: int64

In [163]:
# 1. Đếm tần suất xuất hiện của từng mô tả
desc_count = df_unplanned['UTIL_REASON_DESCRIPTION'].value_counts().reset_index()
desc_count.columns = ['Description', 'Count']

# 2. Tính phần trăm và phần trăm tích lũy
desc_count['Percent'] = desc_count['Count'] / desc_count['Count'].sum()
desc_count['CumulativePercent'] = desc_count['Percent'].cumsum()

# 3. Lọc các Description nằm trong 80% đầu tiên
top_80 = desc_count[desc_count['CumulativePercent'] <= 0.8]

# Hiển thị kết quả
print(top_80)
print("\nTổng số dòng trong 80% đầu tiên:", top_80['Count'].sum())
print("Tổng số dòng toàn bộ:", desc_count['Count'].sum())
print("Tỷ lệ bao phủ:", round(top_80['Count'].sum() / desc_count['Count'].sum() * 100, 2), "%")

                                          Description  Count   Percent  \
0         17-End Feeder - 1702-Jammed handle on chain   4093  0.072014   
1                            02-Quality - 0202-Rework   3258  0.057323   
2           03-Change material - 0301-Change material   3227  0.056777   
3               13-FM chain - 1306-Handle stuck on FM   3119  0.054877   
4         17-End Feeder - 1701-Double handle on chain   2306  0.040573   
..                                                ...    ...       ...   
56  12-TurretT2-1205-Adjust  handle supply box pos...    174  0.003061   
57    14-Fusing - 1407-Coordination/program adjusment    168  0.002956   
58            16-Coordination - 1604-Adjust parameter    164  0.002885   
59  11-Auto handle feeder - 1103-Adjust robot posi...    156  0.002745   
60  11-Auto handle feederT1-1106-Replace/adjust me...    155  0.002727   

    CumulativePercent  
0            0.072014  
1            0.129337  
2            0.186114  
3            0.

Ta thấy top80 discription khá rời rạc, không tập trung vào một mô tả cụ thể nào => Tách cấu trúc description thành từng phần để dễ đánh giá

In [171]:
# Tách thành các phần với cách làm linh hoạt
split_desc = df_unplanned['UTIL_REASON_DESCRIPTION'].str.split('-', n=3, expand=True)

# Tách phần ID
df_unplanned['ID'] = split_desc[0]

# Tách phần máy
df_unplanned['Machine_Name'] = split_desc[1]

# Tách mã lỗi
df_unplanned['Error_Code'] = split_desc[2]

# Tách mô tả lỗi chi tiết
df_unplanned['Error_Decrisption'] = split_desc[3]

/tmp/ipython-input-2253394959.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unplanned['ID'] = split_desc[0]
/tmp/ipython-input-2253394959.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unplanned['Machine_Name'] = split_desc[1]
/tmp/ipython-input-2253394959.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable

In [172]:
df_unplanned[['ID', 'Machine_Name', 'Error_Code', 'Error_Decrisption']].head()

ID   Machine_Name      Error_Code             Error_Decrisption
160  12  Filling tool             1201        Mechanical adjustment.
161  07           FLS             0701        Mechanical adjustment.
163  09             In  feed conveyor    0901-Mechanical adjustment.
164  06     Fiber box             0601        Mechanical adjustment.
167  14        Fusing             1401        Mechanical adjustment.

In [173]:
df_unplanned['ID'].value_counts()

ID
11    14564
17     8220
13     5220
03     3830
14     3822
06     3809
18     3391
02     3335
12     3138
16     2184
05     1404
10     1132
07      773
20      572
15      286
09      178
04      169
25      143
27      121
26       99
19       98
29       84
23       74
24       50
22       47
01       39
08       29
21       21
28        4
Name: count, dtype: int64

In [174]:
df_unplanned_11 = df_unplanned[df_unplanned['ID'] == '11']
df_unplanned_11

PRODUCTIONDATE_DAY_LOC   SHIFT_NAME LINE_NAME            CO_TYPE  \
170                2025-01-02  Afternoon-2  MAFT2202  Material_Filament   
252                2025-01-02  Afternoon-2  MKBC0102  Material_Filament   
253                2025-01-02  Afternoon-2  MKBC0102  Material_Filament   
256                2025-01-02  Afternoon-2  MKBC0102  Material_Filament   
270                2025-01-02  Afternoon-2  MKBC0202  Material_Filament   
...                       ...          ...       ...                ...   
167908             2025-06-30      Night-3  MKZA1401  Material_Filament   
167909             2025-06-30      Night-3  MKZA1401  Material_Filament   
167918             2025-06-30      Night-3  MKZA1501  Material_Filament   
167920             2025-06-30      Night-3  MKZA1501  Material_Filament   
167928             2025-06-30      Night-3  MKZA1502    Material_Handle   

       CREW_ID AE_MODEL_CATEGORY            SIZE_TYPE SHIFT_NAME.1  \
170          A         Unplanned            Renew 360  Afternoon-2   
252          A         Unplanned  Pro-Shield Complete  Afternoon-2   
253          A         Unplanned  Pro-Shield Complete  Afternoon-2   
256          A         Unplanned  Pro-Shield Complete  Afternoon-2   
270          A         Unplanned       Pro-Clean 5000  Afternoon-2   
...        ...               ...                  ...          ...   
167908       C         Unplanned    ActiveClean Guard      Night-3   
167909       C         Unplanned    ActiveClean Guard      Night-3   
167918       C         Unplanned       Super Soft Pro      Night-3   
167920       C         Unplanned       Super Soft Pro      Night-3   
167928       C         Unplanned       Super Soft Pro      Night-3   

                                  UTIL_REASON_DESCRIPTION  DOWNTIME  ...  \
170              11-Segment - 1101-Mechanical adjustment.         8  ...   
252     11-Auto handle feederT2-1101-Double hadle on c...        40  ...   
253     11-Auto handle feederT3-1101-Double hadle on c...        40  ...   
256     11-Auto handle feederT1-1101-Double hadle on c...        43  ...   
270     11-Auto handle feederT3-1103-Adjust robot posi...        10  ...   
...                                                   ...       ...  ...   
167908  11-Auto handle feederT3-1101-Double hadle on c...         9  ...   
167909  11-Auto handle feederT2-1102-Stuck handle on c...        10  ...   
167918  11-Auto handle feederT3-1102-Stuck handle on c...         6  ...   
167920  11-Auto handle feederT2-1102-Stuck handle on c...        10  ...   
167928  11-Auto handle feederT1-1102-Stuck handle on c...         9  ...   

        CLEANING_AND_SANITIZATION  BUSINESS_EXTERNAL_TIME  \
170                             0                       0   
252                             0                       0   
253                             0                       0   
256                             0                       0   
270                             0                       0   
...                           ...                     ...   
167908                          0                       0   
167909                          0                       0   
167918                          0                       0   
167920                          0                       0   
167928                          0                       0   

        PLANNED_MAINTENANCE  TOTAL_TIME  WAITING_TIME  PRODUCTION_ORDER_RATE  \
170                       0           8             0                  24.00   
252                       0          40             0                  81.40   
253                       0          40             0                  81.40   
256                       0          43             0                  81.40   
270                       0          10             0                  81.40   
...                     ...         ...           ...                    ...   
167908                    0           9             0      

In [184]:
import pandas as pd
from scipy.stats import chi2_contingency

df['IS_ERROR_11'] = 0

# Gán = 1 nếu bản ghi nằm trong df_unplanned_11 (cùng index)
df.loc[df.index.isin(df_unplanned_11.index), 'IS_ERROR_11'] = 1

def chi_square_test(df, column):
    contingency_table = pd.crosstab(df[column], df['IS_ERROR_11'])
    chi2, p, dof, expected = chi2_contingency(contingency_table)
    print(f"\n Yếu tố: {column}")
    print("Chi-square:", chi2)
    print("p-value:", p)
    if p < 0.05:
        print("Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 11")
    else:
        print("Kết luận: Không ảnh hưởng đáng kể")

# Chạy kiểm định:
for col in ['LINE_NAME', 'SIZE_TYPE', 'CREW_ID']:
    chi_square_test(df, col)



 Yếu tố: LINE_NAME
Chi-square: 8318.410371952386
p-value: 0.0
Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 11

 Yếu tố: SIZE_TYPE
Chi-square: 3384.0103193072055
p-value: 0.0
Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 11

 Yếu tố: CREW_ID
Chi-square: 164.9135346227804
p-value: 1.5469666854113143e-36
Kết luận: Có ảnh hưởng đáng kể đến lỗi ID = 11


DỰA VÀO GIÁ TRỊ CHI-SQUARE

Lỗi ID = 11 phụ thuộc mạnh nhất vào LINE_NAME, sau đó đến loại sản phẩm (SIZE_TYPE), và yếu nhất là đội/người vận hành (CREW_ID).

LINE_NAME đang là nguyên nhân chính gây ra lỗi ID = 11.

In [188]:
df_unplanned_11["LINE_NAME"].value_counts()

LINE_NAME
MKBC0901    1033
MKBC0102     933
MKBC0902     735
MKBC0502     688
MKBC0302     610
MKBC0202     607
MKBC1002     585
MKBC0601     517
MKBC0101     499
MKBC1301     431
MKBC0301     417
MKBC0602     412
MKBC0702     397
MKBC1202     395
MKBC1102     387
MKZA1402     369
MKTU2003     366
MKTU2004     358
MKBC1101     350
MKTU2001     343
MKBC1001     342
MKTU2005     331
MKTU2002     312
MKBC0701     267
MKZA1401     261
MKTU2006     254
MKZA1501     241
MKZA1802     240
MKZA1502     227
MKBC0501     220
MKBC1201     215
MKZA1702     190
MKBC0201     190
MKZA1801     182
MKZA1701     141
MKBC0402     105
MKBC0401      86
MKZA1601      81
MKZA1602      72
MAFT2203      23
MHPT2307      22
MHPT2303      20
MHPT2306      18
MAFT2204      17
MHPT2305      13
MAFT2205      12
MHPT2301      12
MHPT2302      11
MHPT2304       9
MAFT2202       8
MKFX2101       6
MAFT2201       3
MKFX2102       1
Name: count, dtype: int64

## CO_TYPE == NULL

In [13]:
df_unplanned_null = df_unplanned[df_unplanned["CO_TYPE"].isnull()] # thông tin về loại hoạt động bị thiếu
df_unplanned_null

PRODUCTIONDATE_DAY_LOC   SHIFT_NAME LINE_NAME CO_TYPE CREW_ID  \
233                2025-01-02  Afternoon-2  MHPT2307     NaN       A   
235                2025-01-02  Afternoon-2  MHPT2307     NaN       A   
236                2025-01-02  Afternoon-2  MHPT2307     NaN       A   
239                2025-01-02  Afternoon-2  MHPT2307     NaN       A   
607                2025-01-02        Day-1  MHPT2307     NaN       C   
...                       ...          ...       ...     ...     ...   
167376             2025-06-30        Day-1  MHPT2307     NaN       A   
167378             2025-06-30        Day-1  MHPT2307     NaN       A   
167691             2025-06-30      Night-3  MHPT2307     NaN       C   
167693             2025-06-30      Night-3  MHPT2307     NaN       C   
167697             2025-06-30      Night-3  MHPT2307     NaN       C   

       AE_MODEL_CATEGORY             SIZE_TYPE SHIFT_NAME.1  \
233            Unplanned  Total Defense Shield  Afternoon-2   
235            Unplanned  Total Defense Shield  Afternoon-2   
236            Unplanned  Total Defense Shield  Afternoon-2   
239            Unplanned  Total Defense Shield  Afternoon-2   
607            Unplanned  Total Defense Shield        Day-1   
...                  ...                   ...          ...   
167376         Unplanned  Total Defense Shield        Day-1   
167378         Unplanned  Total Defense Shield        Day-1   
167691         Unplanned  Total Defense Shield      Night-3   
167693         Unplanned  Total Defense Shield      Night-3   
167697         Unplanned  Total Defense Shield      Night-3   

                                 UTIL_REASON_DESCRIPTION  DOWNTIME  ...  \
233       18-Autofeeder - 1806-Replace Robots mechanical        10  ...   
235            03-Change material - 0301-Change material        10  ...   
236           27-Autosorter - 2701-Handle on chain stuck        17  ...   
239                 06-Fiber box - 0602-Adjust sparepart         5  ...   
607                 06-Fiber box - 0602-Adjust sparepart        10  ...   
...                                                  ...       ...  ...   
167376         03-Change material - 0301-Change material         4  ...   
167378    07-Anchor wire feeding - 0705-Sensor is broken        60  ...   
167691         03-Change material - 0301-Change material        10  ...   
167693  23-Endrounding station - 2302-Replace mechanical        18  ...   
167697        18-Autofeeder - 1802-Stuck handle on chain         8  ...   

        PRODUCTION_AVAILABLE_TIME  REJECT_PRODUCTION_QTY  RUN_TIME  \
233                            10                      0         0   
235                            10                      0         0   
236                            17                      0         0   
239                             5                      0         0   
607                            10                      0         0   
...                           ...                    ...       ...   
167376                          4                      0         0   
167378                         60                      0         0   
167691                         10                      0         0   
167693                         18                      0         0   
167697                          8                      0         0   

        CHANGEOVER_DURATION  CLEANING_AND_SANITIZATION  \
233                       0                          0   
235                       0                          0   
236                       0                          0   
239                       0                          0   
607                       0                          0   
...                     ...                        ...   
167376                    0                          0   
167378                    0                          0   
167691                    0                          0   
167693                    0                          0   
16769

In [14]:
df_unplanned_null.describe()

PRODUCTIONDATE_DAY_LOC     DOWNTIME  EFFECTIVE_RUNTIME  \
count                           1678  1678.000000             1678.0   
mean   2025-04-04 10:29:02.073897472    17.542312                0.0   
min              2025-01-02 00:00:00     1.000000                0.0   
25%              2025-02-27 00:00:00     8.000000                0.0   
50%              2025-04-04 12:00:00    10.000000                0.0   
75%              2025-05-14 00:00:00    20.000000                0.0   
max              2025-06-30 00:00:00   371.000000                0.0   
std                              NaN    22.893944                0.0   

       GOOD_PRODUCTION_QTY  LUNCH_AND_BREAK  MEETING_AND_TRAINING  NO_DEMAND  \
count               1678.0           1678.0                1678.0     1678.0   
mean                   0.0              0.0                   0.0        0.0   
min                    0.0              0.0                   0.0        0.0   
25%                    0.0              0.0                   0.0        0.0   
50%                    0.0              0.0                   0.0        0.0   
75%                    0.0              0.0                   0.0        0.0   
max                    0.0              0.0                   0.0        0.0   
std                    0.0              0.0                   0.0        0.0   

       PLANT_AVAILABLE_TIME  PLANT_EXPERIMENTATION  PRODUCTION_AVAILABLE_TIME  \
count           1678.000000                 1678.0                1678.000000   
mean              17.542312                    0.0                  17.542312   
min                1.000000                    0.0                   1.000000   
25%                8.000000                    0.0                   8.000000   
50%               10.000000                    0.0                  10.000000   
75%               20.000000                    0.0                  20.000000   
max              371.000000                    0.0                 371.000000   
std               22.893944                    0.0                  22.893944   

       REJECT_PRODUCTION_QTY  RUN_TIME  CHANGEOVER_DURATION  \
count                 1678.0    1678.0               1678.0   
mean                     0.0       0.0                  0.0   
min                      0.0       0.0                  0.0   
25%                      0.0       0.0                  0.0   
50%                      0.0       0.0                  0.0   
75%                      0.0       0.0                  0.0   
max                      0.0       0.0                  0.0   
std                      0.0       0.0                  0.0   

       CLEANING_AND_SANITIZATION  BUSINESS_EXTERNAL_TIME  PLANNED_MAINTENANCE  \
count                     1678.0                  1678.0               1678.0   
mean                         0.0                     0.0                  0.0   
min                          0.0                     0.0                  0.0   
25%                          0.0                     0.0                  0.0   
50%                          0.0                     0.0                  0.0   
75%                          0.0                     0.0                  0.0   
max                          0.0                     0.0                  0.0   
std                          0.0                     0.0                  0.0   

        TOTAL_TIME  WAITING_TIME  PRODUCTION_ORDER_RATE  
count  1678.000000        1678.0            1678.000000  
mean     17.542312           0.0              63.272920  
min       1.000000           0.0              63.160000  
25%       8.000000           0.0              63.160000  
50%      10.000000           0.0              63.160000  
75%      20.000000           0.0              63.160000  
max     371.000000           0.0             126.320000  
std      22.893944           0.0               2.668994

Ta thấy các giá trị thống kê của DOWNTIME = PLANT_AVAILABLE_TIME và RUNTIME = 0 (nghi ngờ máy được thiết lập chương trình nhưng không chạy)

In [15]:
df_unplanned_null['DOWNTIME'].equals(df_unplanned_null['PLANT_AVAILABLE_TIME'])

True

In [16]:
df_unplanned_null['PRODUCTION_AVAILABLE_TIME'].equals(df_unplanned_null['PLANT_AVAILABLE_TIME'])

True

In [17]:
df_unplanned_null["PRODUCTIONDATE_DAY_LOC"].value_counts()

PRODUCTIONDATE_DAY_LOC
2025-03-03    19
2025-03-14    18
2025-03-13    18
2025-05-08    18
2025-04-28    17
              ..
2025-04-14     5
2025-01-13     4
2025-01-16     4
2025-02-09     4
2025-01-24     2
Name: count, Length: 151, dtype: int64

In [18]:
df_unplanned_null["LINE_NAME"].value_counts()

LINE_NAME
MHPT2307    1678
Name: count, dtype: int64

In [19]:
df_unplanned_null["UTIL_REASON_DESCRIPTION"].unique()

array(['18-Autofeeder - 1806-Replace Robots mechanical',
       '03-Change material - 0301-Change material',
       '27-Autosorter - 2701-Handle on chain stuck',
       '06-Fiber box - 0602-Adjust sparepart',
       '18-Autofeeder - 1802-Stuck handle on chain',
       '18-Autofeeder - 1801-Double hadle on chain',
       '18-Autofeeder - 1803-Adjust robot position',
       '06-Fiber box - 0601-Sparepart broken',
       '13-Fiber picker  - 1301-Adjust gap of fiber picker and picker guide',
       '13-Fiber picker  - 1302-Mechanical error',
       '13-Fiber picker  - 1304-Adjust position of fiber picker',
       '06-Fiber box - 0604-Adjust robot position',
       '07-Anchor wire feeding - 0705-Sensor is broken',
       '20-Filament loading - 2002-Replace mechanical',
       '20-Filament loading - 2005-Clean sparepart',
       '10-Robot - 1001-Adjust robot location',
       '22-Trimming Unit - 2202-Replace mechanical',
       '22-Trimming Unit - 2203-Adjusting height',
       '12-Filling t

In [20]:
df_unplanned_null["UTIL_REASON_DESCRIPTION"].value_counts()

UTIL_REASON_DESCRIPTION
03-Change material - 0301-Change material           353
18-Autofeeder - 1802-Stuck handle on chain          285
06-Fiber box - 0602-Adjust sparepart                207
18-Autofeeder - 1801-Double hadle on chain          122
12-Filling tool - 1201-Cleaning Jaw                  95
                                                   ... 
24-Dust Collector - 2401-Replace mechanical           1
20-Filament loading - 2001-Adjust robot position      1
12-Filling tool - 1204-Replace sparepart              1
13-Fiber picker  - 1303-Welding picker eye            1
25-FM Chain - 2504-Replace sparepart of FM chain      1
Name: count, Length: 76, dtype: int64

In [21]:
df_unplanned_null["SIZE_TYPE"].value_counts()

SIZE_TYPE
Total Defense Shield    1678
Name: count, dtype: int64

In [22]:
df_unplanned_null["GOOD_PRODUCTION_QTY"].value_counts()

GOOD_PRODUCTION_QTY
0    1678
Name: count, dtype: int64

In [23]:
df_unplanned_null["REJECT_PRODUCTION_QTY"].value_counts()

REJECT_PRODUCTION_QTY
0    1678
Name: count, dtype: int64

In [24]:
# 1. Đếm tần suất xuất hiện của từng mô tả
desc_count = df_unplanned_null['UTIL_REASON_DESCRIPTION'].value_counts().reset_index()
desc_count.columns = ['Description', 'Count']

# 2. Tính phần trăm và phần trăm tích lũy
desc_count['Percent'] = desc_count['Count'] / desc_count['Count'].sum()
desc_count['CumulativePercent'] = desc_count['Percent'].cumsum()

# 3. Lọc các Description nằm trong 80% đầu tiên
top_80 = desc_count[desc_count['CumulativePercent'] <= 0.8]

# Hiển thị kết quả
print(top_80)
print("\nTổng số dòng trong 80% đầu tiên:", top_80['Count'].sum())
print("Tổng số dòng toàn bộ:", desc_count['Count'].sum())
print("Tỷ lệ bao phủ:", round(top_80['Count'].sum() / desc_count['Count'].sum() * 100, 2), "%")

                                         Description  Count   Percent  \
0          03-Change material - 0301-Change material    353  0.210369   
1         18-Autofeeder - 1802-Stuck handle on chain    285  0.169845   
2               06-Fiber box - 0602-Adjust sparepart    207  0.123361   
3         18-Autofeeder - 1801-Double hadle on chain    122  0.072706   
4                12-Filling tool - 1201-Cleaning Jaw     95  0.056615   
5   03-Change material - 0302-Unplanned Change Fiber     66  0.039333   
6              10-Robot - 1001-Adjust robot location     51  0.030393   
7         10-Robot - 1002-Adjust mechanical of robot     48  0.028605   
8               06-Fiber box - 0601-Sparepart broken     40  0.023838   
9          06-Fiber box - 0604-Adjust robot position     35  0.020858   
10        27-Autosorter - 2701-Handle on chain stuck     30  0.017878   

    CumulativePercent  
0            0.210369  
1            0.380215  
2            0.503576  
3            0.576281  
4  

1. Các mô tả xuất hiện nhiều nhất chiếm tỷ lệ lớn tổng số sự cố

Nhóm mô tả đứng đầu như:

- 03-Change material - 0301-Change material (353 lần – 21.04%)

- 18-Autofeeder - 1802-Stuck handle on chain (285 lần – 16.98%)

- 06-Fiber box - 0602-Adjust sparepart (207 lần – 12.33%)

=> Chỉ riêng top 3 nguyên nhân đã chiếm gần 50% tổng số sự cố, cho thấy một số vấn đề mang tính lặp lại, có thể cải tiến hoặc chuẩn hoá quy trình để giảm tần suất.

2. Các mô tả liên quan đến thay đổi nguyên liệu (Change material) xuất hiện nhiều

Các mã:

- 0301-Change material (353 lần)

- 302-Unplanned Change Fiber (66 lần)

=> Tổng cộng hơn 419/1677 = 25% tổng số sự cố, cho thấy quá trình thay đổi nguyên liệu hoặc chuẩn bị nguyên liệu đang có vấn đề hoặc chưa được chuẩn hóa.(SIZE_TYPE = Total Defense Shield)

3. Các lỗi lặp lại trong cùng một cụm thiết bị

- Autofeeder, Robot, Fiber box đều có nhiều mô tả lỗi nhỏ nhưng lặp đi lặp lại (stuck, adjust, cleaning).

- Điều này phản ánh thiết bị hoạt động lâu ngày cần bảo trì định kỳ, hoặc thao tác của nhân viên chưa chuẩn.

4. Trường hợp PLANT_AVAILABLE_TIME = PRODUCTION_AVAILABLE_TIME = DOWNTIME và RUNTIME = 0

- Cho thấy máy đã được thiết lập chạy nhưng thực tế không hoạt động (runtime = 0).

- Điều này phù hợp với nhận định: Máy đang trong trạng thái chờ hoặc gặp sự cố ngay sau khi bắt đầu chạy -> được ghi nhận là unplanned

## CO_TYPE == Material_Handle

*Material_Handle: Thay đổi hoặc xử lý vật liệu tay cầm.
Thời gian dành cho việc thay đổi lô, nạp, hoặc xử lý các vấn đề liên quan đến tay cầm (handle) của bàn chải đánh răng. Đây cũng là một hoạt động chuyển đổi sản xuất quan trọng.*


In [25]:
df_unplanned_mh = df_unplanned[df_unplanned['CO_TYPE'] == "Material_Handle"]
df_unplanned_mh

PRODUCTIONDATE_DAY_LOC   SHIFT_NAME LINE_NAME          CO_TYPE CREW_ID  \
160                2025-01-02  Afternoon-2  MAFT2201  Material_Handle       A   
161                2025-01-02  Afternoon-2  MAFT2201  Material_Handle       A   
163                2025-01-02  Afternoon-2  MAFT2201  Material_Handle       A   
164                2025-01-02  Afternoon-2  MAFT2201  Material_Handle       A   
167                2025-01-02  Afternoon-2  MAFT2201  Material_Handle       A   
...                       ...          ...       ...              ...     ...   
167898             2025-06-30      Night-3  MKTU2006  Material_Handle       C   
167928             2025-06-30      Night-3  MKZA1502  Material_Handle       C   
167929             2025-06-30      Night-3  MKZA1502  Material_Handle       C   
167932             2025-06-30      Night-3  MKZA1502  Material_Handle       C   
167935             2025-06-30      Night-3  MKZA1502  Material_Handle       C   

       AE_MODEL_CATEGORY         SIZE_TYPE SHIFT_NAME.1  \
160            Unplanned         Renew 360  Afternoon-2   
161            Unplanned         Renew 360  Afternoon-2   
163            Unplanned         Renew 360  Afternoon-2   
164            Unplanned         Renew 360  Afternoon-2   
167            Unplanned         Renew 360  Afternoon-2   
...                  ...               ...          ...   
167898         Unplanned  GreenClean Ultra      Night-3   
167928         Unplanned    Super Soft Pro      Night-3   
167929         Unplanned    Super Soft Pro      Night-3   
167932         Unplanned    Super Soft Pro      Night-3   
167935         Unplanned    Super Soft Pro      Night-3   

                                  UTIL_REASON_DESCRIPTION  DOWNTIME  ...  \
160         12-Filling tool - 1201-Mechanical adjustment.        17  ...   
161                  07-FLS - 0701-Mechanical adjustment.        12  ...   
163     09-In-feed conveyor - 0901-Mechanical adjustment.        13  ...   
164            06-Fiber box - 0601-Mechanical adjustment.        10  ...   
167               14-Fusing - 1401-Mechanical adjustment.        18  ...   
...                                                   ...       ...  ...   
167898  14-Fiber picker   - 1401-Adjust gap of fiber p...        15  ...   
167928  11-Auto handle feederT1-1102-Stuck handle on c...         9  ...   
167929  13-Filling toolT1-1306-Replace/adjust mechanic...        40  ...   
167932  06-Fiber boxT2-0602-Replace/adjust mechanical ...        10  ...   
167935                   13-Filling toolT2-1303-Clean jaw        10  ...   

        PRODUCTION_AVAILABLE_TIME  REJECT_PRODUCTION_QTY  RUN_TIME  \
160                            17                      0         0   
161                            12                      0         0   
163                            13                      0         0   
164                            10                      0         0   
167                            18                      0         0   
...                           ...                    ...       ...   
167898                         15                      0         0   
167928                          9                      0         0   
167929                         40                      0         0   
167932                         10                      0         0   
167935                         10                      0         0   

        CHANGEOVER_DURATION  CLEANING_AND_SANITIZATION  \
160                       0                          0   
161                       0                          0   
163                       0                          0   
164                       0                          0   
167                       0                          0   
...                     ...                        ...   
167898                    0                          0   
167928                    0                          0   
167929                    0                      

In [26]:
df_unplanned_mh.describe()

PRODUCTIONDATE_DAY_LOC      DOWNTIME  EFFECTIVE_RUNTIME  \
count                          27422  27422.000000            27422.0   
mean   2025-04-01 19:19:19.215228928     25.101524                0.0   
min              2025-01-02 00:00:00      1.000000                0.0   
25%              2025-02-20 00:00:00     10.000000                0.0   
50%              2025-04-01 00:00:00     15.000000                0.0   
75%              2025-05-16 00:00:00     27.000000                0.0   
max              2025-06-30 00:00:00    480.000000                0.0   
std                              NaN     32.963557                0.0   

       GOOD_PRODUCTION_QTY  LUNCH_AND_BREAK  MEETING_AND_TRAINING  NO_DEMAND  \
count              27422.0          27422.0               27422.0    27422.0   
mean                   0.0              0.0                   0.0        0.0   
min                    0.0              0.0                   0.0        0.0   
25%                    0.0              0.0                   0.0        0.0   
50%                    0.0              0.0                   0.0        0.0   
75%                    0.0              0.0                   0.0        0.0   
max                    0.0              0.0                   0.0        0.0   
std                    0.0              0.0                   0.0        0.0   

       PLANT_AVAILABLE_TIME  PLANT_EXPERIMENTATION  PRODUCTION_AVAILABLE_TIME  \
count          27422.000000                27422.0               27422.000000   
mean              25.101524                    0.0                  25.101524   
min                1.000000                    0.0                   1.000000   
25%               10.000000                    0.0                  10.000000   
50%               15.000000                    0.0                  15.000000   
75%               27.000000                    0.0                  27.000000   
max              480.000000                    0.0                 480.000000   
std               32.963557                    0.0                  32.963557   

       REJECT_PRODUCTION_QTY  RUN_TIME  CHANGEOVER_DURATION  \
count                27422.0   27422.0              27422.0   
mean                     0.0       0.0                  0.0   
min                      0.0       0.0                  0.0   
25%                      0.0       0.0                  0.0   
50%                      0.0       0.0                  0.0   
75%                      0.0       0.0                  0.0   
max                      0.0       0.0                  0.0   
std                      0.0       0.0                  0.0   

       CLEANING_AND_SANITIZATION  BUSINESS_EXTERNAL_TIME  PLANNED_MAINTENANCE  \
count                    27422.0                 27422.0              27422.0   
mean                         0.0                     0.0                  0.0   
min                          0.0                     0.0                  0.0   
25%                          0.0                     0.0                  0.0   
50%                          0.0                     0.0                  0.0   
75%                          0.0                     0.0                  0.0   
max                          0.0                     0.0                  0.0   
std                          0.0                     0.0                  0.0   

         TOTAL_TIME  WAITING_TIME  PRODUCTION_ORDER_RATE  
count  27422.000000       27422.0           27422.000000  
mean      25.101524           0.0              57.374400  
min        1.000000           0.0              20.000000  
25%       10.000000           0.0              27.140000  
50%       15.000000           0.0              63.800000  
75%       27.000000           0.0              78.950000  
max      480.000000           0.0             172.000000  
std       32.963557           0.0              22.890787

GOOD_PRODUCTION_QTY = REJECT_PRODUCTION_QTY	-> Không có sản phẩm đầu ra

Ta thấy các giá trị thống kê của DOWNTIME = PLANT_AVAILABLE_TIME và RUNTIME = 0 (Máy không thực hiện sản xuất sản phẩm và không được vận hành)

In [27]:
df_unplanned_mh['DOWNTIME'].equals(df_unplanned_mh['PLANT_AVAILABLE_TIME'])

True

In [28]:
df_unplanned_mh['PRODUCTION_AVAILABLE_TIME'].equals(df_unplanned_mh['PLANT_AVAILABLE_TIME'])

True

In [29]:
df_unplanned_mh["PRODUCTIONDATE_DAY_LOC"].value_counts()

PRODUCTIONDATE_DAY_LOC
2025-05-15    249
2025-03-24    248
2025-05-14    241
2025-03-20    240
2025-05-27    238
             ... 
2025-02-03     79
2025-02-09     65
2025-04-06     33
2025-01-19     20
2025-03-16     10
Name: count, Length: 153, dtype: int64

In [30]:
df_unplanned_mh["LINE_NAME"].unique()

array(['MAFT2201', 'MAFT2203', 'MHPT2301', 'MHPT2302', 'MHPT2303',
       'MKBC0101', 'MKBC0201', 'MKBC0302', 'MKBC0501', 'MKBC0502',
       'MKBC0701', 'MKBC1001', 'MKBC1102', 'MKBC1202', 'MKBC1301',
       'MKTU2001', 'MKTU2002', 'MKTU2003', 'MKTU2004', 'MKTU2006',
       'MKZA1801', 'MKZA1802', 'MKTU2005', 'MKZA1601', 'MAFT2202',
       'MKZA1701', 'MKZA1702', 'MKZA1602', 'MKZA1401', 'MKZA1402',
       'MAFT2205', 'MAFT2204', 'MKBC1002', 'MKZA1501', 'MKZA1502',
       'MKBC1201', 'MKBC0702', 'MKBC0902'], dtype=object)

In [31]:
df_unplanned_mh["LINE_NAME"].value_counts()

LINE_NAME
MHPT2303    1586
MHPT2301    1517
MHPT2302    1335
MKBC0201    1260
MKBC1102    1222
MKBC0101    1066
MKZA1402     945
MKBC1301     923
MKZA1501     894
MKBC0502     875
MKZA1802     861
MKZA1601     855
MKZA1502     820
MKTU2001     757
MKTU2004     754
MKTU2005     730
MKZA1602     725
MKBC1001     716
MKZA1801     678
MKBC0701     674
MKBC1202     635
MKBC0302     614
MKZA1702     607
MAFT2203     606
MAFT2201     586
MAFT2204     586
MKTU2002     573
MKTU2003     552
MKBC0702     521
MAFT2205     493
MAFT2202     463
MKTU2006     439
MKBC0902     387
MKBC0501     382
MKBC1201     358
MKZA1401     275
MKBC1002     109
MKZA1701      43
Name: count, dtype: int64

In [32]:
df_unplanned_mh["SIZE_TYPE"].value_counts()

SIZE_TYPE
Deep Action White               4760
Total Action Model S            3701
EcoFresh Plus                   3327
Renew 360                       2241
GreenClean Pro                  1635
Super Soft Tech                 1609
PureMint Fresh                  1523
Junior Sparkle (Ages 2+)        1362
ActiveClean Model X              945
Total Action Green               904
Defense Action Pro               901
Precision Grip 2.0               855
Super Soft Pro                   824
Kids FunBrush (Tandy)            735
Advanced Hydro-Clean             503
Oral Care 360                    493
Ocean Explorer (Ages 6+)         449
GreenClean Classic               185
EcoFresh Green                   162
Safari Explorer (Ages 6+)        155
EcoSoft Classic                   81
Junior Guard Taper (Ages 5+)      62
GreenClean Ultra                  10
Name: count, dtype: int64

In [33]:
df_unplanned_mh["UTIL_REASON_DESCRIPTION"].unique()

array(['12-Filling tool - 1201-Mechanical adjustment.',
       '07-FLS - 0701-Mechanical adjustment.',
       '09-In-feed conveyor - 0901-Mechanical adjustment.',
       '06-Fiber box - 0601-Mechanical adjustment.',
       '14-Fusing - 1401-Mechanical adjustment.',
       '03-Change material - 0301-Change material',
       '02-Quality - 0202-Rework',
       '18-Autofeeder - 1802-Stuck handle on chain',
       '10-Robot - 1002-Adjust mechanical of robot',
       '12-Filling tool - 1201-Cleaning Jaw',
       '17-End Feeder - 1702-Jammed handle on chain',
       '14-Robot infeed - 1402-Adjust robot postion',
       '13-FM chain - 1306-Handle stuck on FM',
       '13-FM chain - 1302-Replace details of clamping replacement',
       '11-Auto handle feederT3-1102-Stuck handle on chain',
       '11-Auto handle feederT2-1102-Stuck handle on chain',
       '14-Fiber picker  T1-1401-Adjust gap of fiber picker and picker guide',
       '18-Main shaftT1-1802-Adjust date code stamp position',
      

In [34]:
df_unplanned_mh["UTIL_REASON_DESCRIPTION"].value_counts()

UTIL_REASON_DESCRIPTION
02-Quality - 0202-Rework                                                   2218
03-Change material - 0301-Change material                                  1569
17-End Feeder - 1702-Jammed handle on chain                                1557
17-End Feeder - 1701-Double handle on chain                                1027
13-FM chain - 1306-Handle stuck on FM                                      1006
                                                                           ... 
10-Mechanical - 1005-Screw losen                                              1
11-Auto handle feeder - 1110-replace electric tools in electric box           1
05-LaborT3-0506-Training/ meeting out of plan                                 1
16-CoordinationT3-1603-Replace/adjust mechanical detail of coordination       1
01-Safety - 0101-Safety                                                       1
Name: count, Length: 460, dtype: int64

In [35]:
# 1. Đếm tần suất xuất hiện của từng mô tả
desc_count = df_unplanned_mh['UTIL_REASON_DESCRIPTION'].value_counts().reset_index()
desc_count.columns = ['Description', 'Count']

# 2. Tính phần trăm và phần trăm tích lũy
desc_count['Percent'] = desc_count['Count'] / desc_count['Count'].sum()
desc_count['CumulativePercent'] = desc_count['Percent'].cumsum()

# 3. Lọc các Description nằm trong 80% đầu tiên
top_80 = desc_count[desc_count['CumulativePercent'] <= 0.8]

# Hiển thị kết quả
print(top_80)
print("\nTổng số dòng trong 80% đầu tiên:", top_80['Count'].sum())
print("Tổng số dòng toàn bộ:", desc_count['Count'].sum())
print("Tỷ lệ bao phủ:", round(top_80['Count'].sum() / desc_count['Count'].sum() * 100, 2), "%")

                                          Description  Count   Percent  \
0                            02-Quality - 0202-Rework   2218  0.080884   
1           03-Change material - 0301-Change material   1569  0.057217   
2         17-End Feeder - 1702-Jammed handle on chain   1557  0.056779   
3         17-End Feeder - 1701-Double handle on chain   1027  0.037452   
4               13-FM chain - 1306-Handle stuck on FM   1006  0.036686   
5   11-Auto handle feederT1-1101-Double hadle on c...    907  0.033076   
6   11-Auto handle feederT2-1101-Double hadle on c...    805  0.029356   
7          18-Autofeeder - 1802-Stuck handle on chain    798  0.029101   
8   11-Auto handle feederT3-1101-Double hadle on c...    759  0.027679   
9   11-Auto handle feeder - 1101-Double hadle on c...    665  0.024251   
10               06-Fiber box - 0602-Adjust sparepart    608  0.022172   
11  11-Auto handle feederT2-1102-Stuck handle on c...    605  0.022063   
12  11-Auto handle feeder - 1102-Stuck

Ta thấy top80 discription khá rời rạc, không tập trung vào một mô tả cụ thể nào => Tách cấu trúc description thành từng phần để dễ đánh giá

In [36]:
# Tách thành các phần với cách làm linh hoạt
split_desc = df_unplanned_mh['UTIL_REASON_DESCRIPTION'].str.split('-', n=3, expand=True)

# Tách phần máy (Machine / Line)
df_unplanned_mh['Machine_Area'] = split_desc[0] + '-' + split_desc[1]

# Tách mã lỗi (Error Code)
df_unplanned_mh['Error_Code'] = split_desc[2]

# Tách mô tả lỗi chi tiết
df_unplanned_mh['Error_Decrisption'] = split_desc[3]

/tmp/ipython-input-2759090501.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unplanned_mh['Machine_Area'] = split_desc[0] + '-' + split_desc[1]
/tmp/ipython-input-2759090501.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unplanned_mh['Error_Code'] = split_desc[2]
/tmp/ipython-input-2759090501.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://

In [37]:
df_unplanned_mh[['Machine_Area', 'Error_Code', 'Error_Decrisption']].head()

Machine_Area      Error_Code             Error_Decrisption
160  12-Filling tool             1201        Mechanical adjustment.
161           07-FLS             0701        Mechanical adjustment.
163             09-In  feed conveyor    0901-Mechanical adjustment.
164     06-Fiber box             0601        Mechanical adjustment.
167        14-Fusing             1401        Mechanical adjustment.

In [38]:
df_unplanned_mh['Machine_Area'].value_counts()

Machine_Area
17-End Feeder              3334
02-Quality                 2237
11-Auto handle feederT1    1751
11-Auto handle feederT2    1742
03-Change material         1683
                           ... 
17-Main shaft                 2
17-Main shaftT1               2
28-Compressor air             1
01-SafetyT2                   1
03-Material changingT2        1
Name: count, Length: 111, dtype: int64

In [109]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

tfidf = TfidfVectorizer(stop_words='english')
vec = tfidf.fit_transform(df_unplanned_mh['Error_Decrisption'])  # phần mô tả chi tiết sau split

In [40]:
from sklearn.metrics import silhouette_score

scores = []
for k in range(2, 16):
    kmeans = KMeans(n_clusters=k, random_state=42)
    labels = kmeans.fit_predict(vec)
    score = silhouette_score(vec, labels)
    scores.append((k, score))
    print(f"k={k}, Silhouette Score={score}")

k=2, Silhouette Score=0.16593223786049197
k=3, Silhouette Score=0.23249807114652615
k=4, Silhouette Score=0.27899107859414046
k=5, Silhouette Score=0.3671129764066935
k=6, Silhouette Score=0.44000425646272884
k=7, Silhouette Score=0.4123124262916528
k=8, Silhouette Score=0.47332781668368434
k=9, Silhouette Score=0.5310329045204975
k=10, Silhouette Score=0.5511132869441165
k=11, Silhouette Score=0.5633203089914102
k=12, Silhouette Score=0.5698270698632434
k=13, Silhouette Score=0.6087210496403722
k=14, Silhouette Score=0.6109320096418622
k=15, Silhouette Score=0.6408248707856885


In [110]:
kmeans = KMeans(n_clusters=15, random_state=42)
df_unplanned_mh['cluster'] = kmeans.fit_predict(vec)

/tmp/ipython-input-1750626387.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unplanned_mh['cluster'] = kmeans.fit_predict(vec)


In [111]:
for i in range(15):
    print(f"\n------ Cluster {i} ------")
    sample = df_unplanned_mh[df_unplanned_mh['cluster'] == i]['Error_Decrisption'].head(10)
    print(sample.to_string(index=False))


------ Cluster 0 ------
Double hadle on chain
Double hadle on chain
Double hadle on chain
Double hadle on chain
Double hadle on chain
Double hadle on chain
Double hadle on chain
Double hadle on chain
Double hadle on chain
Double hadle on chain

------ Cluster 1 ------
Stuck handle on chain
Stuck handle on chain
   Handle stuck on FM
   Handle stuck on FM
Stuck handle on chain
Stuck handle on chain
   Handle stuck on FM
Stuck handle on chain
   Handle stuck on FM
   Handle stuck on FM

------ Cluster 2 ------
 Replace/adjust mechanical parts of fiber beaters
       Replace mechanical details of fiber picker
 Replace/adjust mechanical parts of fiber beaters
 Replace/adjust mechanical parts of fiber beaters
                   Replace/adjust parts of turret
       Replace mechanical details of fiber picker
 Replace/adjust mechanical parts of fiber beaters
                   Replace/adjust parts of turret
Replace/adjust mechanical details of Filling tool
                   Replace/adjust p

In [112]:
# Dictionary: cluster_id -> tên mô tả lỗi
cluster_labels = {
    0: "Double handle on chain",
    1: "Handle stuck / FM stuck",
    2: "Replace or adjust mechanical parts",
    3: "Material change",
    4: "Rework",
    5: "Mechanical adjustment",
    6: "Robot / Welding / Conveyor adjustment",
    7: "Cleaning mechanical parts",
    8: "Jammed handle on chain",
    9: "Adjust sparepart / parameters",
    10: "Lack of handle on chain",
    11: "Cleaning feeder/mechanical system",
    12: "Double handle on chain",
    13: "Adjust printing/logo/supply box position",
    14: "Adjust fiber picker gap/position"
}
# Gán tên cluster dựa trên dictionary
df_unplanned_mh['cluster_label'] = df_unplanned_mh['cluster'].map(cluster_labels)

# Kiểm tra kết quả
df_unplanned_mh[['Error_Decrisption', 'cluster', 'cluster_label']].head(20)


/tmp/ipython-input-336728146.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unplanned_mh['cluster_label'] = df_unplanned_mh['cluster'].map(cluster_labels)


Error_Decrisption  cluster  \
160        Mechanical adjustment.        5   
161        Mechanical adjustment.        5   
163   0901-Mechanical adjustment.        5   
164        Mechanical adjustment.        5   
167        Mechanical adjustment.        5   
168               Change material        3   
179        Mechanical adjustment.        5   
183        Mechanical adjustment.        5   
184        Mechanical adjustment.        5   
186                        Rework        4   
191               Change material        3   
192         Stuck handle on chain        1   
193    Adjust mechanical of robot        6   
195                  Cleaning Jaw        7   
198               Change material        3   
201                  Cleaning Jaw        7   
206    Adjust mechanical of robot        6   
208         Stuck handle on chain        1   
210               Change material        3   
250        Jammed handle on chain        8   

                             cluster_label  
160                  Mechanical adjustment  
161                  Mechanical adjustment  
163                  Mechanical adjustment  
164                  Mechanical adjustment  
167                  Mechanical adjustment  
168                        Material change  
179                  Mechanical adjustment  
183                  Mechanical adjustment  
184                  Mechanical adjustment  
186                                 Rework  
191                        Material change  
192                Handle stuck / FM stuck  
193  Robot / Welding / Conveyor adjustment  
195              Cleaning mechanical parts  
198                        Material change  
201              Cleaning mechanical parts  
206  Robot / Welding / Conveyor adjustment  
208                Handle stuck / FM stuck  
210                        Material change  
250                 Jammed handle on chain

In [113]:
df_unplanned_mh['cluster_label'].value_counts()

cluster_label
Handle stuck / FM stuck                     4664
Double handle on chain                      4441
Robot / Welding / Conveyor adjustment       4239
Rework                                      2218
Replace or adjust mechanical parts          2060
Mechanical adjustment                       1858
Material change                             1837
Jammed handle on chain                      1675
Adjust sparepart / parameters               1088
Adjust fiber picker gap/position            1077
Cleaning mechanical parts                    625
Lack of handle on chain                      595
Cleaning feeder/mechanical system            580
Adjust printing/logo/supply box position     465
Name: count, dtype: int64

In [45]:
def detect_anomaly_full(df, cluster_name, group_col, top_n=5):
    df_cluster = df[df['cluster_label'] == cluster_name]
    counts = df_cluster[group_col].value_counts()
    percent = df_cluster[group_col].value_counts(normalize=True) * 100

    result = pd.DataFrame({
        'count': counts,
        'percent (%)': percent
    }).head(top_n)

    return result

In [46]:
for cluster in df_unplanned_mh['cluster_label'].unique():
    print(f"\n======  Cluster: {cluster} ======")
    anomaly_line = detect_anomaly_full(df_unplanned_mh, cluster, "LINE_NAME")
    anomaly_crew = detect_anomaly_full(df_unplanned_mh, cluster, "CREW_ID")
    anomaly_size = detect_anomaly_full(df_unplanned_mh, cluster, "SIZE_TYPE")

    print("\n➡ Top 5 LINE_NAME bất thường:")
    print(anomaly_line)

    print("\n➡ Top 5 CREW_ID bất thường:")
    print(anomaly_crew)

    print("\n➡ Top 5 SIZE_TYPE bất thường:")
    print(anomaly_size)


======  Cluster: Mechanical adjustment ======

➡ Top 5 LINE_NAME bất thường:
           count  percent (%)
LINE_NAME                    
MAFT2201     360    19.375673
MAFT2204     349    18.783638
MAFT2203     337    18.137783
MAFT2205     301    16.200215
MAFT2202     270    14.531755

➡ Top 5 CREW_ID bất thường:
         count  percent (%)
CREW_ID                    
A          662    35.629709
B          600    32.292788
C          596    32.077503

➡ Top 5 SIZE_TYPE bất thường:
                       count  percent (%)
SIZE_TYPE                                
Renew 360               1316    70.828848
Oral Care 360            301    16.200215
EcoFresh Plus             69     3.713671
Kids FunBrush (Tandy)     33     1.776103
Precision Grip 2.0        29     1.560818

======  Cluster: Material change ======

➡ Top 5 LINE_NAME bất thường:
           count  percent (%)
LINE_NAME                    
MHPT2303     429    23.353293
MHPT2301     404    21.992379
MHPT2302     395    21.502

In [116]:
def detect_high_impact_low_frequency(df, error_col='Error_Type', downtime_col='DOWNTIME'):
    # Tổng toàn bộ lỗi và downtime
    total_errors = df.shape[0]
    total_downtime = df[downtime_col].sum()

    # Gom nhóm theo từng loại lỗi
    summary = df.groupby(error_col).agg(
        error_count=(error_col, 'count'),
        total_downtime=(downtime_col, 'sum')
    )

    # Tính % lỗi và % downtime
    summary['error_percent'] = summary['error_count'] / total_errors * 100
    summary['downtime_percent'] = summary['total_downtime'] / total_downtime * 100

    # Lọc lỗi xuất hiện ít (<30%) nhưng gây downtime lớn (>70%)
    result = summary[(summary['error_percent'] < 30) & (summary['downtime_percent'] > 70)]

    return summary.sort_values(by='downtime_percent', ascending=False), result

# Nếu cột lỗi của bạn tên là "cluster_label"
summary, high_impact_errors = detect_high_impact_low_frequency(
    df_unplanned_mh, error_col='cluster_label', downtime_col='DOWNTIME'
)

print("Tổng quan lỗi & downtime theo từng loại:")
print(summary)

print("\nLỖI ÍT NHƯNG GÂY ẢNH HƯỞNG LỚN:")
print(high_impact_errors if not high_impact_errors.empty else "Không tìm thấy loại lỗi nào thuộc dạng này.")


Tổng quan lỗi & downtime theo từng loại:
                                          error_count  total_downtime  \
cluster_label                                                           
Rework                                           2218          193792   
Robot / Welding / Conveyor adjustment            4239          119882   
Handle stuck / FM stuck                          4664           66423   
Double handle on chain                           4441           64065   
Mechanical adjustment                            1858           51762   
Replace or adjust mechanical parts               2060           49053   
Jammed handle on chain                           1675           31491   
Adjust sparepart / parameters                    1088           27617   
Adjust fiber picker gap/position                 1077           27216   
Material change                                  1837           15526   
Adjust printing/logo/supply box position          465           12589   
Lack of ha

## CO_TYPE == Material_Filament

Thay đổi hoặc xử lý vật liệu sợi (lông bàn chải). Thời gian dành cho việc thay đổi cuộn, nạp, hoặc xử lý các vấn đề liên quan đến sợi nhựa (filament) dùng để làm lông bàn chải đánh răng. Đây là một hoạt động chuyển đổi sản xuất quan trọng (changeover)

In [47]:
df_unplanned_mf = df_unplanned[df_unplanned['CO_TYPE'] == "Material_Filament"]
df_unplanned_mf

PRODUCTIONDATE_DAY_LOC   SHIFT_NAME LINE_NAME            CO_TYPE  \
170                2025-01-02  Afternoon-2  MAFT2202  Material_Filament   
171                2025-01-02  Afternoon-2  MAFT2202  Material_Filament   
174                2025-01-02  Afternoon-2  MAFT2202  Material_Filament   
177                2025-01-02  Afternoon-2  MAFT2202  Material_Filament   
213                2025-01-02  Afternoon-2  MHPT2304  Material_Filament   
...                       ...          ...       ...                ...   
167908             2025-06-30      Night-3  MKZA1401  Material_Filament   
167909             2025-06-30      Night-3  MKZA1401  Material_Filament   
167916             2025-06-30      Night-3  MKZA1501  Material_Filament   
167918             2025-06-30      Night-3  MKZA1501  Material_Filament   
167920             2025-06-30      Night-3  MKZA1501  Material_Filament   

       CREW_ID AE_MODEL_CATEGORY             SIZE_TYPE SHIFT_NAME.1  \
170          A         Unplanned             Renew 360  Afternoon-2   
171          A         Unplanned             Renew 360  Afternoon-2   
174          A         Unplanned             Renew 360  Afternoon-2   
177          A         Unplanned             Renew 360  Afternoon-2   
213          A         Unplanned  Total Defense Shield  Afternoon-2   
...        ...               ...                   ...          ...   
167908       C         Unplanned     ActiveClean Guard      Night-3   
167909       C         Unplanned     ActiveClean Guard      Night-3   
167916       C         Unplanned        Super Soft Pro      Night-3   
167918       C         Unplanned        Super Soft Pro      Night-3   
167920       C         Unplanned        Super Soft Pro      Night-3   

                                  UTIL_REASON_DESCRIPTION  DOWNTIME  ...  \
170              11-Segment - 1101-Mechanical adjustment.         8  ...   
171            06-Fiber box - 0601-Mechanical adjustment.        12  ...   
174         12-Filling tool - 1201-Mechanical adjustment.        53  ...   
177               14-Fusing - 1401-Mechanical adjustment.        27  ...   
213            18-Autofeeder - 1802-Stuck handle on chain        30  ...   
...                                                   ...       ...  ...   
167908  11-Auto handle feederT3-1101-Double hadle on c...         9  ...   
167909  11-Auto handle feederT2-1102-Stuck handle on c...        10  ...   
167916         16-Autosorter - 1601-Handle on chain stuck         5  ...   
167918  11-Auto handle feederT3-1102-Stuck handle on c...         6  ...   
167920  11-Auto handle feederT2-1102-Stuck handle on c...        10  ...   

        PRODUCTION_AVAILABLE_TIME  REJECT_PRODUCTION_QTY  RUN_TIME  \
170                             8                      0         0   
171                            12                      0         0   
174                            53                      0         0   
177                            27                      0         0   
213                            30                      0         0   
...                           ...                    ...       ...   
167908                          9                      0         0   
167909                         10                      0         0   
167916                          5                      0         0   
167918                          6                      0         0   
167920                         10                      0         0   

        CHANGEOVER_DURATION  CLEANING_AND_SANITIZATION  \
170                       0                          0   
171                       0                          0   
174                       0                          0   
177                       0                          0   
213                       0                          0   
...                     ...                        ...   
167908                    0                          0   
167909                    0        

In [48]:
df_unplanned_mf.describe()

PRODUCTIONDATE_DAY_LOC      DOWNTIME  EFFECTIVE_RUNTIME  \
count                          22422  22422.000000            22422.0   
mean   2025-03-31 07:22:56.612255744     19.485996                0.0   
min              2025-01-02 00:00:00      1.000000                0.0   
25%              2025-02-18 00:00:00     10.000000                0.0   
50%              2025-04-01 00:00:00     14.000000                0.0   
75%              2025-05-14 00:00:00     20.000000                0.0   
max              2025-06-30 00:00:00    448.000000                0.0   
std                              NaN     23.129411                0.0   

       GOOD_PRODUCTION_QTY  LUNCH_AND_BREAK  MEETING_AND_TRAINING  NO_DEMAND  \
count              22422.0          22422.0               22422.0    22422.0   
mean                   0.0              0.0                   0.0        0.0   
min                    0.0              0.0                   0.0        0.0   
25%                    0.0              0.0                   0.0        0.0   
50%                    0.0              0.0                   0.0        0.0   
75%                    0.0              0.0                   0.0        0.0   
max                    0.0              0.0                   0.0        0.0   
std                    0.0              0.0                   0.0        0.0   

       PLANT_AVAILABLE_TIME  PLANT_EXPERIMENTATION  PRODUCTION_AVAILABLE_TIME  \
count          22422.000000                22422.0               22422.000000   
mean              19.485996                    0.0                  19.485996   
min                1.000000                    0.0                   1.000000   
25%               10.000000                    0.0                  10.000000   
50%               14.000000                    0.0                  14.000000   
75%               20.000000                    0.0                  20.000000   
max              448.000000                    0.0                 448.000000   
std               23.129411                    0.0                  23.129411   

       REJECT_PRODUCTION_QTY  RUN_TIME  CHANGEOVER_DURATION  \
count                22422.0   22422.0              22422.0   
mean                     0.0       0.0                  0.0   
min                      0.0       0.0                  0.0   
25%                      0.0       0.0                  0.0   
50%                      0.0       0.0                  0.0   
75%                      0.0       0.0                  0.0   
max                      0.0       0.0                  0.0   
std                      0.0       0.0                  0.0   

       CLEANING_AND_SANITIZATION  BUSINESS_EXTERNAL_TIME  PLANNED_MAINTENANCE  \
count                    22422.0                 22422.0              22422.0   
mean                         0.0                     0.0                  0.0   
min                          0.0                     0.0                  0.0   
25%                          0.0                     0.0                  0.0   
50%                          0.0                     0.0                  0.0   
75%                          0.0                     0.0                  0.0   
max                          0.0                     0.0                  0.0   
std                          0.0                     0.0                  0.0   

         TOTAL_TIME  WAITING_TIME  PRODUCTION_ORDER_RATE  
count  22422.000000       22422.0           22422.000000  
mean      19.485996           0.0              74.465032  
min        1.000000           0.0              24.000000  
25%       10.000000           0.0              67.000000  
50%       14.000000           0.0              78.900000  
75%       20.000000           0.0              81.400000  
max      448.000000           0.0             162.860000  
std       23.129411           0.0              11.739951

GOOD_PRODUCTION_QTY = REJECT_PRODUCTION_QTY	-> Không có sản phẩm đầu ra

Ta thấy các giá trị thống kê của DOWNTIME = PLANT_AVAILABLE_TIME và RUNTIME = 0 (Máy không thực hiện sản xuất sản phẩm và không được vận hành)

In [49]:
df_unplanned_mf['DOWNTIME'].equals(df_unplanned_mf['PLANT_AVAILABLE_TIME'])

True

In [50]:
df_unplanned_mf['PRODUCTION_AVAILABLE_TIME'].equals(df_unplanned_mf['PLANT_AVAILABLE_TIME'])

True

In [51]:
df_unplanned_mf["PRODUCTIONDATE_DAY_LOC"].value_counts()

PRODUCTIONDATE_DAY_LOC
2025-03-11    217
2025-02-20    216
2025-01-09    213
2025-04-21    205
2025-05-12    201
             ... 
2025-02-03     82
2025-02-09     52
2025-04-06     47
2025-01-19     38
2025-03-16     20
Name: count, Length: 153, dtype: int64

In [52]:
df_unplanned_mf["LINE_NAME"].unique()

array(['MAFT2202', 'MHPT2304', 'MHPT2305', 'MHPT2306', 'MKBC0102',
       'MKBC0202', 'MKBC0301', 'MKBC0402', 'MKBC0601', 'MKBC0602',
       'MKBC0902', 'MKBC1201', 'MKFX2101', 'MKBC0302', 'MKBC0401',
       'MKBC0901', 'MKBC0502', 'MKBC1002', 'MKZA1401', 'MKBC1101',
       'MKBC0702', 'MKFX2102', 'MKBC1102', 'MKBC1202', 'MKBC0201',
       'MKBC0501', 'MKTU2005', 'MKZA1501', 'MAFT2203', 'MAFT2201',
       'MKZA1801', 'MAFT2204', 'MKZA1502', 'MKZA1701', 'MAFT2205',
       'MKTU2003', 'MKTU2006', 'MKTU2004'], dtype=object)

In [53]:
df_unplanned_mf["LINE_NAME"].value_counts()

LINE_NAME
MKBC0202    1902
MKBC0102    1694
MKBC0901    1691
MHPT2304    1393
MKBC0902    1280
MKBC0601    1226
MHPT2306    1190
MKBC1101    1159
MKBC1002    1111
MKBC0602    1010
MKBC0501     973
MKBC0301     920
MKZA1401     685
MKZA1501     623
MKFX2101     605
MHPT2305     472
MKBC0302     470
MKBC0502     470
MKZA1701     445
MKZA1502     424
MKBC0402     417
MKFX2102     403
MKBC0401     324
MKBC1201     253
MKBC0702     204
MAFT2201     149
MAFT2204     125
MAFT2203     124
MAFT2202     118
MKBC1102     106
MKBC0201      80
MKTU2005      75
MKTU2003      70
MKTU2004      67
MKBC1202      54
MKZA1801      54
MKTU2006      45
MAFT2205      11
Name: count, dtype: int64

In [54]:
df_unplanned_mf["SIZE_TYPE"].value_counts()

SIZE_TYPE
Classic Clean 100       6822
Total Defense Shield    6761
Pro-Clean 5000          3089
Pro-Shield Complete     1470
ActiveClean Guard       1013
Super Soft Tech          955
Zenith Active            911
Renew 360                516
EcoFresh Plus            263
Zenith GreenClean        257
Super Soft Pro           251
Total Action Model S      64
Zenith Classic Clean      39
Oral Care 360             11
Name: count, dtype: int64

In [55]:
df_unplanned_mf["UTIL_REASON_DESCRIPTION"].unique()

array(['11-Segment - 1101-Mechanical adjustment.',
       '06-Fiber box - 0601-Mechanical adjustment.',
       '12-Filling tool - 1201-Mechanical adjustment.',
       '14-Fusing - 1401-Mechanical adjustment.',
       '18-Autofeeder - 1802-Stuck handle on chain',
       '06-Fiber box - 0602-Adjust sparepart',
       '03-Change material - 0301-Change material',
       '18-Autofeeder - 1801-Double hadle on chain',
       '11-Auto handle feederT2-1101-Double hadle on chain',
       '11-Auto handle feederT3-1101-Double hadle on chain',
       '11-Auto handle feederT1-1101-Double hadle on chain',
       '11-Auto handle feederT3-1103-Adjust robot position',
       '11-Auto handle feederT1-1102-Stuck handle on chain',
       '17-End Feeder - 1702-Jammed handle on chain',
       '11-Auto handle feederT3-1102-Stuck handle on chain',
       '02-Quality - 0202-Rework',
       '14-Fiber picker  T1-1401-Adjust gap of fiber picker and picker guide',
       '13-FM chain - 1306-Handle stuck on FM',
   

In [56]:
df_unplanned_mf["UTIL_REASON_DESCRIPTION"].value_counts()

UTIL_REASON_DESCRIPTION
17-End Feeder - 1702-Jammed handle on chain                            2180
13-FM chain - 1306-Handle stuck on FM                                  1745
17-End Feeder - 1701-Double handle on chain                            1087
03-Change material - 0301-Change material                              1052
11-Auto handle feederT1-1101-Double hadle on chain                      972
                                                                       ... 
09-Compressor airT3-0901-Replace details of valve/air pipe                1
01-SafetyT1-0105-Interlock broken                                         1
17-Main shaftT1-1703-screw losen on main shaft                            1
10-In-feed Head Plate conveyor - 1003-Pneumatic cylinder adjustment       1
14-Fusing - 1406-Replace new electronic instruments                       1
Name: count, Length: 404, dtype: int64

In [57]:
# 1. Đếm tần suất xuất hiện của từng mô tả
desc_count = df_unplanned_mf['UTIL_REASON_DESCRIPTION'].value_counts().reset_index()
desc_count.columns = ['Description', 'Count']

# 2. Tính phần trăm và phần trăm tích lũy
desc_count['Percent'] = desc_count['Count'] / desc_count['Count'].sum()
desc_count['CumulativePercent'] = desc_count['Percent'].cumsum()

# 3. Lọc các Description nằm trong 80% đầu tiên
top_80 = desc_count[desc_count['CumulativePercent'] <= 0.8]

# Hiển thị kết quả
print(top_80)
print("\nTổng số dòng trong 80% đầu tiên:", top_80['Count'].sum())
print("Tổng số dòng toàn bộ:", desc_count['Count'].sum())
print("Tỷ lệ bao phủ:", round(top_80['Count'].sum() / desc_count['Count'].sum() * 100, 2), "%")

                                          Description  Count   Percent  \
0         17-End Feeder - 1702-Jammed handle on chain   2180  0.097226   
1               13-FM chain - 1306-Handle stuck on FM   1745  0.077825   
2         17-End Feeder - 1701-Double handle on chain   1087  0.048479   
3           03-Change material - 0301-Change material   1052  0.046918   
4   11-Auto handle feederT1-1101-Double hadle on c...    972  0.043350   
5                            02-Quality - 0202-Rework    760  0.033895   
6   11-Auto handle feederT1-1102-Stuck handle on c...    733  0.032691   
7   11-Auto handle feederT2-1102-Stuck handle on c...    716  0.031933   
8   11-Auto handle feederT3-1102-Stuck handle on c...    705  0.031442   
9   11-Auto handle feederT2-1101-Double hadle on c...    697  0.031086   
10  11-Auto handle feederT3-1101-Double hadle on c...    696  0.031041   
11         18-Autofeeder - 1802-Stuck handle on chain    663  0.029569   
12               06-Fiber box - 0602-A

Ta thấy top80 discription khá rời rạc, không tập trung vào một mô tả cụ thể nào => Tách cấu trúc description thành từng phần để dễ đánh giá

In [58]:
# Tách thành các phần với cách làm linh hoạt
split_desc = df_unplanned_mf['UTIL_REASON_DESCRIPTION'].str.split('-', n=3, expand=True)

# Tách phần máy (Machine / Line)
df_unplanned_mf['Machine_Area'] = split_desc[0] + '-' + split_desc[1]

# Tách mã lỗi (Error Code)
df_unplanned_mf['Error_Code'] = split_desc[2]

# Tách mô tả lỗi chi tiết
df_unplanned_mf['Error_Decrisption'] = split_desc[3]

/tmp/ipython-input-1998834879.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unplanned_mf['Machine_Area'] = split_desc[0] + '-' + split_desc[1]
/tmp/ipython-input-1998834879.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unplanned_mf['Error_Code'] = split_desc[2]
/tmp/ipython-input-1998834879.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://

In [59]:
df_unplanned_mf[['Machine_Area', 'Error_Code', 'Error_Decrisption']].head()

Machine_Area Error_Code       Error_Decrisption
170       11-Segment        1101  Mechanical adjustment.
171     06-Fiber box        0601  Mechanical adjustment.
174  12-Filling tool        1201  Mechanical adjustment.
177        14-Fusing        1401  Mechanical adjustment.
213    18-Autofeeder        1802   Stuck handle on chain

In [60]:
df_unplanned_mf['Machine_Area'].value_counts()

Machine_Area
17-End Feeder              4175
11-Auto handle feederT1    2269
11-Auto handle feederT3    2066
13-FM chain                2042
11-Auto handle feederT2    1912
                           ... 
06-Fiber box                  1
09-Compressor airT3           1
17-Main shaft                 1
08-ProcessT1                  1
08-ProcessT3                  1
Name: count, Length: 111, dtype: int64

In [123]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

tfidf = TfidfVectorizer(stop_words='english')
vec = tfidf.fit_transform(df_unplanned_mf['Error_Decrisption'])  # phần mô tả chi tiết sau split

In [62]:
from sklearn.metrics import silhouette_score

scores = []
for k in range(2, 16):
    kmeans = KMeans(n_clusters=k, random_state=42)
    labels = kmeans.fit_predict(vec)
    score = silhouette_score(vec, labels)
    scores.append((k, score))
    print(f"k={k}, Silhouette Score={score}")


k=2, Silhouette Score=0.19011343875370562
k=3, Silhouette Score=0.2836117737739569
k=4, Silhouette Score=0.31732449852309486
k=5, Silhouette Score=0.40196600210672545
k=6, Silhouette Score=0.4159947635374536
k=7, Silhouette Score=0.459123332345809
k=8, Silhouette Score=0.40874668773259354
k=9, Silhouette Score=0.43235071089875204
k=10, Silhouette Score=0.5081993877823927
k=11, Silhouette Score=0.6300228469423097
k=12, Silhouette Score=0.633057518731845
k=13, Silhouette Score=0.6633766725383091
k=14, Silhouette Score=0.6686670872451386
k=15, Silhouette Score=0.694636603058939


In [124]:
kmeans = KMeans(n_clusters=15, random_state=42)
df_unplanned_mf['cluster'] = kmeans.fit_predict(vec)

/tmp/ipython-input-917532335.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unplanned_mf['cluster'] = kmeans.fit_predict(vec)


In [125]:
for i in range(15):  # vì n_clusters = 15
    print(f"\n------ Cluster {i} ------")
    sample = df_unplanned_mf[df_unplanned_mf['cluster'] == i]['Error_Decrisption'].head(10)
    print(sample.to_string(index=False))


------ Cluster 0 ------
Double handle on chain
Double handle on chain
Double handle on chain
Double handle on chain
Double handle on chain
Double handle on chain
Double handle on chain
Double handle on chain
Double handle on chain
Double handle on chain

------ Cluster 1 ------
Stuck handle on chain
Stuck handle on chain
Stuck handle on chain
Stuck handle on chain
Stuck handle on chain
Stuck handle on chain
Stuck handle on chain
Stuck handle on chain
Stuck handle on chain
Stuck handle on chain

------ Cluster 2 ------
Adjust sparepart
Adjust sparepart
Sparepart broken
Adjust sparepart
Adjust sparepart
Sparepart broken
Adjust parameter
Adjust sparepart
Adjust parameter
Adjust sparepart

------ Cluster 3 ------
Replace/adjust mechanical details of Filling tool
          Replace details of clamping replacement
           Replace details of Endrounding station
                Replace details of dust collector
Replace/adjust mechanical details of Filling tool
  Replace/adjust mechanical de

In [126]:
# Dictionary: cluster_id -> tên mô tả lỗi
cluster_labels = {
    0: "Double handle on chain",
    1: "Stuck handle on chain",
    2: "Adjust sparepart",
    3: "Replace/adjust mechanical parts",
    4: "Mechanical adjustment",
    5: "Change material",
    6: "Repair laser / Jam conveyor / Lack of handle",
    7: "Adjust welding parameters",
    8: "Double handle on chain",
    9: "Handle stuck on FM",
    10: "Jammed handle on chain",
    11: "Adjust fiber picker gap / position",
    12: "Rework",
    13: "Replace/adjust mechanical parts",
    14: "Adjust robot position"
}
# Gán tên cluster dựa trên dictionary
df_unplanned_mf['cluster_label'] = df_unplanned_mf['cluster'].map(cluster_labels)

# Kiểm tra kết quả
df_unplanned_mf[['Error_Decrisption', 'cluster', 'cluster_label']].head(20)


/tmp/ipython-input-2360377372.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unplanned_mf['cluster_label'] = df_unplanned_mf['cluster'].map(cluster_labels)


Error_Decrisption  cluster           cluster_label
170  Mechanical adjustment.        4   Mechanical adjustment
171  Mechanical adjustment.        4   Mechanical adjustment
174  Mechanical adjustment.        4   Mechanical adjustment
177  Mechanical adjustment.        4   Mechanical adjustment
213   Stuck handle on chain        1   Stuck handle on chain
214        Adjust sparepart        2        Adjust sparepart
218         Change material        5         Change material
219        Adjust sparepart        2        Adjust sparepart
223         Change material        5         Change material
224   Double hadle on chain        8  Double handle on chain
226   Stuck handle on chain        1   Stuck handle on chain
230         Change material        5         Change material
252   Double hadle on chain        8  Double handle on chain
253   Double hadle on chain        8  Double handle on chain
256   Double hadle on chain        8  Double handle on chain
270   Adjust robot position       14   Adjust robot position
273   Stuck handle on chain        1   Stuck handle on chain
277  Jammed handle on chain       10  Jammed handle on chain
278   Stuck handle on chain        1   Stuck handle on chain
281                  Rework       12                  Rework

In [127]:
df_unplanned_mf['cluster_label'].value_counts()

cluster_label
Double handle on chain                          3723
Repair laser / Jam conveyor / Lack of handle    3533
Stuck handle on chain                           3257
Jammed handle on chain                          2180
Replace/adjust mechanical parts                 2163
Handle stuck on FM                              1766
Adjust robot position                           1286
Adjust sparepart                                1197
Change material                                 1107
Adjust fiber picker gap / position               774
Rework                                           760
Mechanical adjustment                            616
Adjust welding parameters                         60
Name: count, dtype: int64

In [67]:
def detect_anomaly_full(df, cluster_name, group_col, top_n=5):
    df_cluster = df[df['cluster_label'] == cluster_name]
    counts = df_cluster[group_col].value_counts()
    percent = df_cluster[group_col].value_counts(normalize=True) * 100

    result = pd.DataFrame({
        'count': counts,
        'percent (%)': percent
    }).head(top_n)

    return result

In [68]:
for cluster in df_unplanned_mf['cluster_label'].unique():
    print(f"\n======  Cluster: {cluster} ======")
    anomaly_line = detect_anomaly_full(df_unplanned_mf, cluster, "LINE_NAME")
    anomaly_crew = detect_anomaly_full(df_unplanned_mf, cluster, "CREW_ID")
    anomaly_size = detect_anomaly_full(df_unplanned_mf, cluster, "SIZE_TYPE")

    print("\n➡ Top 5 LINE_NAME bất thường:")
    print(anomaly_line)

    print("\n➡ Top 5 CREW_ID bất thường:")
    print(anomaly_crew)

    print("\n➡ Top 5 SIZE_TYPE bất thường:")
    print(anomaly_size)


======  Cluster: Mechanical adjustment ======

➡ Top 5 LINE_NAME bất thường:
           count  percent (%)
LINE_NAME                    
MAFT2201      91    14.772727
MAFT2203      73    11.850649
MAFT2202      70    11.363636
MAFT2204      68    11.038961
MKBC0202      66    10.714286

➡ Top 5 CREW_ID bất thường:
         count  percent (%)
CREW_ID                    
C          239    38.798701
A          217    35.227273
B          160    25.974026

➡ Top 5 SIZE_TYPE bất thường:
                      count  percent (%)
SIZE_TYPE                               
Renew 360               302    49.025974
Classic Clean 100        94    15.259740
Pro-Clean 5000           87    14.123377
Total Defense Shield     56     9.090909
Pro-Shield Complete      26     4.220779

======  Cluster: Stuck handle on chain ======

➡ Top 5 LINE_NAME bất thường:
           count  percent (%)
LINE_NAME                    
MKBC0901     454    13.939208
MKBC0202     353    10.838195
MKBC0902     236     7.2459

In [122]:
def detect_high_impact_low_frequency(df, error_col='Error_Type', downtime_col='DOWNTIME'):
    # Tổng toàn bộ lỗi và downtime
    total_errors = df.shape[0]
    total_downtime = df[downtime_col].sum()

    # Gom nhóm theo từng loại lỗi
    summary = df.groupby(error_col).agg(
        error_count=(error_col, 'count'),
        total_downtime=(downtime_col, 'sum')
    )

    # Tính % lỗi và % downtime
    summary['error_percent'] = summary['error_count'] / total_errors * 100
    summary['downtime_percent'] = summary['total_downtime'] / total_downtime * 100

    # Lọc lỗi xuất hiện ít (<30%) nhưng gây downtime lớn (>70%)
    result = summary[(summary['error_percent'] < 30) & (summary['downtime_percent'] > 70)]

    return summary.sort_values(by='downtime_percent', ascending=False), result

# Nếu cột lỗi của bạn tên là "cluster_label"
summary, high_impact_errors = detect_high_impact_low_frequency(
    df_unplanned_mf, error_col='cluster_label', downtime_col='DOWNTIME'
)

print("Tổng quan lỗi & downtime theo từng loại:")
print(summary)

print("\nLỖI ÍT NHƯNG GÂY ẢNH HƯỞNG LỚN:")
print(high_impact_errors if not high_impact_errors.empty else "Không tìm thấy loại lỗi nào thuộc dạng này.")


Tổng quan lỗi & downtime theo từng loại:
                                              error_count  total_downtime  \
cluster_label                                                               
Repair laser / Jam conveyor / Lack of handle         3533           79475   
Rework                                                760           65026   
Double handle on chain                               3723           51471   
Replace/adjust mechanical parts                      2163           46433   
Jammed handle on chain                               2180           41281   
Stuck handle on chain                                3257           35910   
Adjust robot position                                1286           27842   
Handle stuck on FM                                   1766           26733   
Adjust sparepart                                     1197           21184   
Mechanical adjustment                                 616           18396   
Adjust fiber picker gap / position 

## CO_TYPE == Bundle_Material

Thay đổi hoặc xử lý vật liệu đóng gói/bó. Thời gian dành cho việc xử lý các vấn đề hoặc thay đổi nguyên liệu liên quan đến việc bó (bundle) hoặc đóng gói sản phẩm cuối cùng


In [69]:
df_unplanned_bm = df_unplanned[df_unplanned['CO_TYPE'] == "Bundle_Material"]
df_unplanned_bm

PRODUCTIONDATE_DAY_LOC   SHIFT_NAME LINE_NAME          CO_TYPE CREW_ID  \
386                2025-01-02  Afternoon-2  MKBC1101  Bundle_Material       A   
387                2025-01-02  Afternoon-2  MKBC1101  Bundle_Material       A   
389                2025-01-02  Afternoon-2  MKBC1101  Bundle_Material       A   
392                2025-01-02  Afternoon-2  MKBC1101  Bundle_Material       A   
393                2025-01-02  Afternoon-2  MKBC1101  Bundle_Material       A   
...                       ...          ...       ...              ...     ...   
167679             2025-06-30      Night-3  MHPT2305  Bundle_Material       C   
167680             2025-06-30      Night-3  MHPT2305  Bundle_Material       C   
167681             2025-06-30      Night-3  MHPT2305  Bundle_Material       C   
167891             2025-06-30      Night-3  MKTU2005  Bundle_Material       C   
167894             2025-06-30      Night-3  MKTU2005  Bundle_Material       C   

       AE_MODEL_CATEGORY             SIZE_TYPE SHIFT_NAME.1  \
386            Unplanned  Total Defense Shield  Afternoon-2   
387            Unplanned  Total Defense Shield  Afternoon-2   
389            Unplanned  Total Defense Shield  Afternoon-2   
392            Unplanned  Total Defense Shield  Afternoon-2   
393            Unplanned  Total Defense Shield  Afternoon-2   
...                  ...                   ...          ...   
167679         Unplanned  Total Defense Shield      Night-3   
167680         Unplanned  Total Defense Shield      Night-3   
167681         Unplanned  Total Defense Shield      Night-3   
167891         Unplanned      GreenClean Ultra      Night-3   
167894         Unplanned      GreenClean Ultra      Night-3   

                                  UTIL_REASON_DESCRIPTION  DOWNTIME  ...  \
386     06-Fiber boxT2-0602-Replace/adjust mechanical ...        15  ...   
387     11-Auto handle feederT1-1108-Replace/adjust me...        13  ...   
389           17-End Feeder - 1701-Double handle on chain        12  ...   
392                 13-FM chain - 1306-Handle stuck on FM        20  ...   
393     10-Trimming Unit - 1002-Replace details of Tri...        16  ...   
...                                                   ...       ...  ...   
167679              10-Robot - 1001-Adjust robot location        56  ...   
167680   07-Anchor wire feeding - 0702-Replace mechanical        20  ...   
167681                12-Filling tool - 1201-Cleaning Jaw         5  ...   
167891  11-Auto handle feeder - 1101-Double hadle on c...        15  ...   
167894  11-Auto handle feeder - 1102-Stuck handle on c...        15  ...   

        PRODUCTION_AVAILABLE_TIME  REJECT_PRODUCTION_QTY  RUN_TIME  \
386                            15                      0         0   
387                            13                      0         0   
389                            12                      0         0   
392                            20                      0         0   
393                            16                      0         0   
...                           ...                    ...       ...   
167679                         56                      0         0   
167680                         20                      0         0   
167681                          5                      0         0   
167891                         15                      0         0   
167894                         15                      0         0   

        CHANGEOVER_DURATION  CLEANING_AND_SANITIZATION  \
386                       0                          0   
387                       0                          0   
389                       0                          0   
392                       0                          0   
393                       0                          0   
...                     ...                        ...   
167679                    0                          0   
167680                    0                          0   
1

In [70]:
df_unplanned_bm.describe()

PRODUCTIONDATE_DAY_LOC     DOWNTIME  EFFECTIVE_RUNTIME  \
count                           3347  3347.000000             3347.0   
mean   2025-04-02 19:48:18.715267584    18.974007                0.0   
min              2025-01-02 00:00:00     1.000000                0.0   
25%              2025-02-28 00:00:00     9.000000                0.0   
50%              2025-04-04 00:00:00    12.000000                0.0   
75%              2025-05-12 12:00:00    20.000000                0.0   
max              2025-06-30 00:00:00   330.000000                0.0   
std                              NaN    23.711624                0.0   

       GOOD_PRODUCTION_QTY  LUNCH_AND_BREAK  MEETING_AND_TRAINING  NO_DEMAND  \
count               3347.0           3347.0                3347.0     3347.0   
mean                   0.0              0.0                   0.0        0.0   
min                    0.0              0.0                   0.0        0.0   
25%                    0.0              0.0                   0.0        0.0   
50%                    0.0              0.0                   0.0        0.0   
75%                    0.0              0.0                   0.0        0.0   
max                    0.0              0.0                   0.0        0.0   
std                    0.0              0.0                   0.0        0.0   

       PLANT_AVAILABLE_TIME  PLANT_EXPERIMENTATION  PRODUCTION_AVAILABLE_TIME  \
count           3347.000000                 3347.0                3347.000000   
mean              18.974007                    0.0                  18.974007   
min                1.000000                    0.0                   1.000000   
25%                9.000000                    0.0                   9.000000   
50%               12.000000                    0.0                  12.000000   
75%               20.000000                    0.0                  20.000000   
max              330.000000                    0.0                 330.000000   
std               23.711624                    0.0                  23.711624   

       REJECT_PRODUCTION_QTY  RUN_TIME  CHANGEOVER_DURATION  \
count                 3347.0    3347.0               3347.0   
mean                     0.0       0.0                  0.0   
min                      0.0       0.0                  0.0   
25%                      0.0       0.0                  0.0   
50%                      0.0       0.0                  0.0   
75%                      0.0       0.0                  0.0   
max                      0.0       0.0                  0.0   
std                      0.0       0.0                  0.0   

       CLEANING_AND_SANITIZATION  BUSINESS_EXTERNAL_TIME  PLANNED_MAINTENANCE  \
count                     3347.0                  3347.0               3347.0   
mean                         0.0                     0.0                  0.0   
min                          0.0                     0.0                  0.0   
25%                          0.0                     0.0                  0.0   
50%                          0.0                     0.0                  0.0   
75%                          0.0                     0.0                  0.0   
max                          0.0                     0.0                  0.0   
std                          0.0                     0.0                  0.0   

        TOTAL_TIME  WAITING_TIME  PRODUCTION_ORDER_RATE  
count  3347.000000        3347.0            3347.000000  
mean     18.974007           0.0              67.943878  
min       1.000000           0.0              20.000000  
25%       9.000000           0.0              63.160000  
50%      12.000000           0.0              67.000000  
75%      20.000000           0.0              78.900000  
max     330.000000           0.0             172.000000  
std      23.711624           0.0              16.135777

GOOD_PRODUCTION_QTY = REJECT_PRODUCTION_QTY	-> Không có sản phẩm đầu ra

Ta thấy các giá trị thống kê của DOWNTIME = PLANT_AVAILABLE_TIME và RUNTIME = 0 (Máy không thực hiện sản xuất sản phẩm và không được vận hành)

In [71]:
df_unplanned_bm['DOWNTIME'].equals(df_unplanned_bm['PLANT_AVAILABLE_TIME'])

True

In [72]:
df_unplanned_bm['PRODUCTION_AVAILABLE_TIME'].equals(df_unplanned_bm['PLANT_AVAILABLE_TIME'])

True

In [73]:
df_unplanned_bm["PRODUCTIONDATE_DAY_LOC"].value_counts()

PRODUCTIONDATE_DAY_LOC
2025-04-10    71
2025-04-09    71
2025-04-11    56
2025-05-17    55
2025-03-12    54
              ..
2025-02-03     5
2025-01-13     3
2025-01-24     3
2025-02-06     2
2025-02-18     1
Name: count, Length: 148, dtype: int64

In [74]:
df_unplanned_bm["LINE_NAME"].unique()

array(['MKBC1101', 'MKZA1401', 'MKBC0101', 'MKZA1501', 'MKBC1202',
       'MKBC0502', 'MKBC1001', 'MKBC0301', 'MKBC0901', 'MKTU2001',
       'MKTU2002', 'MKBC0302', 'MKBC0401', 'MKBC0902', 'MKBC0702',
       'MKZA1502', 'MKBC0402', 'MKBC1002', 'MHPT2305', 'MKTU2003',
       'MKTU2004', 'MKTU2006', 'MKBC1201', 'MKTU2005'], dtype=object)

In [75]:
df_unplanned_bm["LINE_NAME"].value_counts()

LINE_NAME
MHPT2305    1005
MKBC0901     437
MKBC0101     285
MKBC0902     213
MKBC0302     154
MKZA1401     152
MKBC0301     142
MKTU2002     142
MKZA1502     141
MKZA1501     125
MKBC0502      94
MKTU2001      81
MKBC1001      78
MKBC0702      61
MKBC1202      59
MKBC1002      58
MKTU2004      32
MKTU2006      23
MKBC1201      18
MKBC1101      16
MKTU2003       9
MKBC0401       8
MKBC0402       7
MKTU2005       7
Name: count, dtype: int64

In [76]:
df_unplanned_bm["SIZE_TYPE"].value_counts()

SIZE_TYPE
Total Defense Shield         1514
Classic Clean 100             497
ActiveClean Guard             256
Kids FunBrush (Tandy)         244
PureMint Fresh                236
Super Soft Tech               210
Deep Action White             114
Safari Explorer (Ages 6+)      68
Super Soft Pro                 59
Ocean Explorer (Ages 6+)       50
GreenClean Classic             49
Defense Action Pro             25
Zenith Classic Clean           13
GreenClean Ultra                9
Zenith Active                   2
EcoFresh Plus                   1
Name: count, dtype: int64

In [77]:
df_unplanned_bm["UTIL_REASON_DESCRIPTION"].unique()

array(['06-Fiber boxT2-0602-Replace/adjust mechanical parts of fiber beaters',
       '11-Auto handle feederT1-1108-Replace/adjust mechanical detail of Robot',
       '17-End Feeder - 1701-Double handle on chain',
       '13-FM chain - 1306-Handle stuck on FM',
       '10-Trimming Unit - 1002-Replace details of Trimming unit',
       '11-Auto handle feederT3-1107-Replace/adjust MECH parts of Hopper-Separator',
       '16-Autosorter - 1601-Handle on chain stuck',
       '02-Quality - 0202-Rework',
       '11-Auto handle feederT1-1101-Double hadle on chain',
       '11-Auto handle feederT2-1101-Double hadle on chain',
       '07-Anchor wire feedingT1-0703-Cleaning/adjust anchor wire feeding',
       '11-Auto handle feederT3-1101-Double hadle on chain',
       '11-Auto handle feederT1-1102-Stuck handle on chain',
       '17-End Feeder - 1702-Jammed handle on chain',
       '12-TurretT2-1201-Replace/adjust parts of turret',
       '04-Material - 0401-BOM shortage',
       '17-End Feeder - 

In [78]:
df_unplanned_bm["UTIL_REASON_DESCRIPTION"].value_counts()

UTIL_REASON_DESCRIPTION
03-Change material - 0301-Change material                   253
18-Autofeeder - 1802-Stuck handle on chain                  207
13-FM chain - 1306-Handle stuck on FM                       177
02-Quality - 0202-Rework                                    151
17-End Feeder - 1701-Double handle on chain                 147
                                                           ... 
11-Auto handle feederT2-1111-Replace/adjust sensor            1
18-Autofeeder - 1807-Cleaning mechanical(Pneumatic)           1
08-Process - 0803-Shortage handle                             1
29-Laser and vision system - 2901-Repair laser code date      1
07-Anchor wire feeding - 0702-Replace mechanical              1
Name: count, Length: 233, dtype: int64

In [79]:
# 1. Đếm tần suất xuất hiện của từng mô tả
desc_count = df_unplanned_bm['UTIL_REASON_DESCRIPTION'].value_counts().reset_index()
desc_count.columns = ['Description', 'Count']

# 2. Tính phần trăm và phần trăm tích lũy
desc_count['Percent'] = desc_count['Count'] / desc_count['Count'].sum()
desc_count['CumulativePercent'] = desc_count['Percent'].cumsum()

# 3. Lọc các Description nằm trong 80% đầu tiên
top_80 = desc_count[desc_count['CumulativePercent'] <= 0.8]

# Hiển thị kết quả
print(top_80)
print("\nTổng số dòng trong 80% đầu tiên:", top_80['Count'].sum())
print("Tổng số dòng toàn bộ:", desc_count['Count'].sum())
print("Tỷ lệ bao phủ:", round(top_80['Count'].sum() / desc_count['Count'].sum() * 100, 2), "%")

                                          Description  Count   Percent  \
0           03-Change material - 0301-Change material    253  0.075590   
1          18-Autofeeder - 1802-Stuck handle on chain    207  0.061846   
2               13-FM chain - 1306-Handle stuck on FM    177  0.052883   
3                            02-Quality - 0202-Rework    151  0.045115   
4         17-End Feeder - 1701-Double handle on chain    147  0.043920   
5         17-End Feeder - 1702-Jammed handle on chain    140  0.041829   
6                06-Fiber box - 0602-Adjust sparepart    123  0.036749   
7   11-Auto handle feederT1-1101-Double hadle on c...    119  0.035554   
8   11-Auto handle feederT3-1101-Double hadle on c...    103  0.030774   
9   11-Auto handle feederT2-1101-Double hadle on c...     99  0.029579   
10  11-Auto handle feederT1-1102-Stuck handle on c...     89  0.026591   
11  11-Auto handle feederT2-1102-Stuck handle on c...     89  0.026591   
12  11-Auto handle feederT3-1102-Stuck

Ta thấy top80 discription khá rời rạc, không tập trung vào một mô tả cụ thể nào => Tách cấu trúc description thành từng phần để dễ đánh giá

In [80]:
# Tách thành các phần với cách làm linh hoạt
split_desc = df_unplanned_bm['UTIL_REASON_DESCRIPTION'].str.split('-', n=3, expand=True)

# Tách phần máy (Machine / Line)
df_unplanned_bm['Machine_Area'] = split_desc[0] + '-' + split_desc[1]

# Tách mã lỗi (Error Code)
df_unplanned_bm['Error_Code'] = split_desc[2]

# Tách mô tả lỗi chi tiết
df_unplanned_bm['Error_Decrisption'] = split_desc[3]

/tmp/ipython-input-897553826.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unplanned_bm['Machine_Area'] = split_desc[0] + '-' + split_desc[1]
/tmp/ipython-input-897553826.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unplanned_bm['Error_Code'] = split_desc[2]
/tmp/ipython-input-897553826.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pan

In [81]:
df_unplanned_bm[['Machine_Area', 'Error_Code', 'Error_Decrisption']].head()

Machine_Area Error_Code  \
386           06-Fiber boxT2       0602   
387  11-Auto handle feederT1       1108   
389           17-End Feeder        1701   
392             13-FM chain        1306   
393        10-Trimming Unit        1002   

                                    Error_Decrisption  
386  Replace/adjust mechanical parts of fiber beaters  
387         Replace/adjust mechanical detail of Robot  
389                            Double handle on chain  
392                                Handle stuck on FM  
393                  Replace details of Trimming unit

In [82]:
df_unplanned_bm['Machine_Area'].value_counts()

Machine_Area
17-End Feeder                            351
18-Autofeeder                            287
11-Auto handle feederT1                  263
03-Change material                       254
06-Fiber box                             246
                                        ... 
04-MaterialT2                              1
09-Handle lifting device                   1
10-MechanicalT3                            1
15-Electrical cabinet/display(Hepta)       1
08-Process                                 1
Name: count, Length: 85, dtype: int64

In [128]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

tfidf = TfidfVectorizer(stop_words='english')
vec = tfidf.fit_transform(df_unplanned_bm['Error_Decrisption'])  # phần mô tả chi tiết sau split

In [84]:
from sklearn.metrics import silhouette_score

scores = []
for k in range(2, 16):
    kmeans = KMeans(n_clusters=k, random_state=42)
    labels = kmeans.fit_predict(vec)
    score = silhouette_score(vec, labels)
    scores.append((k, score))
    print(f"k={k}, Silhouette Score={score}")


k=2, Silhouette Score=0.20110210150827526
k=3, Silhouette Score=0.30991721109309744
k=4, Silhouette Score=0.35461768438446634
k=5, Silhouette Score=0.4177012492604669
k=6, Silhouette Score=0.42900324364190306
k=7, Silhouette Score=0.45043740540283445
k=8, Silhouette Score=0.4618156849131485
k=9, Silhouette Score=0.5016681268752905
k=10, Silhouette Score=0.559304491739638
k=11, Silhouette Score=0.5732156059966567
k=12, Silhouette Score=0.5964819949253884
k=13, Silhouette Score=0.6081691299910545
k=14, Silhouette Score=0.6412135337564668
k=15, Silhouette Score=0.6497200849671987


In [129]:
kmeans = KMeans(n_clusters=15, random_state=42)
df_unplanned_bm['cluster'] = kmeans.fit_predict(vec)

/tmp/ipython-input-1287086102.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unplanned_bm['cluster'] = kmeans.fit_predict(vec)


In [130]:
for i in range(15):  # vì n_clusters = 15
    print(f"\n------ Cluster {i} ------")
    sample = df_unplanned_bm[df_unplanned_bm['cluster'] == i]['Error_Decrisption'].head(10)
    print(sample.to_string(index=False))


------ Cluster 0 ------
Double handle on chain
Double handle on chain
Double handle on chain
 Double hadle on chain
 Double hadle on chain
 Double hadle on chain
Double handle on chain
 Double hadle on chain
 Double hadle on chain
 Double hadle on chain

------ Cluster 1 ------
Handle on chain stuck
Handle on chain stuck
Stuck handle on chain
Stuck handle on chain
Handle on chain stuck
Handle on chain stuck
Stuck handle on chain
Stuck handle on chain
Stuck handle on chain
Stuck handle on chain

------ Cluster 2 ------
Adjust parameter
Adjust parameter
Adjust parameter
Adjust parameter
Adjust parameter
Adjust parameter
Adjust parameter
Adjust parameter
Adjust parameter
Adjust parameter

------ Cluster 3 ------
Replace material
Replace material
Replace material
Replace material
Replace material
Replace material
Replace material
Replace material
 Change material
 Change material

------ Cluster 4 ------
Jammed handle on chain
Jammed handle on chain
Jammed handle on chain
Jammed handle on

In [131]:
# Dictionary: cluster_id -> tên mô tả lỗi
cluster_labels = {
    0: "Double handle on chain",
    1: "Stuck handle on chain",
    2: "Adjust machine parameter",
    3: "Change material",
    4: "Jammed handle on chain",
    5: "Mechanical adjustment / repair",
    6: "Replace fiber mechanism parts",
    7: "Adjust robot position / handle sorting",
    8: "Rework",
    9: "Handle stuck at FM",
    10: "FM / Sensor failure",
    11: "Picker gap / camera / BOM issue",
    12: "Cleaning / minor adjustment",
    13: "Lack of handle / waiting technician",
    14: "Replace/adjust turret parts"
}
# Gán tên cluster dựa trên dictionary
df_unplanned_bm['cluster_label'] = df_unplanned_bm['cluster'].map(cluster_labels)

# Kiểm tra kết quả
df_unplanned_bm[['Error_Decrisption', 'cluster', 'cluster_label']].head(20)


/tmp/ipython-input-1044094222.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unplanned_bm['cluster_label'] = df_unplanned_bm['cluster'].map(cluster_labels)


Error_Decrisption  cluster  \
386   Replace/adjust mechanical parts of fiber beaters        6   
387          Replace/adjust mechanical detail of Robot        5   
389                             Double handle on chain        0   
392                                 Handle stuck on FM        9   
393                   Replace details of Trimming unit        5   
492      Replace/adjust MECH parts of Hopper-Separator       11   
494                             Double handle on chain        0   
496                              Handle on chain stuck        1   
845                                             Rework        8   
962                                 Handle stuck on FM        9   
963                             Double handle on chain        0   
1089                             Double hadle on chain        0   
1090                                Handle stuck on FM        9   
1091                             Double hadle on chain        0   
1093               Cleaning/adjust anchor wire feeding       12   
1095                             Double hadle on chain        0   
1190                                            Rework        8   
1191                            Double handle on chain        0   
1546                                            Rework        8   
1547                             Handle on chain stuck        1   

                        cluster_label  
386     Replace fiber mechanism parts  
387    Mechanical adjustment / repair  
389            Double handle on chain  
392                Handle stuck at FM  
393    Mechanical adjustment / repair  
492   Picker gap / camera / BOM issue  
494            Double handle on chain  
496             Stuck handle on chain  
845                            Rework  
962                Handle stuck at FM  
963            Double handle on chain  
1089           Double handle on chain  
1090               Handle stuck at FM  
1091           Double handle on chain  
1093      Cleaning / minor adjustment  
1095           Double handle on chain  
1190                           Rework  
1191           Double handle on chain  
1546                           Rework  
1547            Stuck handle on chain

In [132]:
df_unplanned_bm['cluster_label'].value_counts()

cluster_label
Stuck handle on chain                     593
Double handle on chain                    577
Picker gap / camera / BOM issue           328
Change material                           287
Adjust robot position / handle sorting    248
Mechanical adjustment / repair            216
Adjust machine parameter                  194
Handle stuck at FM                        182
Rework                                    151
Jammed handle on chain                    147
Lack of handle / waiting technician       112
Cleaning / minor adjustment               106
Replace fiber mechanism parts              96
FM / Sensor failure                        64
Replace/adjust turret parts                46
Name: count, dtype: int64

In [134]:
def detect_anomaly_full(df, cluster_name, group_col, top_n=5):
    df_cluster = df[df['cluster_label'] == cluster_name]
    counts = df_cluster[group_col].value_counts()
    percent = df_cluster[group_col].value_counts(normalize=True) * 100

    result = pd.DataFrame({
        'count': counts,
        'percent (%)': percent
    }).head(top_n)

    return result

In [136]:
for cluster in df_unplanned_bm['cluster_label'].unique():
    print(f"\n======  Cluster: {cluster} ======")
    anomaly_line = detect_anomaly_full(df_unplanned_bm, cluster, "LINE_NAME")
    anomaly_crew = detect_anomaly_full(df_unplanned_bm, cluster, "CREW_ID")
    anomaly_size = detect_anomaly_full(df_unplanned_bm, cluster, "SIZE_TYPE")

    print("\n➡ Top 5 LINE_NAME bất thường:")
    print(anomaly_line)

    print("\n➡ Top 5 CREW_ID bất thường:")
    print(anomaly_crew)

    print("\n➡ Top 5 SIZE_TYPE bất thường:")
    print(anomaly_size)


======  Cluster: Replace fiber mechanism parts ======

➡ Top 5 LINE_NAME bất thường:
           count  percent (%)
LINE_NAME                    
MKTU2001      22    22.916667
MKTU2002      21    21.875000
MKBC0901      14    14.583333
MKBC0902       8     8.333333
MKBC1001       7     7.291667

➡ Top 5 CREW_ID bất thường:
         count  percent (%)
CREW_ID                    
C           37    38.541667
B           32    33.333333
A           27    28.125000

➡ Top 5 SIZE_TYPE bất thường:
                      count  percent (%)
SIZE_TYPE                               
PureMint Fresh           44    45.833333
Classic Clean 100        16    16.666667
Total Defense Shield     13    13.541667
Deep Action White         6     6.250000
GreenClean Classic        5     5.208333

======  Cluster: Mechanical adjustment / repair ======

➡ Top 5 LINE_NAME bất thường:
           count  percent (%)
LINE_NAME                    
MKBC0901      44    20.370370
MHPT2305      40    18.518519
MKBC0902  

In [133]:
def detect_high_impact_low_frequency(df, error_col='Error_Type', downtime_col='Downtime'):
    # Tổng toàn bộ lỗi và downtime
    total_errors = df.shape[0]
    total_downtime = df[downtime_col].sum()

    # Gom nhóm theo từng loại lỗi
    summary = df.groupby(error_col).agg(
        error_count=(error_col, 'count'),
        total_downtime=(downtime_col, 'sum')
    )

    # Tính % lỗi và % downtime
    summary['error_percent'] = summary['error_count'] / total_errors * 100
    summary['downtime_percent'] = summary['total_downtime'] / total_downtime * 100

    # Lọc lỗi xuất hiện ít (<30%) nhưng gây downtime lớn (>70%)
    result = summary[(summary['error_percent'] < 30) & (summary['downtime_percent'] > 70)]

    return summary.sort_values(by='downtime_percent', ascending=False), result

# Nếu cột lỗi của bạn tên là "cluster_label"
summary, high_impact_errors = detect_high_impact_low_frequency(
    df_unplanned_bm, error_col='cluster_label', downtime_col='DOWNTIME'
)

print("Tổng quan lỗi & downtime theo từng loại:")
print(summary)

print("\nLỖI ÍT NHƯNG GÂY ẢNH HƯỞNG LỚN:")
print(high_impact_errors if not high_impact_errors.empty else "Không tìm thấy loại lỗi nào thuộc dạng này.")


Tổng quan lỗi & downtime theo từng loại:
                                        error_count  total_downtime  \
cluster_label                                                         
Rework                                          151           12431   
Picker gap / camera / BOM issue                 328            8832   
Double handle on chain                          577            6848   
Stuck handle on chain                           593            6794   
Adjust robot position / handle sorting          248            6595   
Mechanical adjustment / repair                  216            4727   
Adjust machine parameter                        194            3011   
Handle stuck at FM                              182            2991   
Jammed handle on chain                          147            2497   
Change material                                 287            2220   
Cleaning / minor adjustment                     106            1536   
Replace fiber mechanism parts       

## CO_TYPE == Tooling

Thay đổi, điều chỉnh, hoặc bảo trì dụng cụ/khuôn mẫu.	Thời gian dành cho việc thay thế, điều chỉnh hoặc bảo trì các dụng cụ (tooling), khuôn mẫu (như đầu tufting, dao cắt, v.v.) được sử dụng trong quá trình sản xuất.


In [89]:
df_unplanned_t = df_unplanned[df_unplanned['CO_TYPE'] == "Tooling"]
df_unplanned_t

PRODUCTIONDATE_DAY_LOC   SHIFT_NAME LINE_NAME  CO_TYPE CREW_ID  \
476                2025-01-02  Afternoon-2  MKTU2005  Tooling       A   
477                2025-01-02  Afternoon-2  MKTU2005  Tooling       A   
480                2025-01-02  Afternoon-2  MKTU2005  Tooling       A   
485                2025-01-02  Afternoon-2  MKTU2005  Tooling       A   
834                2025-01-02        Day-1  MKTU2005  Tooling       C   
...                       ...          ...       ...      ...     ...   
167256             2025-06-30  Afternoon-2  MKTU2003  Tooling       B   
167257             2025-06-30  Afternoon-2  MKTU2003  Tooling       B   
167259             2025-06-30  Afternoon-2  MKTU2003  Tooling       B   
167562             2025-06-30        Day-1  MKTU2003  Tooling       A   
167564             2025-06-30        Day-1  MKTU2003  Tooling       A   

       AE_MODEL_CATEGORY       SIZE_TYPE SHIFT_NAME.1  \
476            Unplanned  EcoFresh Green  Afternoon-2   
477            Unplanned  EcoFresh Green  Afternoon-2   
480            Unplanned  EcoFresh Green  Afternoon-2   
485            Unplanned  EcoFresh Green  Afternoon-2   
834            Unplanned  EcoFresh Green        Day-1   
...                  ...             ...          ...   
167256         Unplanned  EcoFresh Green  Afternoon-2   
167257         Unplanned  EcoFresh Green  Afternoon-2   
167259         Unplanned  EcoFresh Green  Afternoon-2   
167562         Unplanned  EcoFresh Green        Day-1   
167564         Unplanned  EcoFresh Green        Day-1   

                                  UTIL_REASON_DESCRIPTION  DOWNTIME  ...  \
476     11-Auto handle feeder - 1107-Replace/adjust ME...        55  ...   
477     14-Fiber picker   - 1401-Adjust gap of fiber p...        60  ...   
480     11-Auto handle feeder - 1103-Adjust robot posi...        40  ...   
485     18-Main shaft - 1802-Adjust date code stamp po...        29  ...   
834     11-Auto handle feeder - 1104-Lack of handle on...        10  ...   
...                                                   ...       ...  ...   
167256                           02-Quality - 0202-Rework        30  ...   
167257  14-Fiber picker   - 1401-Adjust gap of fiber p...        60  ...   
167259  07-Anchor wire feeding - 0703-Cleaning/adjust ...        60  ...   
167562  06-Fiber box - 0602-Replace/adjust mechanical ...        64  ...   
167564  14-Fiber picker   - 1401-Adjust gap of fiber p...       130  ...   

        PRODUCTION_AVAILABLE_TIME  REJECT_PRODUCTION_QTY  RUN_TIME  \
476                            55                      0         0   
477                            60                      0         0   
480                            40                      0         0   
485                            29                      0         0   
834                            10                      0         0   
...                           ...                    ...       ...   
167256                         30                      0         0   
167257                         60                      0         0   
167259                         60                      0         0   
167562                         64                      0         0   
167564                        130                      0         0   

        CHANGEOVER_DURATION  CLEANING_AND_SANITIZATION  \
476                       0                          0   
477                       0                          0   
480                       0                          0   
485                       0                          0   
834                       0                          0   
...                     ...                        ...   
167256                    0                          0   
167257                    0                          0   
167259                    0                          0   
167562                    0                          0   
167564                    0                          

In [90]:
df_unplanned_t.describe()

PRODUCTIONDATE_DAY_LOC     DOWNTIME  EFFECTIVE_RUNTIME  \
count                           1967  1967.000000             1967.0   
mean   2025-03-21 22:15:18.759532032    27.258261                0.0   
min              2025-01-02 00:00:00     3.000000                0.0   
25%              2025-02-14 00:00:00    12.000000                0.0   
50%              2025-03-21 00:00:00    20.000000                0.0   
75%              2025-04-25 00:00:00    30.000000                0.0   
max              2025-06-30 00:00:00   307.000000                0.0   
std                              NaN    28.619943                0.0   

       GOOD_PRODUCTION_QTY  LUNCH_AND_BREAK  MEETING_AND_TRAINING  NO_DEMAND  \
count               1967.0           1967.0                1967.0     1967.0   
mean                   0.0              0.0                   0.0        0.0   
min                    0.0              0.0                   0.0        0.0   
25%                    0.0              0.0                   0.0        0.0   
50%                    0.0              0.0                   0.0        0.0   
75%                    0.0              0.0                   0.0        0.0   
max                    0.0              0.0                   0.0        0.0   
std                    0.0              0.0                   0.0        0.0   

       PLANT_AVAILABLE_TIME  PLANT_EXPERIMENTATION  PRODUCTION_AVAILABLE_TIME  \
count           1967.000000                 1967.0                1967.000000   
mean              27.258261                    0.0                  27.258261   
min                3.000000                    0.0                   3.000000   
25%               12.000000                    0.0                  12.000000   
50%               20.000000                    0.0                  20.000000   
75%               30.000000                    0.0                  30.000000   
max              307.000000                    0.0                 307.000000   
std               28.619943                    0.0                  28.619943   

       REJECT_PRODUCTION_QTY  RUN_TIME  CHANGEOVER_DURATION  \
count                 1967.0    1967.0               1967.0   
mean                     0.0       0.0                  0.0   
min                      0.0       0.0                  0.0   
25%                      0.0       0.0                  0.0   
50%                      0.0       0.0                  0.0   
75%                      0.0       0.0                  0.0   
max                      0.0       0.0                  0.0   
std                      0.0       0.0                  0.0   

       CLEANING_AND_SANITIZATION  BUSINESS_EXTERNAL_TIME  PLANNED_MAINTENANCE  \
count                     1967.0                  1967.0               1967.0   
mean                         0.0                     0.0                  0.0   
min                          0.0                     0.0                  0.0   
25%                          0.0                     0.0                  0.0   
50%                          0.0                     0.0                  0.0   
75%                          0.0                     0.0                  0.0   
max                          0.0                     0.0                  0.0   
std                          0.0                     0.0                  0.0   

        TOTAL_TIME  WAITING_TIME  PRODUCTION_ORDER_RATE  
count  1967.000000        1967.0            1967.000000  
mean     27.258261           0.0              66.123294  
min       3.000000           0.0              20.000000  
25%      12.000000           0.0              60.000000  
50%      20.000000           0.0              78.900000  
75%      30.000000           0.0              78.900000  
max     307.000000           0.0             157.800000  
std      28.619943           0.0              22.020238

GOOD_PRODUCTION_QTY = REJECT_PRODUCTION_QTY	-> Không có sản phẩm đầu ra

Ta thấy các giá trị thống kê của DOWNTIME = PLANT_AVAILABLE_TIME và RUNTIME = 0 (Máy không thực hiện sản xuất sản phẩm và không được vận hành)

In [91]:
df_unplanned_t['DOWNTIME'].equals(df_unplanned_t['PLANT_AVAILABLE_TIME'])

True

In [92]:
df_unplanned_t['PRODUCTION_AVAILABLE_TIME'].equals(df_unplanned_t['PLANT_AVAILABLE_TIME'])

True

In [93]:
df_unplanned_t["PRODUCTIONDATE_DAY_LOC"].value_counts()

PRODUCTIONDATE_DAY_LOC
2025-03-18    50
2025-01-14    49
2025-01-15    46
2025-01-18    38
2025-03-22    36
              ..
2025-04-19     3
2025-04-24     2
2025-02-08     2
2025-06-13     2
2025-01-04     1
Name: count, Length: 130, dtype: int64

In [94]:
df_unplanned_t["LINE_NAME"].unique()

array(['MKTU2005', 'MKBC0702', 'MKBC1202', 'MKZA1502', 'MKBC0501',
       'MKBC0302', 'MKBC0102', 'MKZA1701', 'MKBC1301', 'MKTU2003',
       'MKBC1002', 'MKBC1201', 'MKTU2004', 'MKBC0502', 'MKBC0901',
       'MKTU2006', 'MKBC0401', 'MKTU2002', 'MKBC0902', 'MKBC0202'],
      dtype=object)

In [95]:
df_unplanned_t["LINE_NAME"].value_counts()

LINE_NAME
MKBC1202    522
MKBC1201    277
MKZA1502    135
MKTU2003    118
MKBC0702    102
MKTU2004     96
MKBC0401     90
MKBC0102     90
MKBC1301     85
MKTU2005     84
MKBC0502     78
MKBC0901     62
MKBC0501     49
MKZA1701     45
MKTU2006     42
MKTU2002     25
MKBC0302     23
MKBC1002     16
MKBC0902     14
MKBC0202     14
Name: count, dtype: int64

In [96]:
df_unplanned_t["SIZE_TYPE"].value_counts()

SIZE_TYPE
Classic White 110               775
Classic Clean 100               226
Total Action Green              119
GreenClean Pro                   94
Super Soft Tech                  88
Pro-Clean 5000                   77
Junior Sparkle (Ages 2+)         73
Zenith GreenClean                71
Total Action Model S             71
PureMint Fresh                   55
Deep Action White                51
Pro-Shield Complete              50
Advanced Hydro-Clean             43
EcoFresh Green                   40
EcoFresh Plus                    31
Junior Guard Taper (Ages 5+)     25
Total Defense Shield             22
GreenClean Classic               15
ActiveClean Guard                15
Defense Action Pro               10
EcoSoft Classic                   6
Zenith Active                     6
Kids FunBrush (Tandy)             3
Ocean Explorer (Ages 6+)          1
Name: count, dtype: int64

In [97]:
df_unplanned_t["UTIL_REASON_DESCRIPTION"].unique()

array(['11-Auto handle feeder - 1107-Replace/adjust MECH parts of Hopper-Separator',
       '14-Fiber picker   - 1401-Adjust gap of fiber picker and picker guide',
       '11-Auto handle feeder - 1103-Adjust robot position',
       '18-Main shaft - 1802-Adjust date code stamp position',
       '11-Auto handle feeder - 1104-Lack of handle on chain',
       '14-Fiber picker  T1-1401-Adjust gap of fiber picker and picker guide',
       '17-End Feeder - 1702-Jammed handle on chain',
       '14-Fiber picker  T3-1401-Adjust gap of fiber picker and picker guide',
       '12-Dust collector - 1203-Clean filter',
       '06-Fiber boxT2-0602-Replace/adjust mechanical parts of fiber beaters',
       '11-Auto handle feederT3-1103-Adjust robot position',
       '11-Auto handle feederT2-1102-Stuck handle on chain',
       '13-FM chain - 1306-Handle stuck on FM',
       '11-Auto handle feederT1-1101-Double hadle on chain',
       '11-Auto handle feeder - 1102-Stuck handle on chain',
       '11-Auto ha

In [98]:
df_unplanned_t["UTIL_REASON_DESCRIPTION"].value_counts()

UTIL_REASON_DESCRIPTION
17-End Feeder - 1702-Jammed handle on chain                                   216
13-FM chain - 1306-Handle stuck on FM                                         191
02-Quality - 0202-Rework                                                      127
11-Auto handle feederT1-1101-Double hadle on chain                             61
11-Auto handle feederT2-1102-Stuck handle on chain                             58
                                                                             ... 
07-Anchor wire feedingT2-0704-Adjust the length of anchor wire                  1
16-Coordination - 1603-Replace/adjust mechanical detail of coordination         1
11-Auto handle feeder - 1109-Replace/clean pneumatics components                1
11-Auto handle feederT1-1112-Clean mechanical detail                            1
11-Auto handle feederT2-1107-Replace/adjust MECH parts of Hopper-Separator      1
Name: count, Length: 194, dtype: int64

In [99]:
# 1. Đếm tần suất xuất hiện của từng mô tả
desc_count = df_unplanned_t['UTIL_REASON_DESCRIPTION'].value_counts().reset_index()
desc_count.columns = ['Description', 'Count']

# 2. Tính phần trăm và phần trăm tích lũy
desc_count['Percent'] = desc_count['Count'] / desc_count['Count'].sum()
desc_count['CumulativePercent'] = desc_count['Percent'].cumsum()

# 3. Lọc các Description nằm trong 80% đầu tiên
top_80 = desc_count[desc_count['CumulativePercent'] <= 0.8]

# Hiển thị kết quả
print(top_80)
print("\nTổng số dòng trong 80% đầu tiên:", top_80['Count'].sum())
print("Tổng số dòng toàn bộ:", desc_count['Count'].sum())
print("Tỷ lệ bao phủ:", round(top_80['Count'].sum() / desc_count['Count'].sum() * 100, 2), "%")

                                          Description  Count   Percent  \
0         17-End Feeder - 1702-Jammed handle on chain    216  0.109812   
1               13-FM chain - 1306-Handle stuck on FM    191  0.097102   
2                            02-Quality - 0202-Rework    127  0.064565   
3   11-Auto handle feederT1-1101-Double hadle on c...     61  0.031012   
4   11-Auto handle feederT2-1102-Stuck handle on c...     58  0.029487   
5   14-Fiber picker   - 1401-Adjust gap of fiber p...     54  0.027453   
6   11-Auto handle feederT3-1101-Double hadle on c...     49  0.024911   
7   11-Auto handle feederT1-1102-Stuck handle on c...     48  0.024403   
8          17-End Feeder - 1705-Mechanical Adjustment     46  0.023386   
9   06-Fiber box - 0602-Replace/adjust mechanical ...     45  0.022877   
10        17-End Feeder - 1701-Double handle on chain     45  0.022877   
11  11-Auto handle feederT2-1101-Double hadle on c...     44  0.022369   
12  11-Auto handle feederT3-1102-Stuck

Ta thấy top80 discription khá rời rạc, không tập trung vào một mô tả cụ thể nào => Tách cấu trúc description thành từng phần để dễ đánh giá

In [100]:
# Tách thành các phần với cách làm linh hoạt
split_desc = df_unplanned_t['UTIL_REASON_DESCRIPTION'].str.split('-', n=3, expand=True)

# Tách phần máy (Machine / Line)
df_unplanned_t['Machine_Area'] = split_desc[0] + '-' + split_desc[1]

# Tách mã lỗi (Error Code)
df_unplanned_t['Error_Code'] = split_desc[2]

# Tách mô tả lỗi chi tiết
df_unplanned_t['Error_Decrisption'] = split_desc[3]

/tmp/ipython-input-248826308.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unplanned_t['Machine_Area'] = split_desc[0] + '-' + split_desc[1]
/tmp/ipython-input-248826308.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unplanned_t['Error_Code'] = split_desc[2]
/tmp/ipython-input-248826308.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://panda

In [101]:
df_unplanned_t[['Machine_Area', 'Error_Code', 'Error_Decrisption']].head()

Machine_Area Error_Code  \
476  11-Auto handle feeder        1107   
477      14-Fiber picker          1401   
480  11-Auto handle feeder        1103   
485          18-Main shaft        1802   
834  11-Auto handle feeder        1104   

                                 Error_Decrisption  
476  Replace/adjust MECH parts of Hopper-Separator  
477    Adjust gap of fiber picker and picker guide  
480                          Adjust robot position  
485                Adjust date code stamp position  
834                        Lack of handle on chain

In [102]:
df_unplanned_t['Machine_Area'].value_counts()

Machine_Area
17-End Feeder                      335
13-FM chain                        222
11-Auto handle feederT1            148
11-Auto handle feederT2            144
11-Auto handle feederT3            139
                                  ... 
18-Main shaftT3                      1
01-SafetyT1                          1
17-Main shaftT2                      1
15-Electrical cabinet/displayT2      1
15-Electrical cabinet/displayT1      1
Name: count, Length: 63, dtype: int64

In [137]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

tfidf = TfidfVectorizer(stop_words='english')
vec = tfidf.fit_transform(df_unplanned_t['Error_Decrisption'])  # phần mô tả chi tiết sau split

In [104]:
from sklearn.metrics import silhouette_score

scores = []
for k in range(2, 16):
    kmeans = KMeans(n_clusters=k, random_state=42)
    labels = kmeans.fit_predict(vec)
    score = silhouette_score(vec, labels)
    scores.append((k, score))
    print(f"k={k}, Silhouette Score={score}")


k=2, Silhouette Score=0.1886701822628694
k=3, Silhouette Score=0.24787659300838394
k=4, Silhouette Score=0.2721954057273554
k=5, Silhouette Score=0.3538529560363634
k=6, Silhouette Score=0.3563696680579255
k=7, Silhouette Score=0.3727571508941615
k=8, Silhouette Score=0.5239708303938585
k=9, Silhouette Score=0.5872391884996089
k=10, Silhouette Score=0.6009628632168311
k=11, Silhouette Score=0.615816177019389
k=12, Silhouette Score=0.618742089979909
k=13, Silhouette Score=0.6502344134838013
k=14, Silhouette Score=0.6585493063633883
k=15, Silhouette Score=0.6725593198075531


In [138]:
kmeans = KMeans(n_clusters=15, random_state=42)
df_unplanned_t['cluster'] = kmeans.fit_predict(vec)

/tmp/ipython-input-1170859561.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unplanned_t['cluster'] = kmeans.fit_predict(vec)


In [139]:
for i in range(15):  # vì n_clusters = 15
    print(f"\n------ Cluster {i} ------")
    sample = df_unplanned_t[df_unplanned_t['cluster'] == i]['Error_Decrisption'].head(10)
    print(sample.to_string(index=False))


------ Cluster 0 ------
Handle stuck on FM
   Adjust FM chain
   Adjust FM chain
Handle stuck on FM
Handle stuck on FM
Handle stuck on FM
Handle stuck on FM
Handle stuck on FM
Handle stuck on FM
Handle stuck on FM

------ Cluster 1 ------
 Replace/adjust mechanical parts of fiber beaters
 Replace/adjust mechanical parts of fiber beaters
        Replace/adjust mechanical detail on chain
  Replace/adjust mechanical details of driver tip
        Replace/adjust mechanical detail on chain
        Replace/adjust mechanical detail on chain
       Replace mechanical details of fiber picker
 Replace/adjust mechanical parts of fiber beaters
Replace/adjust mechanical details of Filling tool
        Replace/adjust mechanical detail of Robot

------ Cluster 2 ------
 Double hadle on chain
 Double hadle on chain
 Double hadle on chain
 Double hadle on chain
 Double hadle on chain
Double handle on chain
 Double hadle on chain
 Double hadle on chain
Double handle on chain
Double handle on chain

----

In [140]:
# Dictionary: cluster_id -> tên mô tả lỗi
cluster_labels = {
    0: "Handle stuck at FM / Adjust FM chain",
    1: "Replace/adjust mechanical parts",
    2: "Double handle on chain",
    3: "Jammed handle on chain",
    4: "Lack or stuck handle on chain",
    5: "Rework",
    6: "Sensor / mechanical minor adjustment",
    7: "Adjust handle supply box position",
    8: "Adjust fiber picker gap",
    9: "Waiting for technician / lack of skill",
    10: "Adjust robot position",
    11: "Robot/date code stamp position adjustment",
    12: "Adjust machine parameters",
    13: "Replace/adjust trimming & endrounding parts",
    14: "Clean / repair hopper, cutter, camera"
}
# Gán tên cluster dựa trên dictionary
df_unplanned_t['cluster_label'] = df_unplanned_t['cluster'].map(cluster_labels)

# Kiểm tra kết quả
df_unplanned_t[['Error_Decrisption', 'cluster', 'cluster_label']].head(20)


/tmp/ipython-input-1282561111.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unplanned_t['cluster_label'] = df_unplanned_t['cluster'].map(cluster_labels)


Error_Decrisption  cluster  \
476      Replace/adjust MECH parts of Hopper-Separator       14   
477        Adjust gap of fiber picker and picker guide        8   
480                              Adjust robot position       11   
485                    Adjust date code stamp position       11   
834                            Lack of handle on chain        4   
2837       Adjust gap of fiber picker and picker guide        8   
3558                            Jammed handle on chain        3   
3886       Adjust gap of fiber picker and picker guide        8   
3891                                      Clean filter       14   
3892  Replace/adjust mechanical parts of fiber beaters        1   
3894       Adjust gap of fiber picker and picker guide        8   
4193                            Jammed handle on chain        3   
4196                             Adjust robot position       11   
4197                             Stuck handle on chain        4   
4199                                Handle stuck on FM        0   
4200                             Double hadle on chain        2   
4646                             Stuck handle on chain        4   
4647                             Double hadle on chain        2   
4649                                            Rework        5   
4672                                     Adjust cutter       14   

                                  cluster_label  
476       Clean / repair hopper, cutter, camera  
477                     Adjust fiber picker gap  
480   Robot/date code stamp position adjustment  
485   Robot/date code stamp position adjustment  
834               Lack or stuck handle on chain  
2837                    Adjust fiber picker gap  
3558                     Jammed handle on chain  
3886                    Adjust fiber picker gap  
3891      Clean / repair hopper, cutter, camera  
3892            Replace/adjust mechanical parts  
3894                    Adjust fiber picker gap  
4193                     Jammed handle on chain  
4196  Robot/date code stamp position adjustment  
4197              Lack or stuck handle on chain  
4199       Handle stuck at FM / Adjust FM chain  
4200                     Double handle on chain  
4646              Lack or stuck handle on chain  
4647                     Double handle on chain  
4649                                     Rework  
4672      Clean / repair hopper, cutter, camera

In [141]:
df_unplanned_t['cluster_label'].value_counts()

cluster_label
Double handle on chain                         241
Replace/adjust mechanical parts                240
Lack or stuck handle on chain                  232
Jammed handle on chain                         216
Clean / repair hopper, cutter, camera          215
Handle stuck at FM / Adjust FM chain           193
Adjust fiber picker gap                        169
Rework                                         127
Robot/date code stamp position adjustment       99
Replace/adjust trimming & endrounding parts     64
Sensor / mechanical minor adjustment            49
Adjust machine parameters                       44
Adjust robot position                           38
Waiting for technician / lack of skill          25
Adjust handle supply box position               15
Name: count, dtype: int64

In [142]:
def detect_anomaly_full(df, cluster_name, group_col, top_n=5):
    df_cluster = df[df['cluster_label'] == cluster_name]
    counts = df_cluster[group_col].value_counts()
    percent = df_cluster[group_col].value_counts(normalize=True) * 100

    result = pd.DataFrame({
        'count': counts,
        'percent (%)': percent
    }).head(top_n)

    return result

In [143]:
for cluster in df_unplanned_t['cluster_label'].unique():
    print(f"\n======  Cluster: {cluster} ======")
    anomaly_line = detect_anomaly_full(df_unplanned_t, cluster, "LINE_NAME")
    anomaly_crew = detect_anomaly_full(df_unplanned_t, cluster, "CREW_ID")
    anomaly_size = detect_anomaly_full(df_unplanned_t, cluster, "SIZE_TYPE")

    print("\n➡ Top 5 LINE_NAME bất thường:")
    print(anomaly_line)

    print("\n➡ Top 5 CREW_ID bất thường:")
    print(anomaly_crew)

    print("\n➡ Top 5 SIZE_TYPE bất thường:")
    print(anomaly_size)


======  Cluster: Clean / repair hopper, cutter, camera ======

➡ Top 5 LINE_NAME bất thường:
           count  percent (%)
LINE_NAME                    
MKBC1202      53    24.651163
MKBC1201      21     9.767442
MKZA1502      18     8.372093
MKBC0102      14     6.511628
MKBC0502      14     6.511628

➡ Top 5 CREW_ID bất thường:
         count  percent (%)
CREW_ID                    
A          109    50.697674
C           57    26.511628
B           49    22.790698

➡ Top 5 SIZE_TYPE bất thường:
                      count  percent (%)
SIZE_TYPE                               
Classic White 110        76    35.348837
Classic Clean 100        27    12.558140
Total Action Green       17     7.906977
Pro-Clean 5000           14     6.511628
Total Action Model S     13     6.046512

======  Cluster: Adjust fiber picker gap ======

➡ Top 5 LINE_NAME bất thường:
           count  percent (%)
LINE_NAME                    
MKTU2003      23    13.609467
MKBC1301      19    11.242604
MKBC1202 

In [144]:
def detect_high_impact_low_frequency(df, error_col='Error_Type', downtime_col='Downtime'):
    # Tổng toàn bộ lỗi và downtime
    total_errors = df.shape[0]
    total_downtime = df[downtime_col].sum()

    # Gom nhóm theo từng loại lỗi
    summary = df.groupby(error_col).agg(
        error_count=(error_col, 'count'),
        total_downtime=(downtime_col, 'sum')
    )

    # Tính % lỗi và % downtime
    summary['error_percent'] = summary['error_count'] / total_errors * 100
    summary['downtime_percent'] = summary['total_downtime'] / total_downtime * 100

    # Lọc lỗi xuất hiện ít (<30%) nhưng gây downtime lớn (>70%)
    result = summary[(summary['error_percent'] < 30) & (summary['downtime_percent'] > 70)]

    return summary.sort_values(by='downtime_percent', ascending=False), result

# Nếu cột lỗi của bạn tên là "cluster_label"
summary, high_impact_errors = detect_high_impact_low_frequency(
    df_unplanned_t, error_col='cluster_label', downtime_col='DOWNTIME'
)

print("Tổng quan lỗi & downtime theo từng loại:")
print(summary)

print("\nLỖI ÍT NHƯNG GÂY ẢNH HƯỞNG LỚN:")
print(high_impact_errors if not high_impact_errors.empty else "Không tìm thấy loại lỗi nào thuộc dạng này.")


Tổng quan lỗi & downtime theo từng loại:
                                             error_count  total_downtime  \
cluster_label                                                              
Rework                                               127           11483   
Replace/adjust mechanical parts                      240            6332   
Clean / repair hopper, cutter, camera                215            5871   
Adjust fiber picker gap                              169            5270   
Jammed handle on chain                               216            4479   
Handle stuck at FM / Adjust FM chain                 193            4012   
Double handle on chain                               241            3633   
Lack or stuck handle on chain                        232            3331   
Robot/date code stamp position adjustment             99            2333   
Replace/adjust trimming & endrounding parts           64            2114   
Sensor / mechanical minor adjustment           